### ISSUE TITLE
Please test updating the study type

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#101]
Related to: https://github.com/clarity-h2020/docker-drupal/issues/91

New rules for UPDATING the study are activated, Please test:

1. Add new study (or use old one)
2. Change study type
3. See if the GL steps are defined as they should be (aligned with the study type).

**Comment by p-a-s-c-a-l** [comment]
I'm not going to test this. IMHO this functionality is not needed, moreover it introduces unnecessary complexity which we are not able to handle ATM since it binds to many resources that are urgently needed elsewhere. Therefore it should be disabled .

**Comment by DenoBeno** [comment]
If you don't want to test it, it's fine with me. I've tested it and to the best of my knowledge it works perfectly. I just wanted to be 100% sure before enabling it for inserts. 

I'm going to enable it for the study insert now and all the new studies will use it - if it turns out that this isn't working 100% perfect, please open a new ticket.

Oh, by the way: you probably consider "handling updates" the unnecessary complexity. Actually it's not, all it does is to reset the study so you basically have a new one. Actually it doesn't reset the group, just the group nodes so there *could* be some artefacts due to this, but it's still convenient for testing. 

Anyway: in a few minutes, all new studies will use the gl-step templates. If you encounter any difficulties, first look at the template definition and fix it if needed..
