### ISSUE TITLE
Cannot create new iFRames

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#102]
Cannot create new nodes of type *extended iframe*. After saving the new node the iFrame HTML is transformed from 

```html
<iframe 
id="map-component" 
src="/apps/map-component/build/index.html?study_uuid=c3609e3e-f80f-482b-9e9f-3a26226a6859 
style="width:100%;height:400px">
</iframe>
```

to 

```html
<p><iframe 
id="map-component" 
src="/apps/map-component/build/index.html?study_uuid=c3609e3e-f80f-482b-9e9f-3a26226a6859 
style=" width:100="">
</iframe></p>
```

Note how the `style` attribute got "destroyed"! Perhaps a problem with the new theme?

**Comment by DenoBeno** [comment]
This is most probably the issue with the filters. Try usign the "full html" text type.

**Comment by DenoBeno** [comment]
You were using the full html, but you were using it with editor and the editor wasn't configured to keep these attributes. I have disabled the editor now, don't have time to play with the configuration thereof.

Anyway: whoever uses the "full html" must be knowledgable and trusted...
