### ISSUE TITLE
Csis is sending a lot of mails

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#105]

**Comment by p-a-s-c-a-l** [comment]
Installed the Maillog Module, but apparently it does nothing as mentioned [here]( https://www.drupal.org/project/maillog/issues/1396316). Tried to *disable* it, but that's a feature that seems to be [intentionally broken](https://github.com/clarity-h2020/docker-drupal/issues/106).  So we have to uninstall it unless somebody knows how to make this module work.  I tried to find [Mail Logger](https://www.drupal.org/project/mail_logger) module but this doesn't seem to be available in composer.

**Comment by patrickkaleta** [comment]
> I tried to find [Mail Logger](https://www.drupal.org/project/mail_logger) module but this doesn't seem to be available in composer.

When it comes to contributed modules, one thing Drupal taught me was to always first scroll down to check for which versions this module is available. Turns out the Mail Logger was only developed for Drupal 7. Migrating it to Drupal 8 doesn't seem likely (at least from the look of its info-page).
![modules-availability](https://user-images.githubusercontent.com/42167036/64110396-4e9f0e00-cd82-11e9-97ac-8dc799eaab9c.png)

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/64238280-6ef3d780-cefe-11e9-8f3d-0807649fb83d.png)

**Comment by p-a-s-c-a-l** [comment]
SMTP Module activated itself (?) again. We need to suppress such mails.

**Comment by patrickkaleta** [comment]
> SMTP Module activated itself (?) again. We need to suppress such mails.

A module activating itself would be very strange behavior. It wasn't activated by me or Denis. @fgeyer16 did you maybe (accidentally) activate this module for testing purposes or such?

I will try to completely remove this [SMTP Authentification support module](https://www.drupal.org/project/smtp) from my local instance and check if there are any unwanted side effects.

In addition I [found](https://drupal.stackexchange.com/questions/38255/how-can-i-stop-drupal-from-sending-e-mails-of-any-kind) a couple of ways on how to suppress sending out mails. I think this [one](https://drupal.stackexchange.com/questions/38255/how-can-i-stop-drupal-from-sending-e-mails-of-any-kind#answer-38268) could be a good solution for our case. @fgeyer16 what do you think?

**Comment by p-a-s-c-a-l** [comment]
> A module activating itself would be very strange behavior.

Maybe is was silently activated by Maillog? See https://www.drupal.org/project/maillog/issues/1396316#comment-7934795 Therefore Maillog should be removed, too.

**Comment by patrickkaleta** [comment]
Locally removing SMTP and Maillog modules didn't break my system.

**Procedure:**
1) disabled the modules on the Extend page in the BE (already done on the CSIS)
2) cleared the cache
3) removed the 2 module folders from within the docker container
4) cleared cache again

@fgeyer16 shall I proceed with this on the CSIS server or do you have concerns with this method?

**Comment by fgeyer16** [comment]
> 3. removed the 2 module folders from within the docker container

this should be done by `composer remove drupal/package_name` otherwise the modules will be installed again on next composer update.

Or the lien has to be deleted manually in the composer.json and composer.lock files.

**Comment by fgeyer16** [comment]
> SMTP Module activated itself (?) again. We need to suppress such mails.

I thought I switched it off after I tested something last week, but it seems I did not. Sorry. 
If we remove the smtp-module no mail should go out because, as @p-a-s-c-a-l  already mentioned on other place the docker container does not have any MTA which can send a mail.

**Comment by patrickkaleta** [comment]
> > SMTP Module activated itself (?) again. We need to suppress such mails.
> 
> I thought I switched it off after I tested something last week, but it seems I did not. Sorry.
> If we remove the smtp-module no mail should go out because, as @p-a-s-c-a-l already mentioned on other place the docker container does not have any MTA which can send a mail.

@fgeyer16 I don't think this was your fault. I was just about to finally remove the two modules, when I noticed that the **SMTP module was active again**. Definitely strange behavior, but now those two modules are gone for good :-) 

Also thanks for the hint with the `composer remove` command. We definitely don't want these modules to come back after the next update!

Closing this, because Drupal shouldn't be sending out any mails now.

**Comment by p-a-s-c-a-l** [comment]
Still not resolved. Maybe @Itsman-AT has some news on that.

**Comment by Itsman-AT** [comment]
I am still on it (but I was not in the office last week). I will install Wireshark on the machine (as our IT suggested) and see, if this sheds some light on the issue.

**Comment by Itsman-AT** [comment]
Question: Shall the interfaces be active like this?
@p-a-s-c-a-l @fgeyer16 
![grafik](https://user-images.githubusercontent.com/41750112/68127121-80188f00-ff15-11e9-960b-871fed41f6ac.png)

**Comment by DenoBeno** [comment]
what does this even mean?

**Comment by Itsman-AT** [comment]
I think, we knew this already, but do you know which of our applications uses this mail greeting "Hello [] pleased to meet you"?
@DenoBeno @p-a-s-c-a-l @fgeyer16 

**UPDATE: I now figured, that this is the "normal" mail exchange protocol.**

![grafik](https://user-images.githubusercontent.com/41750112/68139762-fffd2400-ff2a-11e9-9ea0-49e4deb595a7.png)

**Comment by Itsman-AT** [comment]
> 
> 
> what does this even mean?

This is the depiction of all the network interfaces of the machine (Docker runs its services via TCP/IP) and their current traffic.

**Comment by p-a-s-c-a-l** [comment]
Hm, but you cannot identify the source of the SMTP request? Which process is sending the mails? 

[dockerveth](https://github.com/micahculpepper/dockerveth) shows you which docker containers are attached to which `veth` interfaces:

**CONTAINER ID**|**VETH**|**NAMES**
:-----:|:-----:|:-----:
a42a24ff952f|veth5204e59|nginx-web
ccb20795831b|vethba9e0c2|nginx-letsencrypt
aee21efe9287|veth18a799d|nginx-gen
a4b53b42c385|veth6f1f109|ckan-ckan
06d206f02422|veth69bfb4a|ckan-solr
8b2966e8838e|veth80d3b6e|ckan-postgis
02032b899eb8|veth1991740|ckan-redis
34902e9d63f9|vethad68e63|ckan-datapusher
ab0642ee39d4|vethfce1b8d|geoserver-postgis-backups
bf3c7299e7a1|veth2ee76f2|geoserver
68b4177e93d4|vethe306f66|geoserver-postgis
3b8d70db32d6|vethae69c4d|csis-drupal
c0f6cade9118|veth72eb763|csis-postgis
372dc0e7a4ae|veth9e2d1a3|pgadmin4
182521e92b5b|veth29de404|hoster

Container IPs:

`docker ps -q | xargs -n 1 docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} {{ .Name }}' | sed 's/ \// /'`

**Container Name**|**IPv4**
-----|-----
172.19.0.7|nginx-web
172.19.0.5|nginx-letsencrypt
172.19.0.2|nginx-gen
172.19.0.6|ckan-ckan
172.19.0.11|ckan-solr
172.19.0.13|ckan-postgis
172.19.0.4|ckan-redis
172.19.0.14|ckan-datapusher
172.19.0.10|geoserver-postgis-backups
172.19.0.9|geoserver
172.19.0.16|geoserver-postgis
172.19.0.3|csis-drupal
172.19.0.8|csis-postgis
172.19.0.15|pgadmin4
172.19.0.12|hoster

**Comment by p-a-s-c-a-l** [comment]
@DenoBeno @Itsman-AT 
I've identified the problem: Exception Emails sent from CKAN!
Debug mode was turned on. Each request to a non-existent URI is logged and a mail is sent to the admin (info@myclimsteservice.eu). I've turned this off now.

**Comment by Itsman-AT** [comment]
> [dockerveth](https://github.com/micahculpepper/dockerveth) shows you which docker containers a

Ah, thanks, this is the command I was looking for! Great that you identified it, I will check back with the IT for mail activities now.

**Comment by Itsman-AT** [comment]
Looking good, so far:
![grafik](https://user-images.githubusercontent.com/41750112/68208594-c7fcec00-ffd1-11e9-85d1-649985e07593.png)
