### ISSUE TITLE
Deleting a variable caused havoc, please re-install the last backup version.

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#107]
I tried to remove the "field_calculation_type" from the study taxonomy, but this field wasn't cleanly removed and now the site is complaining about various errors. And this in spite of the field not being used - I added it one hour ago, it wasn't used in any views and I and assured that no data is stored in it before attempting to delete it. :-(

E.g. 
https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/study_type/overview

> The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Core\Database\DatabaseExceptionWrapper</em>: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation &quot;taxonomy_term__field_calculation_type&quot; does not exist
> LINE 3: taxonomy_term__field_calculation_type t
>         ^: SELECT t.*
> FROM
> {taxonomy_term__field_calculation_type} t
> WHERE (entity_id IN (:db_condition_placeholder_0, :db_condition_placeholder_1, :db_condition_placeholder_2, :db_condition_placeholder_3, :db_condition_placeholder_4)) AND (deleted = :db_condition_placeholder_5) AND (langcode IN (:db_condition_placeholder_6, :db_condition_placeholder_7, :db_condition_placeholder_8, :db_condition_placeholder_9))
> ORDER BY delta ASC NULLS FIRST; Array
> (
>     [:db_condition_placeholder_0] =&gt; 2217
>     [:db_condition_placeholder_1] =&gt; 10
>     [:db_condition_placeholder_2] =&gt; 9
>     [:db_condition_placeholder_3] =&gt; 1161
>     [:db_condition_placeholder_4] =&gt; 1159
>     [:db_condition_placeholder_5] =&gt; 0
>     [:db_condition_placeholder_6] =&gt; en
>     [:db_condition_placeholder_7] =&gt; de
>     [:db_condition_placeholder_8] =&gt; und
>     [:db_condition_placeholder_9] =&gt; zxx
> )
>  in <em class="placeholder">Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;loadFromDedicatedTables()</em> (line <em class="placeholder">1262</em> of <em class="placeholder">core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php</em>).

I suppose one could manually delete the offending items from the DB, but it's probably too much work. **Please just reset the DB to the last backup version.**

**Comment by p-a-s-c-a-l** [comment]
OK, I'll restored the db from last duplicity backup (today 7:45)

```
/docker/999-duplicity $ docker-compose -f restore.yml up

root@V3LS1809:/docker/999-duplicity/restore/docker/100-csis# cp -rp postgresql_data /docker/100-csis/postgresql_data
```

**Comment by p-a-s-c-a-l** [comment]
For the future, please first try out such "breaking" changes in a local instance of the system (Patrick can help you how to set one up).

**Comment by DenoBeno** [comment]
Thanks. I've posted a bug report on drupal.org, this is really annoying. :-(
