### ISSUE TITLE
Should we add a cron job to clean cache?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#108]
I just had another "BR not working" moment. This is annoying, recurring issue and I have no idea what causes it. However, a workaround is known & simple: _clean the cache_. 

My proposal is to add a cron job that will do this let's say once per hour and leave it that way until further notice. This will not noticeably affect the normal working of the site and we'll have one thing less to worry about at the moment.

WDYT?

**Comment by fgeyer16** [comment]
I think we can try it. But it is "not good practice" in the meaning of Drupal and page speed. Not so important yet in development but maybe somewhen later. When do you encounter this moments? WHen you are workingon some rules or "just sometimes in the wild"?

**Comment by p-a-s-c-a-l** [comment]
Please keep in mind: Drupal runs in a docker container, so you have to execute

```sh
docker exec csis-drupal drush cr
```

**Comment by DenoBeno** [comment]
@fgeyer16 : it's somewhat random. Today, I tried to change a group type and noticed that I didn't get a different set of templates. Then I realised that rule isn't working, cleared the cache and it worked again. I'm pretty much clueless here.

**Comment by DenoBeno** [comment]
Maybe cleaning once per day would be enough. I just don't want this kind of creepy items to persist for days...

**Comment by DenoBeno** [comment]
Has this been implemented/can we close it?

**Comment by DenoBeno** [comment]
I could add this now, but I'm not sure if it's still necessary. Putting it "on hold" until we run in the same problem again.

**Comment by p-a-s-c-a-l** [comment]
Didn't run in the problem again -> can be closed
