### ISSUE TITLE
React Integration in Drupal Page

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#11]
@fgeyer16 idea to be defined "create react field of group entity" = entry point for react applications

**Comment by therter** [comment]
**Integrate a react-app**
The module [React Mount Node](https://www.drupal.org/project/reactjs_mount) is used to add a react app to the drupal system. Therefore the react app will be packed into a js file (e.g. with webpack) and added as a library to a drupal theme. 

**Example to add a library to the bartik theme**
Add the following code to the end of the bartik.libraries.yml file:

```
react-app:
  css:
    component:
     css/leaflet.css: {}
  js:
    js/bundle.js: {}
```

This library can be referenced by the react-mount module. 

![react-mount](https://user-images.githubusercontent.com/1788509/46525192-421ce780-c88b-11e8-85b5-c52862d8b8a1.png)

The react objects can be bound to the window variable and easily invoked from the docker page.


Example:
```javascript
<script type="text/javascript">
  function go(la, ln) {
    //mapComp is the react object
    window.mapComp.setView(la, ln, 8);
  }
</script>
<input onclick="go(48.858093, 2.294694)" style="margin-right: 20px;" type="button" value="Paris" />
<input onclick="go(51.509865, -0.118092)" type="button" value="London" />
```

**Comment by p-a-s-c-a-l** [comment]
If the react apps need to reside in a subfolder of the [csis-theme](https://github.com/clarity-h2020/csis-theme), then we might run in to problems if we want to use dedicated git repositories for our react apps. See also https://github.com/clarity-h2020/docker-drupal/issues/25

**Comment by p-a-s-c-a-l** [comment]
@therter  According to the [React Mount Node](https://www.drupal.org/project/reactjs_mount) documentation, you can place the react app in the libraries folder of the theme or in the general /libraries folder. Please check also the [Best practices for handling external libraries in Drupal 8](https://www.drupal.org/project/documentation/issues/2605130).

**Comment by p-a-s-c-a-l** [comment]
done
