### ISSUE TITLE
Can OpenLayers module be removed?

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#111]
Viewing the Drupal [Status report page](https://csis.myclimateservice.eu/admin/reports/status) it shows the following error:
![openlayers-error](https://user-images.githubusercontent.com/42167036/64614071-f5655900-d3d7-11e9-8765-4cd0f48d31a2.png)

@therter , @p-a-s-c-a-l , @fgeyer16: **Is anyone of you using this module or can it be removed?** Judging by the error message it shouldn't even be doing anything right now, but I'd still like to check with you before.

If I'm not mistaken, this OpenLayers module was installed way back, when we were trying to figure out what (Leaflet or OpenLayers) would be best suitable/supported in Drupal. Disabling and completely removing this module caused no problems on my local machine and should be therefore also safe on the CSIS.

Before disabling the module, I had to remove a couple of [items](https://csis.myclimateservice.eu/admin/structure/openlayers/source/list) related to OpenLayers, which where **(probably?)** installed by the module by default and not created manually by one of us.

**Comment by DenoBeno** [comment]
I'm not sure what my "map" widgets are using. If nothing breaks (e.g. twins views, entering the geo-data in Showcases, little maps that are visualized for data packages and resources...), it's OK with me.

**Comment by therter** [comment]
I don't use this module

**Comment by fgeyer16** [comment]
I installed the module at the beginning, thinking it would be helpful, but never managed to understand how it works.
SO I think nobody is using it

**Comment by p-a-s-c-a-l** [comment]
Yes, it can be remove.

**Comment by patrickkaleta** [comment]
Ok, module has been removed.
