### ISSUE TITLE
/single/import fails on CSIS

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#112]
I have just experienced the following error:

![grafik](https://user-images.githubusercontent.com/2961790/64692946-813dba80-d496-11e9-8a89-ed9adb157390.png)

This is quite interesting, because "single import" is a very robust mechanism that I've used a lot in the past and now it suddenly failed on both csis and DRIVER+ PoS site within a day (still works on pos-dev).

What were the latest updates to the site?

I was able to find only one possible answer to the issue yesterday: https://spradip.wordpress.com/2016/08/02/drupal-8-configuration-management-issues/

@fgeyer16 : Any ideas?

**Comment by DenoBeno** [comment]
OK, this was resolved on pos in the following way: 

- "I've created a .yml file with the configuration you've put here in a comment, and, using drush, have imported just this file configuration. It imported it successfully this way... "

Once this was done, importing over the web gui started working again too.

**Comment by fgeyer16** [comment]
This is interresting that it worked via drush. I experienced this missing standard module error sometimes on other places and clearing cache solved this for me then.

**Comment by patrickkaleta** [comment]
> What were the latest updates to the site?

No module have been updated recently, but one module (Geolocation) has been removed on Monday. However, I cleared the cache afterwards, so I don't think that's the reason for this problem.

**Comment by DenoBeno** [comment]
Well, it works and we know how to handle it the next time...
