### ISSUE TITLE
please install form steps module

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#114]
Related to: https://github.com/clarity-h2020/emikat/issues/16

We need to save the data package before matching the included nodes in the next step. This is what https://www.drupal.org/project/forms_steps is for.

Please install...

**Comment by DenoBeno** [comment]
Unless you prefer to do it differently?

**Comment by DenoBeno** [comment]
form steps module not available on CSIS yet.

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by patrickkaleta** [comment]
Module has been enabled in the BE. Closing this issue.
