### ISSUE TITLE
(Re-)implement "twins" as "View as application" content

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#118]
Related to https://github.com/clarity-h2020/docker-drupal/issues/117

Currently, the "twins" are included in the GL-step as a view field. This is causing problems because the arguments must be listed and these arguments are easy to forget.

More robust way for including the views in the study workflow is to define a "View as application" node and the include this node in the study in the same way as one would include external application. This is already done for [Study Vulnerability functions table](https://csis.myclimateservice.eu/node/1355/edit) and for the [Study adaptation options table](https://csis.myclimateservice.eu/node/1286/edit).

Problem here is that the views that are included "as application" are in different context, so one has to change the arguments for a view to work again.

This is not urgent, rather a "nice to have" once we have time to clean up the CSIS implementation a bit.

**Comment by DenoBeno** [comment]
@patrickkaleta : this is really just "nice to have", leave it as is for now. If/when we start refactoring the CSIS application, this will serve as a reminder.

**Comment by DenoBeno** [comment]
Actually I just did this for the hazards twin because the existing view was causing troubles (see https://github.com/clarity-h2020/csis/issues/107). It's much easier than I thought.

**Comment by p-a-s-c-a-l** [comment]
> If/when we start refactoring the CSIS application

There a no plans to do that.
