### ISSUE TITLE
Define Block Structure of the CSIS 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#12]
@fgeyer16 Define the Block structure of the CSIS on basis of the general mock-up layout
@patrickkaleta Implement the block structure on basis of a child theme of e.g. the Bartik theme

**Comment by p-a-s-c-a-l** [comment]
I moved the respective code to a [separate git repository](https://github.com/clarity-h2020/csis-theme/issues/1).

Ideally, you should develop in your own local git repository and then push to [csis-theme](https://github.com/clarity-h2020/csis-theme). The theme residing in the local docker-drupal git repository on the DEV server can then be updated with:

``
git subtree pull --prefix=drupal-data/web/themes/csis --squash csis-theme master
``

Alternatively (but not recommended ;-), you can modify the module's code directly in the local docker-drupal git repository on the DEV server, commit your changes to the local docker-drupal repository and then update both the remote repositories [csis-theme](https://github.com/clarity-h2020/csis-theme) with:

```
git push
git subtree push --prefix=drupal-data/web/themes/csis --squash csis-theme master
```

**Comment by p-a-s-c-a-l** [comment]
``/drupal-data/web/themes/custom/csis`` is now excluded from [docker-drupal](https://github.com/clarity-h2020/docker-drupal/) repository (see also https://github.com/clarity-h2020/docker-drupal/commit/c995784feb2d489086a380081a95d8f6f5508d91) and is owned by user *docker* which does not have push access to [csis-theme](https://github.com/clarity-h2020/csis-theme/) repository! 

To update the theme you have to su to docker and then issue a git pull. Editing the theme directly in ``/drupal-data/web/themes/custom/csis`` is no longer possible.

**Comment by patrickkaleta** [comment]
I talked to Andrea about possible designs and she said that they already created a draft for a couple of example pages (and that they could also do the same for all the other pages) which can be found on ownCloud: 

https://repository.atosresearch.eu/owncloud/index.php/apps/files/?dir=%2FCLARITY%2FWP6%20Dissemination%20and%20Community%20Building%2FT6.2%20Media%20Production%20and%20Publishing%2FCSIS%20styles

IMHO those design drafts are better suited then our current mockups for styling the website.

**Comment by p-a-s-c-a-l** [comment]
I agree, this looks much better. But who would be responsible for creating the CSS, adapting the current bootstrap theme, etc.? See also https://github.com/clarity-h2020/csis-theme/issues/5
