### ISSUE TITLE
Form steps not working as expected

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#120]
related to: https://github.com/clarity-h2020/docker-drupal/issues/114

I have configured a "form steps" workflow for adding data packages and discovered that it doesn't work as it should.  

See: https://www.drupal.org/project/forms_steps/issues/3084693

e.g., "next" should bring me from https://csis.myclimateservice.eu/data_package/context/932b8771-a650-4529-9b15-c0f4f1212918 to https://csis.myclimateservice.eu/data_package/step2/932b8771-a650-4529-9b15-c0f4f1212918 but I end up on https://csis.myclimateservice.eu/data_package/step2 instead

Any ideas?

**Comment by DenoBeno** [comment]
We are using form steps in three sites outside this one, including the marketplace - it always works except here. Florian tried to find out why, but this has led nowhere.

Postponed until some better time.

**Comment by p-a-s-c-a-l** [comment]
Is this till relevant or can we close the issue?

**Comment by patrickkaleta** [comment]
Duplicate of #136
