### ISSUE TITLE
Extend Cities Taxonomy

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#121]
See https://github.com/clarity-h2020/emikat/issues/25#issuecomment-542059508

As mentioned in the issue above, ATM we just re-import cities where heat wave LE calculation is possible. Still open is the question about [solar radiation](https://github.com/clarity-h2020/emikat/issues/25#issuecomment-541752288) and [mortality rates](https://github.com/clarity-h2020/emikat/issues/26).

**Comment by therter** [comment]
> ATM we just re-import cities where heat wave LE calculation is possible

The cities with  heat_wave = true are reimported

**Comment by DenoBeno** [comment]
nice

**Comment by p-a-s-c-a-l** [comment]
done
