### ISSUE TITLE
Revise Adaptation options data model

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#122]
We need to revise the current data model implementation and check if all views & Entity browsers actually use the right configuration to display, search and filter through all available Adaptation options.

**Comment by p-a-s-c-a-l** [comment]
Is this still required / feasible to achieve in the remaining time? Does it provide real added value ? If not, please close.

**Comment by patrickkaleta** [comment]
Heinrich, Mauro and me are currently discussing how to implement the Cost-Benefit analysis (baseline scenario vs. scenario with an adaptation option chosen). Not sure, how much of that will/can be implemented, but I'm expecting some decisions within the next 1-2 weeks.

**Comment by patrickkaleta** [comment]
Closing in favor of [this issue](https://github.com/clarity-h2020/csis/issues/155).
