### ISSUE TITLE
Clean up the System

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#125]
Before we are going live, we have to clean up the system and remove test studies, orphan resources, test data packages, etc. I wonder if this is easily possible, e.g. remove a study and **all** associated steps? Anyway, this is something that can only be addressed after https://github.com/clarity-h2020/csis/issues/113 has been resolved. 

Perhaps we could also start with an "empty" production system and *import* only the stuff we need, like taxonomies, step templates, ... ?

**Comment by fgeyer16** [comment]
I think 
this depends how many test content is in the system. Hunting down dependencies for import in an empty system can be as many work as hundting down the existing content and delete it.

**Comment by DenoBeno** [comment]
I would prefer to start without any studies in the operative system. And with only a few template steps.

For the rest, I'm not sure. I suppose that we will need all the taxonomy terms, but how about resources and data packages?

The data used by the twins should probably be moved to the marketplace, with CSIS fetching a copy of this data in nightly syncing?  Other?

**Comment by p-a-s-c-a-l** [comment]
>  Hunting down dependencies for import in an empty system can be as many work as hundting down the existing content and delete it.

O.K. then. I've copied the complete database to the new PROD and DEV systems since, there seems no simple way to initialise a clean system from scratch.

**Comment by p-a-s-c-a-l** [comment]
If there is no easy way to clean up the system, we have at least to unpublish all content (test studies, test data packages, test resources, outdated solution offers, etc.) that should not be visible to end users in the public system. Also related to https://github.com/clarity-h2020/csis/issues/130

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta @fgeyer16 

I'm logged in as 'ordinary' user ([p-a-s-c-a-l](https://csis.myclimateservice.eu/user/183)) in public CSIS, why can I see all those studies even tough I'm not a member of the study groups?

![grafik](https://user-images.githubusercontent.com/1788226/83844283-fb8a2b00-a706-11ea-86dd-1cbc39c71b0d.png)

**Comment by patrickkaleta** [comment]
> @patrickkaleta @fgeyer16
> 
> I'm logged in as 'ordinary' user ([p-a-s-c-a-l](https://csis.myclimateservice.eu/user/183)) in public CSIS, why can I see all those studies even tough I'm not a member of the study groups?

Since you're a logged-in user, you get to see all Studies, that have been set to `public` by the Study owners. Only anonymous users cannot see those Studies. They can only see those Studies that have been explicitly whitelisted in the [csis-helpers module settings.](https://csis.myclimateservice.eu/admin/config/csis_helpers/default)

**Comment by p-a-s-c-a-l** [comment]
O.K. thanks, So I'm going to unpublish the tests studies.
