### ISSUE TITLE
Composer updated failed (out-of-memory)

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#126]
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by p-a-s-c-a-l** [comment]
`php -r "echo ini_get('memory_limit').PHP_EOL;"` shows **64MB** while [Drupal Status Report](https://csis.myclimateservice.eu/admin/reports/status) shows **1GB** ?!

**Comment by p-a-s-c-a-l** [comment]
Solution: add `ENV COMPOSER_MEMORY_LIMIT=-1` to [Dockerfile](https://github.com/clarity-h2020/docker-drupal/blob/dev/drupal/Dockerfile).

**Comment by DenoBeno** [comment]
This is a common issue - Drupal with plenty of modules eats a lot of memory.
