### ISSUE TITLE
Include city codes in our City/Region taxonomy

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#128]
Our [city/region taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview) so far only stores the Country it belongs to and the EEA city profile name (which btw is missing in 5-10% of our cities -> @humerh or @therter could this cause any troubles for Emikat our our map/table components?).

We noticed some issues with the calculations in Emikat, which are partly caused by mismatches between City labels (explained [here](https://github.com/clarity-h2020/emikat/issues/29#issuecomment-553431127) by Heinrich). One solution would be to include city codes in Drupal, so that Emikat can then do the matching based on those city codes.

**To do:**
@humerh & @negroscuro can you agree on a definition for those city codes, which @negroscuro then makes available, so that @therter can update the Cities/Regions in Drupal using his script. I will then take care of passing these city codes along to Emikat everytime it gets triggered by CSIS.

**Comment by negroscuro** [comment]
@Heinrich, as we discused already for mortality importing in Atos database, indeed you explained to me, how this codes work, so, what about to remove last 2 digits/letters from a city code which corresponds to city outskirts? so I can provide such fixed city codes for CSIS to import. Is this ok? 

![image](https://user-images.githubusercontent.com/6427900/69048541-034de080-09fe-11ea-8c23-4a7fe714c141.png)

I just implemented it but just to be sure I would like confirmation from your side.

@therter now mortality layer is providing such reduced city code as well as boundary fo every available city.

**Comment by patrickkaleta** [comment]
I already added a [City code field](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/cities_regions/overview/fields) to our Cities/Region taxonomy (machine name: `field_city_code`), so that we can store the codes in Drupal. I will now prepare the CSIS helpers module to be able to work with this new field.

**Comment by therter** [comment]
I have reimported the cities taxonomy with the data from the mortality layer. The field City code is filled, now.

**Comment by patrickkaleta** [comment]
Ok, from now on the city code is being sent to Emikat with each new Study or Study update, so @humerh you can now do your matching based on the city codes instead of the city names.
![parameters-in-emikat](https://user-images.githubusercontent.com/42167036/69324824-726b4500-0c49-11ea-8402-0cb6fefe52d4.png)

FYI: I've also added the city code to our `$studyInfo` JSON object, just in case that our components should ever need it as well.

Closing this issue, since from Drupal-side everything is done now.
