### ISSUE TITLE
Could not delete web/modules/contrib/group/PATCHES.txt

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#132]
`composer update` fails with:

`- Updating drupal/group (1.0.0-rc4 => 1.0.0-rc5):     Update failed (Could not delete web/modules/contrib/group/PATCHES.txt: )`

No sure if this is related to the patches in `/docker/100-csis/drupal-data/patches`. Probably it's just a permission problem.

Anyway, I recommend to check `composer.patches.json`whether those patches are still needed for the installed versions of the respective modules.

**Comment by patrickkaleta** [comment]
**Solved.**
I ran `composer update drupal/group`, which updated that specific module without any problems. But for whatever reasons this also caused some other unrelated modules to be downgraded.

Running `composer update` afterwards reverted those downgrades and also updated all other remaining outdated modules.

> No sure if this is related to the patches in `/docker/100-csis/drupal-data/patches`. Probably it's just a permission problem.
> 
Yes, this file is related to it, but it's always being generated automatically so I don't know why it was suddenly causing problems.

> Anyway, I recommend to check `composer.patches.json`whether those patches are still needed for the installed versions of the respective modules.

Yes, currently two patches are applied and both are still needed.
