### ISSUE TITLE
"Setting the value of 'Drupal.toolbar.subtrees.clarity' exceeded the quota." error

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#133]
This is what I saw on https://csis.myclimateservice.eu/study/37/step/1642/view/external:
 
![image](https://user-images.githubusercontent.com/2961790/68200148-9549f800-ffbf-11e9-8642-bd7795ffd6d1.png)

Not sure what's causing it, but apparently we are trying to put more data in the Chrome storage than allowed (25MB limit per default, allegedly)

Here is a thread on stackflow explaining how to handle this error:
- https://stackoverflow.com/questions/23977690/local-storage-in-chrome

**Comment by p-a-s-c-a-l** [comment]
Closing since the problem didn't appear again.
