### ISSUE TITLE
Error when adding new scenario in study context

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#139]
I've added a new scenario by editing the [study context](https://csis.myclimateservice.eu/study/54/view/context):

![grafik](https://user-images.githubusercontent.com/1788226/75023755-9fbdce00-5498-11ea-9428-adfc173e1e14.png)

The following error occurred:
>    Warning: assert(): Cannot load a NULL ID. failed in Drupal\Core\Entity\EntityStorageBase->load() (line 249 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).
    Warning: array_flip(): Can only flip STRING and INTEGER values! in Drupal\Core\Entity\EntityStorageBase->loadMultiple() (line 266 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).

Event Log:
- [2435166](https://csis.myclimateservice.eu/admin/reports/dblog/event/2435162)
- [2435163](https://csis.myclimateservice.eu/admin/reports/dblog/event/2435163)

**Comment by patrickkaleta** [comment]
Strange. Denis experienced the [same](https://github.com/clarity-h2020/csis/issues/136). I though I found the problem and fixed that. Need to look into that again...

**Comment by NICDDB** [comment]
Me too i've this problem. And also the calculation does not start

<img width="762" alt="Schermata 2020-04-30 alle 15 27 53" src="https://user-images.githubusercontent.com/60875355/80715843-38a34200-8af7-11ea-9e5e-daa2dc1e135b.png">
<img width="1409" alt="Schermata 2020-04-30 alle 15 28 05" src="https://user-images.githubusercontent.com/60875355/80715846-3b059c00-8af7-11ea-92ab-493c743aab6b.png">

**Comment by patrickkaleta** [comment]
> And also the calculation does not start

The calculations needs to be triggered manually by clicking on the button on the bottom right side of the screenshot. Study scenarios are not used for the calculation trigger, so it should not be related to this issue.

Still investigating why this error messages sometimes pops up and sometimes not. @NICDDB  What Study exactly is this?

**Comment by NICDDB** [comment]
> The calculations needs to be triggered manually by clicking on the button on the bottom right side of the screenshot. Study scenarios are not used for the calculation trigger, so it should not be related to this issue.

Yes i know this, but i don't have a feedback that say me if the calculation start or not. Anyway after clicking the button "start calculation" i check in the hazard characterization - local effect / table and i don't have results.

> What Study exactly is this?

I'm working on two study
The first is a my study called - Napoli validation study -, that have a olds results in the table.
The second is my study called - Napoli validation check -, that not have nothing results in the table.

**Comment by patrickkaleta** [comment]
Sorry, I believe there was an issue with your permissions. Once you click the button, an info-windows should pop up and ask for your confirmation to trigger the calculations:
![trigger-permissions](https://user-images.githubusercontent.com/42167036/80957502-85db2880-8e03-11ea-940c-272b17ff2c58.png)

Only after you confirm that, the calculation is actually triggered.
 
For the Study "Napoli validation study", I already triggered the calculation. The Study " Napoli validation check" has never been calculated, so that's why no results where shown. Please try to trigger it yourself once the other calculation is completed and let me know if the problem still persists.

**Comment by NICDDB** [comment]
This info-windows has never been until now.
Anyway now the calculation work.
Thanks you @patrickkaleta!
