### ISSUE TITLE
SingleSignOn fails on users

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#140]
Users are not able to log in via CAS.

**Comment by fgeyer16** [comment]
This issue seems to be caused by users loosing CAS permission..
@p-a-s-c-a-l  your user had no "Allow user to log in via CAS" set. So SSO was disabled. I set this in your profile again.

Can you please check if SSO now works for you?

**Comment by p-a-s-c-a-l** [comment]
> Can you please check if SSO now works for you?

Now, it's working, thanks!
