### ISSUE TITLE
Error when saving study context

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#142]
When editing and trying to save the study context at https://csis.myclimateservice.eu/group/109/edit/context?destination=/study/109/view/context, the following error occurred:

![grafik](https://user-images.githubusercontent.com/1788226/75158731-0d772d80-5717-11ea-9c8a-2de32eb08b63.png)

> The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Drupal\Core\Database\DatabaseExceptionWrapper</em>: Exception in Cities to Countries mapping[cities_to_countries_mapping]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: &quot;_none&quot;
LINE 5: ...omy_term__field_country.field_country_target_id = &#039;_none&#039;)) ...
                                                             ^: SELECT taxonomy_term_field_data.langcode AS taxonomy_term_field_data_langcode, taxonomy_term_field_data.name AS taxonomy_term_field_data_name, taxonomy_term_field_data.tid AS tid
FROM
{taxonomy_term_field_data} taxonomy_term_field_data
LEFT JOIN {taxonomy_term__field_country} taxonomy_term__field_country ON taxonomy_term_field_data.tid = taxonomy_term__field_country.entity_id AND taxonomy_term__field_country.deleted = :views_join_condition_0
WHERE ((taxonomy_term__field_country.field_country_target_id = :taxonomy_term__field_country_field_country_target_id)) AND ((taxonomy_term_field_data.status = :db_condition_placeholder_1) AND (taxonomy_term_field_data.vid IN (:db_condition_placeholder_2)))
ORDER BY taxonomy_term_field_data_name ASC NULLS FIRST; Array
(
    [:taxonomy_term__field_country_field_country_target_id] =&gt; _none
    [:db_condition_placeholder_1] =&gt; 1
    [:db_condition_placeholder_2] =&gt; cities_regions
    [:views_join_condition_0] =&gt; 0
)
 in <em class="placeholder">Drupal\views\Plugin\views\query\Sql-&gt;execute()</em> (line <em class="placeholder">1543</em> of <em class="placeholder">core/modules/views/src/Plugin/views/query/Sql.php</em>).

Probably, because no country was selected. If this field is required, the form validation should be implemented or the save button should be disabled or at least the system should not crash.

**Comment by patrickkaleta** [comment]
> Probably, because no country was selected. If this field is required, the form validation should be implemented or the save button should be disabled or at least the system should not crash.

Definitely the cause of this problem. Seems like we're having another issue with [Dependent Fields](https://www.drupal.org/docs/8/modules/business-rules/advanced-usage/dependent-field). [Bug ](https://www.drupal.org/project/business_rules/issues/3079452) was already reported, but so far no fix available. To me it seems like Dependent Fields are bypassing the default validation checks (or at least executed before them). For our other required fields (e.g. title or study goal) validation is triggered properly.

As a temporary fix, I will just set the first country in the list as the default placeholder. When I find the time I'll check if there is a way for us to handle the validation inside our csis-helpers module.

**Comment by p-a-s-c-a-l** [comment]
> As a temporary fix, I will just set the first country in the list as the default placeholder.

I think we can live with that as a permanent fix. :-)
