### ISSUE TITLE
Reliable Country Selection

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#145]
Coming back to country selection, there are two usability issues:

![grafik](https://user-images.githubusercontent.com/1788226/75223947-d4d36480-57a7-11ea-9c84-5a9c95729d64.png)

The first, more serious one is related to the [recalculation of HC-LE input layers](https://github.com/clarity-h2020/emikat/issues/32): The city selection box must contain cities only, that are guaranteed to be available (recalculated) for screening. So we have to periodically re-generate the cities taxonomy as @therter described [here](https://github.com/clarity-h2020/docker-drupal/issues/68#issuecomment-523336896). I wonder, if there is a possibility to a) automate or b) simplify this process? If we could unpublish or hide some taxonomy terms, then it would still be a manual task to update the list of cities as new cities are becoming available, but it's still more efficient than doing the complete import process again and again.

The second issue is not that critical (showstopper) but it could still become frustrating for users:  There are many *countries* without supported cities, so they shouldn't be shown at all in the countries selection box for **Automated Screening: Urban Infrastructure** studies.

_Originally posted by @p-a-s-c-a-l in https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-590727856_

**Comment by therter** [comment]
> The first, more serious one is related to the [recalculation of HC-LE input layers](https://github.com/clarity-h2020/emikat/issues/32): The city selection box must contain cities only, that are guaranteed to be available (recalculated) for screening. So we have to periodically re-generate the cities taxonomy as @therter described [here](https://github.com/clarity-h2020/docker-drupal/issues/68#issuecomment-523336896). I wonder, if there is a possibility to a) automate or b) simplify this process? If we could unpublish or hide some taxonomy terms, then it would still be a manual task to update the list of cities as new cities are becoming available, but it's still more efficient than doing the complete import process again and again.

This can be solved by a script that I have created. See [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301). 
But I have seen that the structure of the [city shape file](http://services.clarity-h2020.eu:8080/geoserver/clarity/wfs?request=GetFeature&typeNames=clarity:city&outputFormat=SHAPE-ZIP) that is updated by @negroscuro, when new cities become available,  has changed. So I must adjust the function that publish/unpublish the cities.


But this approach does not work for the countries. Because the countries will still be shown in the country combo box, when I unpublish them via the db.

**Comment by p-a-s-c-a-l** [comment]
> This can be solved by a script that I have created. See [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301).

Yes, but currently it's not automated. ATM city data is [being regenerated](https://github.com/clarity-h2020/emikat/issues/33#issuecomment-603783702), so the list of cities has to be updated regularly.

**Comment by p-a-s-c-a-l** [comment]
Any updates?
Perhaps this can be combined with [synchronisation](https://github.com/clarity-h2020/csis/issues/135)? @patrickkaleta 

How is synchronisation triggered? Manually or by a cron-job? In any case we could include @therter's `republish.sh` in the process so that the cities taxonomy is updated in DEV right before the synchronisation starts and then the updated taxonomies are synchronised to PROD. WDYT?

BTW, the [scripts](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301) should be made available in [this](https://github.com/clarity-h2020/docker-drupal/) GitHub repo under /scripts.

**Comment by therter** [comment]
> BTW, the [scripts](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301) should be made available in [this](https://github.com/clarity-h2020/docker-drupal/) GitHub repo under /scripts.

I have added the script to the repo

**Comment by patrickkaleta** [comment]
> @therter  wrote:
> But this approach (_hiding empty countries by unpublishing them_) does not work for the countries. Because the countries will still be shown in the country combo box, when I unpublish them via the db.

I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain. 

Tested it locally and it even worked fine together with the Business Rule function that handles the automated selection of cities/regions for the selected country.

The necessary View is already available in the CSIS, so if @therter can provide such a publish/unpublish script for countries, we can use this approach to get a more reliable country selection.

**Comment by patrickkaleta** [comment]
> How is synchronisation triggered? Manually or by a cron-job? In any case we could include @therter's `republish.sh` in the process so that the cities taxonomy is updated in DEV right before the synchronisation starts and then the updated taxonomies are synchronised to PROD. WDYT?

For now, it's set to be triggered manually by running the pull_content.sh script in the target docker environment, which runs the individual `drush migrate` commands in the necessary order. 

If configurations have changed (field & content type settings, Views, etc.), it's necessary to first synchronize the configuration, for which in turn it might be first necessary to run a composer update (in case new modules are used), so ideally during this whole process the site is put into "maintenance mode". All that considered I'm not a big fan of having a cron-job take care of this process.
However, it would be possible to only synchronize certain content types (like countries and cities/regions) by running the individual `drush migrate` commands for those taxonomies. @therter's republish script could be run in DEV before this "slimmed down" version of the content synchronization more frequently than the usual content synchronization.

> BTW, the [scripts](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301) should be made available in [this](https://github.com/clarity-h2020/docker-drupal/) GitHub repo under /scripts.

I will put the mentioned script for the content synchronization in there as well.

**Comment by therter** [comment]
> The necessary View is already available in the CSIS, so if @therter can provide such a publish/unpublish script for countries, we can use this approach to get a more reliable country selection.

I have added the code for publishing/unpublishing countries to the function that publish/unpublish the cities. See [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-595716301)

**Comment by therter** [comment]
> I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain.

@patrickkaleta I have unpublished the country 'Andorra', but it is still shown in the combobox.


![Auswahl_156](https://user-images.githubusercontent.com/1788509/80104133-9cb58b80-8576-11ea-90c6-7578ba1f37ed.png)

**Comment by therter** [comment]
> I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain.

@patrickkaleta I have unpublished the country 'Andorra', but it is still shown in the combobox.


![Auswahl_156](https://user-images.githubusercontent.com/1788509/80104133-9cb58b80-8576-11ea-90c6-7578ba1f37ed.png)

**Comment by therter** [comment]
> I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain.

@patrickkaleta I have unpublished the country 'Andorra', but it is still shown in the combobox.


![Auswahl_156](https://user-images.githubusercontent.com/1788509/80104133-9cb58b80-8576-11ea-90c6-7578ba1f37ed.png)

**Comment by therter** [comment]
> I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain.

@patrickkaleta I have unpublished the country 'Andorra', but it is still shown in the combobox.


![Auswahl_156](https://user-images.githubusercontent.com/1788509/80104133-9cb58b80-8576-11ea-90c6-7578ba1f37ed.png)

**Comment by patrickkaleta** [comment]
> > I believe I found a possible solution for that problem. Instead of showing the overall taxonomy list for countries in the [Study country field](https://csis.myclimateservice.eu/admin/group/types/manage/study/fields/group.study.field_country), I can place a View inbetween, which filters out unpublished countries. The result would be that only published Countries (for which available Cities exist) would remain.
> 
> @patrickkaleta I have unpublished the country 'Andorra', but it is still shown in the combobox.

@therter  Sorry, for the misunderstanding. I prepared the necessary View but didn't switch to it until getting feedback. Now this new mechanism is active and in the Country selection box I can see roughly 30 countries.

In the "Maintenance" overviews I've added a [list of the Countries](https://csis.myclimateservice.eu/maintenance/countries), so it's possible to view & change the status of the published/unpublished countries manually.

**Comment by p-a-s-c-a-l** [comment]
Thanks! So this can be considered as done.
