### ISSUE TITLE
Google Maps API Key expired 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#146]
Now we ran into the avoidable problem described [here](https://github.com/clarity-h2020/docker-drupal/issues/55#issuecomment-574129603) and [here](https://github.com/clarity-h2020/csis/issues/113#issuecomment-574177688):

> You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

This affects the "Twins" Maps and the Spatial Coverage Maps in Data Packages and Resources. I assume it's not easily possible to replace those maps by something like leaflet or OpenLayers?

**Comment by p-a-s-c-a-l** [comment]
Any news about that?

**Comment by p-a-s-c-a-l** [comment]
@DenoBeno we cannot make a [BETA release of CSIS](https://github.com/clarity-h2020/csis/issues/145#issue-567632298) before this has been resolved: there will be no Twins Google Maps. Alternative, we can remove / unpublish all Twin Tabs from study templates as proposed [here](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-591344047) in PROD instance and re-enable them again when this issue has been resolved. I any case, we can't wait any longer if we want to proceed with the release as planned.

**Comment by p-a-s-c-a-l** [comment]
Any updates on the status?

**Comment by patrickkaleta** [comment]
**Google Maps API Key is no longer required.** We've now switched to the Drupal 8 [Leaflet](https://www.drupal.org/project/leaflet) module, which should offer all the features we were using in the [Geofield Map](https://www.drupal.org/project/geofield_map) module.

**AFAIK** we only used Google Maps for the Twins and the Showcases. In both cases I've adapted the corresponding View to use the new Leaflet module. No changes to the Drupal Data model were necessary.
