### ISSUE TITLE
Update Drupal Core and modules

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#148]
I found a [blog post](https://blog.42mate.com/update-drupal-core-from-8-7-to-8-8-with-composer/) describing step-by-step how to upgrate to current 8.8 version of Drupal. I tested this locally and upgrade worked as supposed. In addition, I then also updated the remaining modules and fixed/removed our list of appended patches. All went well and CSIS seems to be running stable without any side-effects (I will further test the CSIS today). I suppose we can do the upgrade tomorrow.

### Instructions
1) upgrade Core to 8.8 as described in [blog post](https://blog.42mate.com/update-drupal-core-from-8-7-to-8-8-with-composer/) (step 1 can be skipped, step 3 should be executed completely)
2) **DONE** update the `composer.patches.json` file:
 a) remove the other_view_filter patch (this patch is already included in the new module version)
 b) switch to the re-created Business Rules patch for issue 3043752
3) update remaining modules with:
 a) composer update
 b) drush updb
 c) drush cr

Check the [Status report](https://csis.myclimateservice.eu/admin/reports/status) to see if any problems remain.

**Comment by patrickkaleta** [comment]
Done! Drupal is now running current 8.8.5 version and all modules are up-to-date.

**Comment by p-a-s-c-a-l** [comment]
Please upgrade to 8.9.1 @fgeyer16

**Comment by p-a-s-c-a-l** [comment]
```sh
composer outdated "drupal/*"
```

> drupal/better_exposed_filters 3.0.0-alpha6 5.0.0-beta1 Provides advanced options (such as links, checkboxes, or jQueryUI widgets) for exposed Views ele...
drupal/core                   8.9.2        9.0.2       Drupal is an open source content management platform powering millions of websites and applicati...
drupal/core-dev               8.9.2        9.0.2       require-dev dependencies from drupal/drupal; use in addition to drupal/core-recommended to run t...
drupal/devel                  1.2.0        4.0.0       Various blocks, pages, and functions for developers.
drupal/devel_entity_updates   1.0.0        3.0.0       Provides developers an API and drush command to perform automatic entity updates.
drupal/imce                   1.8.0        2.2.0       Provides a file manager supporting personal folders.
drupal/migrate_plus           4.2.0        5.1.0       Enhancements to core migration support.
drupal/migrate_tools          4.5.0        5.0.0       Tools to assist in developing and running migrations.
drupal/permissions_by_term    2.25.0       3.1.0       Restricts access to nodes by taxonomy terms in relation to users and their roles.


```sh
composer update drupal/core --with-dependencies

```

> Dependency "twig/twig" is also a root requirement, but is not explicitly allowed. Ignoring.
Dependency "symfony/debug" is also a root requirement, but is not explicitly allowed. Ignoring.
Dependency "symfony/debug" is also a root requirement, but is not explicitly allowed. Ignoring.

**Comment by p-a-s-c-a-l** [comment]
![image](https://user-images.githubusercontent.com/1788226/87022798-494af500-c1d7-11ea-9b5d-e866e4316d4d.png)

> Upgrading from 8.x-3.x to 8.x-4.x
We have tried to provide an easy upgrade path from version 3 to version 4. Running the update hooks will try and update your views BEF configuration to be compatible with version 4. After the updates you should clear the caches, or it will result in a fatal error.

> PLEASE RUN THIS ON A LOCAL/TEST ENVIRONMENT FIRST.

> Note: We will no longer commit any new code against the 8.x-3.x version. Feature requests should be made against the 8.x-4.x version.

I'm not going to touch this module. The lasted v3 release is [8.x-3.0-alpha6](https://www.drupal.org/project/better_exposed_filters/releases).

**Comment by p-a-s-c-a-l** [comment]
let's assume this is done now

**Comment by fgeyer16** [comment]
reopening due to better exposed Filters
> I'm not going to touch this module. The lasted v3 release is 8.x-3.0-alpha6.

Somehow I missed that module when I tested yesterday. I tried to update it locally.

changed the line in composer.json to "drupal/better_exposed_filters": "^4.0"

1. composer update
2. vendor/bin/drush/updb
3. vendor/bin/drush/cr

after that the showcase page delivered a WSOD. 
Disabling better exposed filters at /admin/structure/views/view/showcase_overview_geofield/edit/default, reenabling it and restore the settings fixed the WSOD

shall I proceed with that on csis-dev?

**Comment by p-a-s-c-a-l** [comment]
> shall I proceed with that on csis-dev?

yes, please give it try :-)
CSIS is not usable anyway due to https://github.com/clarity-h2020/emikat/issues/45

**Comment by fgeyer16** [comment]
Better exposed Filter is now on 4.0-beta2 and green in the update overview.on csis-dev. Procedure: 

1. Set exposed form style to basic at /admin/structure/views/view/showcase_overview_geofield/edit/default (note settings somewhere before)
2. remove the section drupal/better_exposed_filters from composer.pathces.json
3. change the line in composer.json to "drupal/better_exposed_filters": "^4.0"
4. composer update
5. vendor/bin/drush/updb
6. vendor/bin/drush/cr
7. Set exposed form style to Better exposed Filter again at /admin/structure/views/view/showcase_overview_geofield/edit/default and reapply the settings

Best practice to update PROD: 

1. push to git (I do not have/find my credentials for ATOS' gitlab)
2. Pull from git at Prod
3. Set exposed form style to basic at /admin/structure/views/view/showcase_overview_geofield/edit/default (note settings somewhere before)
4. composer install
5. vendor/bin/drush/updb
6. vendor/bin/drush/cr
7. Set exposed form style to Better exposed Filter again at

**Comment by p-a-s-c-a-l** [comment]
done
