### ISSUE TITLE
Accessing private Git repository via new servers not possible

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#150]
After changing the remote origin to our new private Git repository, I'm still unable to push/pull from the DEV server.

I've added a SSH key [as described](https://scm.atosresearch.eu/help/ssh/README#generating-a-new-ssh-key-pair), but trying to push commits to the repo returns the following error now:
```
ssh: connect to host scm.atosresearch.eu port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Trying to check whether the SSH key was added successfully (as mentioned in the description) with `ssh -T git@https://scm.atosresearch.eu/` also returns the "Connection timed out" error. @maesbri could you please check with your IT department, what might be the issue now?

**Comment by patrickkaleta** [comment]
I tested connecting to the repository with my own machine and our old CSIS-server (to rule out the DEV and PROD servers as the source of error), however the connection still fails due to a time out. @maesbri, @DanielRodera any news from you IT department on what could be the problem here?

**Comment by DanielRodera** [comment]
Hi @patrickkaleta,

I am afraid you cannot make the push by ssh, 

Our company´s policy regarding the security doesn't allow external connections (using ssh)

Did you try making a push using https instead of ssh??

**Comment by patrickkaleta** [comment]
> Did you try making a push using https instead of ssh??

Thank you @DanielRodera. ssh seems to be indeed forbidden. Push/pull is possible via https. I've changed the remote origins in both our servers, so that they now use https instead.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta I've noticed that the last commit in [clarity-csis-drupal](https://gitlab.atosresearch.eu/ari/clarity-csis-drupal) is from 6 months ago. Now did you or didn't you use the git repo to import / export configuration between DEV and PROD as described [here](https://github.com/clarity-h2020/docker-drupal/issues/138)?

**Comment by p-a-s-c-a-l** [comment]
Ah, o.k. I had a look at the old **gitlab**.atosresearch.eu. I wonder why this is still online?

I've added warning to the old repository that it's deprecated and has moved to **scm**.atosresearch.eu.
