### ISSUE TITLE
Edit context usability issue

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#153]
https://csis.myclimateservice.eu/study/166/view/context
19.06.2020, 11:15, 
![grafik](https://user-images.githubusercontent.com/45260352/85116875-3ff4eb00-b21e-11ea-9ec7-458fbe5bc892.png)

Not sure if the users understands that he has to edit things here (edit button) in order to go further. It might be helpfull to rename the button maybe to "please enter more information here" or "please select your city here", or anything like that

_Originally posted by @claudiahahn in https://github.com/clarity-h2020/csis-technical-validation/issues/53#issuecomment-646530767_

**Comment by p-a-s-c-a-l** [comment]
@claudiahahn is right, it's not clear for the user that he/she **must** edit the study context in order to make further progress in the workflow.

Very quick first fix would be to simply rename the button to something like *"Please enter more details to proceed with your study"*.

Next we could just change the name of the button when **required** context information is missing, or we show a warning message next to the button. The message disappears once all required information for the calculation has been provided.

Next, we could automatically open the "edit context box" when user visits the context tab
a) for the first time, and/or
b) as long as **required** context information is missing

**Comment by patrickkaleta** [comment]
> @claudiahahn is right, it's not clear for the user that he/she **must** edit the study context in order to make further progress in the workflow.
> 
> Very quick first fix would be to simply rename the button to something like _"Please enter more details to proceed with your study"_.
> 
> Next we could just change the name of the button when **required** context information is missing, or we show a warning message next to the button. The message disappears once all required information for the calculation has been provided.
> 
> Next, we could automatically open the "edit context box" when user visits the context tab
> a) for the first time, and/or
> b) as long as **required** context information is missing

One complication is that this button is generated for all of our Study types, which have different requirements (e.g. Transport Infrastructure Studies don't require a City at all). So, we would have to handle every Study type separately.

**Therefore as a first fix, I did the following on DEV (see [here](https://csis-dev.myclimateservice.eu/study/60/view/intro) for example):** 
- moved the edit button to the top of the page and renamed it to "Edit Study context"
- the Study checklist in the sidebar now not only warns the users of a missing City, but also informs them that they have to go to the Study context and change it there 
![study-context](https://user-images.githubusercontent.com/42167036/85850987-26b7e580-b7ae-11ea-888d-c880006e465d.png)


The Study checklist in the sidebar is already configured to only work for this specific Study type, therefore we don't need to additionally take care of that anywhere else.

**Comment by p-a-s-c-a-l** [comment]
Thanks. That should be enough for now.

**Comment by claudiahahn** [comment]
Thank you!
