### ISSUE TITLE
Setup Single-Sign-On

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#16]
Setup CAS (Central Authentication Service) with CLARITY Marketplace, EMIKAT, GeoServer, etc.

**Comment by therter** [comment]
@florian @humerh Is there a good way to use Single-Sign-On for the emikat server.

**Comment by p-a-s-c-a-l** [comment]
@therter @fgeyer16 
`/jsonapi/user/user` returns an array of all users, but I'm only interested in the current user.  According to this [change record](https://www.drupal.org/node/2984034), you could [filter](https://www.drupal.org/docs/8/modules/jsonapi/filtering) the current user by `meta.links.me`. Is this really the way to go or is there any simpler method?

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 Is this a duplicate of https://github.com/clarity-h2020/marketplace/issues/10?

**Comment by p-a-s-c-a-l** [comment]
ATM credentials for EMIKAT and other services are part of the user profile. That means, when a new user registers, we have to copy the credentials. Is this really the way to go?! Furthermore, aren't the profiles now managed on profiles.myclimateservice.eu?

**Comment by DenoBeno** [comment]
Is the SSO working now?

**Comment by DenoBeno** [comment]
I can't help with this, getting myself out of the loop.

**Comment by fgeyer16** [comment]
Single sign on works now. To prevent confused users I removed the login link for the local login in the user menu and replaced it by a link to the cas login at profile.myclimateservices.eu. If you are already logged in at the SSO server you will be automatically logged in to the csis if you visit the home page of csis

All the **developer accounts** (people who can configure drupal)are l**ocal accounts only**. They can not login via the offered login link. **Please enter /user/login in your Browser directly to login!**

**Comment by fgeyer16** [comment]
> ATM credentials for EMIKAT and other services are part of the user profile. That means, when a new user registers, we have to copy the credentials. Is this really the way to go?! Furthermore, aren't the profiles now managed on profiles.myclimateservice.eu?

As far as I can see the credentials are part of the local profile. If they are always the same enter them as default value in the local User profile. Then on creation of a new user this user will have them without copying them manually. As long as they are only used by the csis I would leave them in the local profile.  

What uses the credentials? PHP code js code or both? 

As an alternative for storing the credentials in the local user profile, we could create a own configuration for service credentials. But what if the credentials will be different for different users in the future?

**Comment by p-a-s-c-a-l** [comment]
> are part of the local profile.

We need it in both! I've just noticed that this information is not available in profile.myclimateservices.eu profiles. But it needs to be there, unless we find a better solution.


> What uses the credentials? PHP code js code or both?

None of them. They are exposed via the JSON API and used by external web applications. So this is  just a hacky intermediate solution.

> But what if the credentials will be different for different users in the future?

ATM it doesn't look like that will be the case. 

Anyway, we'll keep it as it is. The better solution would be to use Drupal as OAuth 2.0 Provider in EMIKAT, but I don't think that this can be supported @humerh?

**Comment by DenoBeno** [comment]
Can this be closed now?

**Comment by patrickkaleta** [comment]
This can probably be best answered by @fgeyer16, he set it up. AFAIK some users experience problems with logging into the system, but for that we open separate issues.

**Comment by fgeyer16** [comment]
Single sign on is working. We may need to adjust the gateway settings. That means on which pages will the user be logged in automatically if he is already logged in on SSO.

For handling Problems on logging in the most common problems are when the user was created manually on the csis. Then you will have to check the `Allow user to log in via CAS` manually and enter the Username which is used on profile.

CAS/SSO users are not allowed to login locally. They also can neither change their local password (which is never needed) nor their local email address or username. If they try they will get an error.
So one problem of users who where "used" to the local login before was to use the local login form after they were "moved" to SSO. This is cause why the login link leads to the SSO login now and the local login is only reachable by entering the address in the browser. If somebody asks you for an account on csis please tell him to register on profile and  then visit the homepage of csis. The user on csis will then be created automatically.

This way we schould not get login problems any more.

**Comment by fgeyer16** [comment]
So closing

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 Can you please check the SSO profiles whether they contain the [EMIKAT Credentials](https://github.com/clarity-h2020/docker-drupal/issues/16#issuecomment-525145170) and if not add them (also as default)? E.g. it seems that for Lena's account there no EMIKAT credentials available.

**Comment by fgeyer16** [comment]
Seems Lena logged in locally, i'm on it.

**Comment by DenoBeno** [comment]
I always log in locally. One of these days, we need to fix my account too.

**Comment by fgeyer16** [comment]
> I always log in locally. One of these days, we need to fix my account too.

You have developer role. I do not want to give administrators and developers Single Sign On.

**Comment by DenoBeno** [comment]
ah, OK

**Comment by p-a-s-c-a-l** [comment]
This seems to be working quite well now. If there are still problems, we can open an new issue.
