### ISSUE TITLE
PDF Generation broken

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#163]
Both on DEV and PROD:

> Error generating document: Failed to generate PDF: Loading pages (1/6) [> ] 0% [======> ] 10% QSslSocket: cannot resolve CRYPTO_num_locks QSslSocket: cannot resolve CRYPTO_set_id_callback QSslSocket: cannot resolve CRYPTO_set_locking_callback QSslSocket: cannot resolve sk_free QSslSocket: c

See also https://github.com/clarity-h2020/csis-technical-validation/issues/76#issuecomment-657628093

Probably an error in the HTML2PDF library. Which one are we using?

**Comment by patrickkaleta** [comment]
> Both on DEV and PROD:
> 
> > Error generating document: Failed to generate PDF: Loading pages (1/6) [> ] 0% [======> ] 10% QSslSocket: cannot resolve CRYPTO_num_locks QSslSocket: cannot resolve CRYPTO_set_id_callback QSslSocket: cannot resolve CRYPTO_set_locking_callback QSslSocket: cannot resolve sk_free QSslSocket: c
> 
> See also [clarity-h2020/csis-technical-validation#76 (comment)](https://github.com/clarity-h2020/csis-technical-validation/issues/76#issuecomment-657628093)
> 
> Probably an error in the HTML2PDF library. Which one are we using?

We're using wkhtmltopdf (set in the [Entity print settings](https://csis-dev.myclimateservice.eu/admin/config/content/entityprint)) in the version 0.12.4 (I believe).

The error message seems familiar. I think we had that problem with QSslSocket in the past. AFAIK @DenoBeno fixed it be installing/updating something inside the docker-container? And maybe that got lost after the [update](https://github.com/clarity-h2020/docker-drupal/issues/156) of the Docker container?

**Comment by patrickkaleta** [comment]
> Error generating document: Failed to generate PDF: Loading pages (1/6) [> ] 0% [======> ] 10% QSslSocket: cannot resolve CRYPTO_num_locks QSslSocket: cannot resolve CRYPTO_set_id_callback QSslSocket: cannot resolve CRYPTO_set_locking_callback QSslSocket: cannot resolve sk_free QSslSocket: c

Probably related to this [issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001). Seems like Debian and wkhtmltopdf 0.12.4 have a problematic relationship. The proposed solution by updating wkhtmltopdf to version 0.12.5 is not the solution, since that version itself has its problems (see [1](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3242), [2](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3242)), so I believe we went with something like proposed in [this comment](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001#issuecomment-309673453).

But a month ago version 0.12.6 was finally released, which [seems to solve some of the issues](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3953#issuecomment-640242222) introduced in 0.12.5.

**Comment by p-a-s-c-a-l** [comment]
h4cc/wkhtmltopdf-amd64 seems to be [abandoned](https://github.com/h4cc/wkhtmltopdf-amd64/issues/43). wkhtmltopdf. can be downloaded from [here](https://wkhtmltopdf.org/downloads.html), so I'll update the docker image.

**Comment by p-a-s-c-a-l** [comment]
> Error generating document: Failed to generate PDF: sh: 1: /app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: not found 

Now the question is how to tell [phpwkhtmltopdf](https://github.com/mikehaertl/phpwkhtmltopdf) where to find the wkhtmltopdf binary?

**Comment by patrickkaleta** [comment]
> > Error generating document: Failed to generate PDF: sh: 1: /app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64: not found
> 
> Now the question is how to tell [phpwkhtmltopdf](https://github.com/mikehaertl/phpwkhtmltopdf) where to find the wkhtmltopdf binary?

That should be possible in the [Entity print settings](https://csis-dev.myclimateservice.eu/admin/config/content/entityprint). There you can specify the binary location.

**Comment by p-a-s-c-a-l** [comment]
PDF Generation [is working again](https://csis-dev.myclimateservice.eu/print/pdf/group/1) on DEV. I'm going to update PROD with the new docker image.

**Comment by patrickkaleta** [comment]
> I'm going to update PROD with the new docker image.
 
I think there is a webinar taking place right now or just about to.

**Comment by p-a-s-c-a-l** [comment]
PROD is updated now. I had to lock drupal/group at 1.0.0-rc5. See https://github.com/clarity-h2020/docker-drupal/issues/166
