### ISSUE TITLE
Twins Map not working properly on Summary Page

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#165]
https://csis.myclimateservice.eu/study/185/step/5119/view/summary
2020-07-13 16:00
Firefox 78.0.1 (64-Bit) / Windows 10

![grafik](https://user-images.githubusercontent.com/18684786/87314616-cbaf1e00-c523-11ea-9244-bd4bc04b6e0b.png)

**expected behaviour** I was expecting to see a full map in the OpenStreetMap Panel.
**actual behavour** Most tiles in the map were not loaded. I just noticed the map only completes when I open up the console window with CTRL+SHIFT+I. I can actually reproduce this. Pressing F5 results again in the incomplete map. Opening the console completes it.
**what i did** I followed all the steps to create a study and was in the process of clicking through HC, HCLE, EE, VA,... and the respective subitems (introduction, data, table). After clicking on summary and scrolling down a bit to "Included Elements" and expanding "Details" of "DC3 - Climate adaption for the city of Linz" the above is what I see. Refreshing did not load the missing tiles.

_Originally posted by @johanneshorak in https://github.com/clarity-h2020/csis-technical-validation/issues/76#issuecomment-657592506_

**Comment by patrickkaleta** [comment]
Seems to be a CSS issue affecting the Leaflet map widget. This widget is provided by a [contributed module](https://www.drupal.org/project/leaflet), so our customizing options are limited. The problem appears when the showcase _Details_ are hidden at first and then expanded by the user's interaction. Setting the _Details_ to be displayed open by default in the [display mode](https://csis-dev.myclimateservice.eu/admin/structure/types/manage/showcase/display/summary) let's the map render properly. I suppose this to be the easiest and fastest solution, since I don't know how we would have to alter the CSS otherwise.

@therter did you ever experience similiar displaying problems with the map component and have maybe found a possible CSS or JS solution to it?

**Comment by therter** [comment]
> @therter did you ever experience similiar displaying problems with the map component and have maybe found a possible CSS or JS solution to it?

I had a similar problem, that I could solve with a JS invocation of the method invalidateSize() on the leaflet instance.  But I am not sure, if this was the same problem, because the position of the tiles was also wrong, but now there are only invisible tiles.

**Comment by p-a-s-c-a-l** [comment]
> Setting the _Details_ to be displayed open by default in the [display mode](https://csis-dev.myclimateservice.eu/admin/structure/types/manage/showcase/display/summary) let's the map render properly. I suppose this to be the easiest and fastest solution, since I don't know how we would have to alter the CSS otherwise.

Yes, we should follow this approach.

**Comment by fgeyer16** [comment]
> I had a similar problem, that I could solve with a JS invocation of the method invalidateSize() on the leaflet instance. But I am not sure, if this was the same problem,

I think this is the same problem as @therter had,  There is a short js which should fix this:

```
 (function($,Drupal) {
   Drupal.behaviors.tabs_leaflet_fix = {
     attach: function (context,settings) {
         $('form').on('click',function() {
           for(var maps in drupalSettings.leaflet){
             map = drupalSettings.leaflet[maps];
             map.lMap.invalidateSize(false);
           }
         });
     }
   }
 })(jQuery,Drupal);
```
This is taken from the events page where I had the same problem in the add form for the location widget. So we will have to adjust the jquery selector for the on click event.

**Comment by p-a-s-c-a-l** [comment]
Did you already implement this fix in CSI-DEV @fgeyer16 ?

**Comment by p-a-s-c-a-l** [comment]
wontfix
