### ISSUE TITLE
 drupal/group patches still needed?

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#166]
Are the  drupal/group patches still nedded for drupal/group v1.0.0 ?

> Updating drupal/group (1.0.0-rc5 => 1.0.0): Downloading (100%)
> - Installing drupal/group (1.0.0): Loading from cache
>  - Applying patches for drupal/group
    patches/group_2833054.patch (Issue #2833054)
    patches/group_2872645.patch (Issue #2872645)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/group_2872645.patch

**Comment by p-a-s-c-a-l** [comment]
> One or more problems were detected with your Drupal installation. Check the status report for more information. 

One problem is the outdated groups module. Can we safely upgrade and remove the patches @fgeyer16 ?

**Comment by patrickkaleta** [comment]
@fgeyer16 FYI: Group module now recently went from RC (release candidate) to a "real" release (finally...), so keep that in mind when testing our currently applied Group-patches.

**Comment by p-a-s-c-a-l** [comment]
Group Module should be [updated ASAP](https://www.drupal.org/sa-contrib-2020-030).

**Comment by fgeyer16** [comment]
group module is up to date now on csis-dev.

**Comment by p-a-s-c-a-l** [comment]
thanks
