### ISSUE TITLE
Create Custom PostGIS Docker Image

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#167]
> The new cities are now in the dev instance.
> 
> There were two problems after the last image update:
> #### The drupal database was not updated and tried to use the postgis-2.5.so library.
> 
> Normally, this can be fixed with the following command (see [here](https://github.com/postgis/docker-postgis#known-issues--errors))
> 
> ```
> docker exec csis-postgis update-postgis.sh
> ```
> 
> But in this case, the update-postgis.sh script also tried to use the old library, so within the postgis container, a symbolic link to the existing postgis-3.so library had to be created.
> 
> ```
> /usr/lib/postgresql/10/lib# ln -s postgis-3.so postgis-2.5.so 
> ```
> 
> #### The tool shp2pgsql was not installed
> 
> The new docker image does not install the postgis client tools. So I had to install the postgis client tools with the following commands:
> 
> ```
> apt-get update
> apt-get install postgis
> ```
> 
> After this, it was possible to execute the republish script

@therter When we recreate the container, [your customisations](https://github.com/clarity-h2020/data-package/issues/75#issuecomment-666417615) are lost. Therefore we have to create a custom `postgis/postgis:10-3.0` image as we did for [Drupal](https://github.com/clarity-h2020/docker-drupal/tree/dev/drupal).

_Originally posted by @p-a-s-c-a-l in https://github.com/clarity-h2020/data-package/issues/75#issuecomment-666426484_

**Comment by p-a-s-c-a-l** [comment]
@therter The compose file has to be updated, too. Our custom postgis image should be tagged with 'csis-postgis:10-3.0' .
See https://github.com/clarity-h2020/docker-drupal/issues/156#issue-650555286

**Comment by therter** [comment]
> @therter The compose file has to be updated, too. Our custom postgis image should be tagged with 'csis-postgis:10-3.0' .
> See [#156 (comment)](https://github.com/clarity-h2020/docker-drupal/issues/156#issue-650555286)

I have updated the compose file on the dev instance. If this will not lead to problems, then I will update the prod instance

**Comment by p-a-s-c-a-l** [comment]
done
