### ISSUE TITLE
Set CSIS Prod and Dev into Maintenance mode due to a server maintenance

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#169]
PROD and DEV instance need to be switched into maintenance mode (via Drupal BE UI). Servers will be shutdown today due to maintenance works on our IT infrastructure. Everything should be back up on Monday (latest).

Automated CI testing will throw errors during that time, which can be ignored.

**Comment by ghilbrae** [comment]
Is this related with Denis' email from the other day? Will this be done at noon? We have a webinar starting at 10 that will end at 12. Thanks!

**Comment by patrickkaleta** [comment]
Yes, it's related to his email. And don't worry, I won't put the site under maintenance mode until the webinar is done.

**Comment by ghilbrae** [comment]
Thanks!!

**Comment by patrickkaleta** [comment]
Done. Servers are back online and PROD and DEV are available once again.
