### ISSUE TITLE
Wrong Mimetypes

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#2]
Drupal sets wrong MIME Type on automatically generated / processed CSS & JS files causing browsers like Firefox or Chrome to refuse loading such files:

``Problem loading stylesheet - not loaded because its MIME type, "text/html", is not "text/css", "text/html", is not "text/javascript".``

**Temporary workaround**: disable JS / CSS preprocessing as described [here](https://www.drupal.org/project/jstools/issues/72561#comment-12566682)
```
drush -y config-set system.performance css.preprocess 0
drush -y config-set system.performance js.preprocess 0
```

**Comment by p-a-s-c-a-l** [comment]
See also https://github.com/clarity-h2020/csis/issues/2

**Comment by fgeyer16** [comment]
The Problem seems to be caused by a non writable temporary directory. 
Please check if the directory given in the setting **system.file (path in the interface: admin/config/media/file-system)** exists and is writeable for drupal.

**Comment by p-a-s-c-a-l** [comment]
/tmp mode is 1777 (world-writable.) and mounted as docker [tmpfs](https://docs.docker.com/storage/tmpfs/). tmpfs doesn't seem to work as expected, falling back to bind-mount  (host-mounted volume) for /tmp.

**Comment by p-a-s-c-a-l** [comment]
resolved
