### ISSUE TITLE
Report Generation

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#20]
Generate PDFs out of a Drupal Page either using a special Drupal Module (if available) or use some external libraries like Jasper Reports and fetch the study data from the [REST API](https://github.com/clarity-h2020/docker-drupal/issues/17).

**Important**: All information needed to generate a report should reside in the [Group Type "Study"](https://github.com/clarity-h2020/docker-drupal/issues/8]).

**Comment by fgeyer16** [comment]
There are three modules for Drupal  8 which allow creating pdf from content:

1. [Entity print](https://www.drupal.org/project/entity_print)
2. [Printable](https://www.drupal.org/project/printable)
3. [PrinterFriendly](https://www.drupal.org/project/printfriendly)
From a first view I think 1 or 3 are more flexible than 2 so that we can create nice reports. For the definitive decision we will have to wait until the Study design in Drupal  is fixed

**Comment by patrickkaleta** [comment]
I had a look at those three modules @fgeyer16 suggested:

1. Entity print: 
   - supports multiple PDF engines (worked best with tecnickcom/tcpdf)
   - works with Views
   - doesn't include the map component, so we would have to take a screenshot of that and include in the View

2. Printable:
   - doesn't work with Views, supposed to work with all Content types and Groups, but the "generate-pdf button" doesn't appear for every content type. No documentation available, so no idea how to fix this 

3. Printfriendly:
   - only Pro version (40$/year) promises to work with dynamic content (Angular/React)
   - Drupal module only works for content types (no Groups or Views!) on two display modes (Teaser & Full page)

I would suggest using Entity print and include all dynamic content (like the map compoment) as screenshots. Alternatively I will have a look at athenapdf (https://github.com/arachnys/athenapdf), which is a pdf service that should work as a Docker image.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta @fgeyer16 

Report generation has now high priority as it's "show-stopper" feature for CSIS v1 and can be implemented even if no additional data (e.g. from impact calculation) is yet available.

Imho the following step are required:

- define a structure for report content at the level of Gl-Step and Study Group Type. For static content, we could introduce an additional boolean flag *includeInReport*.
- Add the "Include in report" buttons to each GL-Step page to flag "static" content (e.g. data package resource descriptions, taxonomy terms like GL-Step description, ...) for inclusion in the report
- Add the "Include in report" buttons for "dynamic" content (like tables and maps) that are embedded as external apps and that display content that is not available in the Drupal Backend (e.g. displayed maps layers are obtained from external WMS).
  - for CSIS v2: add the "Include in report" button in each embedded React/iFrame Apps (e.g. [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis/issues/3) separately. These components will have to use the JSON API to patch their report content into the GL-Step entity. ()
  - **for [CSIS v1](https://github.com/clarity-h2020/docker-drupal/milestone/2):** extend [ReactMount](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/) and [iFrame](https://csis.myclimateservice.eu/admin/structure/types/manage/extended_iframe/fields) Content Types by  an "Include in report" button that uses [html2canvas](https://github.com/clarity-h2020/scenario-analysis/issues/3#issuecomment-434228501) to create a screenshot of the whole embedded app (e.g. map with all layers as shown on the screen) and stores it in the GL-Step.
-  create views for the different summary pages that contain the report-related properties (like the screenshots of the apps) of the Gl-Step. This corresponds to the summary tabs on the level of the distinct steps, e.g. [Analyse Vulnerability Summary](https://csis.myclimateservice.eu/study/1/step/82/view/summary)
- create a view for the complete study that aggregates the different step views. Question: Does this correspond to [Study Summary](https://csis.myclimateservice.eu/study/1/step/82/view/summary) tab or do we need another top-level "Report" tab?
- add PDF Export functionality as discussed [here](https://github.com/clarity-h2020/docker-drupal/issues/20#issuecomment-443632736)

**Comment by fgeyer16** [comment]
I added fields to the summary view mode of GL-Step and Study group. So for now all Content of type "Report Image" which is related to a Step or a Study is shown on the Summary tabs.
The content type "Report Image" has for now two types: Maps and tables and is the content which will be generated by the "include in report Button" ( #46 ). The images will be sorted by maps and Table in on the summary tab. The comment to an image can be added/edited on the summary tab.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 

Thanks! Some minor issues: 
- ~Report Images are shown in the GL-Step View, e.g. [here](https://csis.myclimateservice.eu/study/1/view/intro)~ fixed
- Report Images in summary are not visible  for demo user

![grafik](https://user-images.githubusercontent.com/1788226/53243276-a2c88780-36a7-11e9-966b-56432bd4be2b.png)

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 
*EVA: Report summary Images - EVA Study summary* What is it supposed to show? A 'final' report including the information from all steps? The view aggregates the GL-steps, right? But only the introduction (taxonomy) is shown.  Anyway, the summary Tab of the Study is not the reight place for the final report, see 2)

What we still need is
1) 'Include in Report Button'. It seems that there is 'something' available in the csis_helper_module, but without further information, I cannot proceed.
2) A 'final' report that includes the general study report (context + data package + map) plus all GL-Step report. This tab should probably be shown after the 'last EU-GL Step" 
3) A possibility to print the final report

**Comment by p-a-s-c-a-l** [comment]
I've installed entity print, but the result is not what I've expected.

That's the Assess Risk & Impact Summary Page including report images from MCDA:

![grafik](https://user-images.githubusercontent.com/1788226/54347508-6dc8a880-4647-11e9-805f-664353c20058.png)

And that's what entity print generates:

![grafik](https://user-images.githubusercontent.com/1788226/54347395-3e19a080-4647-11e9-931b-943381549977.png)

I've set permission on almost any entities rendered in the summary view (e.g. EU-GL: Use all print engines: Authenticated user) but that didn't help.

@patrickkaleta @fgeyer16 

According to the [module description](https://www.drupal.org/project/entity_print) no separate PDF Engine is required for Drupal 8. However the [documentation](https://www.drupal.org/docs/8/modules/entity-print/usage) says that *Dompdf* has to be installed (not clear if this required for Drupal 7 or 8) as opposed to the Module description which requires *wkhtmltopdf*  for Drupal 7. I tried to install *Dompdf*, but it failed with the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phenx/php-svg-lib[v0.3.2, v0.2].
    - Can only install one of: phenx/php-svg-lib[v0.2, v0.3.2].
    - Can only install one of: phenx/php-svg-lib[v0.2, v0.3.2].
    - dompdf/dompdf v0.8.0 requires phenx/php-svg-lib 0.2.* -> satisfiable by phenx/php-svg-lib[v0.2].
    - Installation request for dompdf/dompdf 0.8.0 -> satisfiable by dompdf/dompdf[v0.8.0].
    - Installation request for phenx/php-svg-lib (locked at v0.3.2) -> satisfiable by phenx/php-svg-lib[v0.3.2].

Installation failed, reverting ./composer.json to its original content.
```

But as PDF generation as such works, I'm not sure if using another (?) PDF engine would solve the problem.

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
regarding the "Include in Report Button" we first tried to solve this with a custom field "snapshot", which turned out to be too complex. So, instead we now have a [token field](https://csis.myclimateservice.eu/admin/structure/ds/fields/manage_token/include_in_report_button) (created via [Display Suite](https://www.drupal.org/project/ds)), which creates the "Include in Report Button" and can be set on the display of any content type (currently done for the [React mount with js](https://csis.myclimateservice.eu/admin/structure/types/manage/react_mount_with_js/display)).

In the [csis-helpers Module](https://github.com/clarity-h2020/csis-helpers-module/blob/dev/js/csis_include_in_report.js) that button could then trigger the generation of the screenshot and create a Report image entity via JSON:API + then link that created Report image to the corresponding Group (this is already done, since it wasn't much work).

It seems like you already managed to create the screenshot and post the Report image in your [Scenario analysis app](https://github.com/clarity-h2020/scenario-analysis). I can now try to extract the necessary code from there and add it to the csis-helpers Module.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta 
Thanks. The relevant JavaScript code for taking the screenshots is available [here](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/scripts/services/drupalService.js#L398). However, I use the AngularJS framework and it's $http and $resource services. So this cannot be used 1:1 in 'plain' JavaScript. The general program flow is:
1) GET gl-step entity and extract report images array from relationships (this is necessary since PATCH does overwrite the complete array and does not add new entities)
2) POST new file (binary PNG) and get the uuid
3) POST new report_image from [template](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/data/reportImageTemplate.json) assign file uuid from 2) to relationships and get uuid of report image entity
4) PATCH gl-step entity, sending as payload a simple [template](https://github.com/clarity-h2020/scenario-analysis/blob/dev/app/data/glStepTemplate.json) + the array retrieved in 1) with pushed report image uuid retrieved in 3)

Any idea what's wrong with the entity print module? I've tested it only in my local instance. I can make it available on CSIS.

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
thanks for the instructions!

Regarding the entity print module, I will have a look at it in my local instance as well (check which PDF engine works best) and talk to the guy responsible for setting up entity print in a different Drupal 8 project. On the CSIS [module-page](https://csis.myclimateservice.eu/admin/modules) I can already see that the entity print module is available, it only needs to be installed (activated), so I don't think you need to do anything at the moment.

**Comment by fgeyer16** [comment]
@p-a-s-c-a-l 
The difference between screen and pdf comes from Drupals view modes system. Entity print takes the default view mode while on screen the summary view mode is shown. How ever entity print provides a PDF view mode which has to be activated on Manage Display on the Dafault view mode:
 
![Bildschirmfoto von »2019-03-14 20-12-14«](https://user-images.githubusercontent.com/25331450/54384967-c7f05a80-4695-11e9-90be-d1879b012ca8.png)

Then you can arrange the fields on the PDF view mode. To copy an existing view mode first set Layout for Gl-step to none
![Bildschirmfoto von »2019-03-14 20-16-29«](https://user-images.githubusercontent.com/25331450/54385264-7eecd600-4696-11e9-89f6-852c918ec339.png)
and then clone the layout of the view mode
![Bildschirmfoto von »2019-03-14 20-19-58«](https://user-images.githubusercontent.com/25331450/54385311-9deb6800-4696-11e9-89de-716d2be63a32.png)

> According to the module description no separate PDF Engine is required for Drupal 8. However the documentation says that Dompdf has to be installed (not clear if this required for Drupal 7 or 8)

I installed entity print on my localsystem and dompdf was installed automatically by composer with its dependencies without an error
![Bildschirmfoto von »2019-03-14 19-53-17«](https://user-images.githubusercontent.com/25331450/54385447-ee62c580-4696-11e9-9946-71b9c5f9ee40.png)

I think composer was confused when you tried to install it a second time. From the log it looks like as if you (or composer) tried to get dompdf  0.8.0 while dompdf 0.8.3 was already installed So composer could not resolve dependencies.

**Comment by p-a-s-c-a-l** [comment]
Thanks, I'll give it a try. Regarding dompdf, you'r right, it's automatically installed. :-)

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l , @fgeyer16 
I can confirm that **dompdf** is installed automatically, but for me that engine doesn't work. When trying to generate the pdf I get an error saying that it's unable to load the css and/or images (even though I can access the respective URLs via Browser).

Installing **TCPDF (v1)** via "composer require tecnickcom/tcpdf ~6" worked fine and a pdf is generated. But I noticed that it has some problems when the format of the images is set to "Responsive image". In that case no image is printed onto the pdf. Using "Image" as the format works.
![responsive-image-formatter](https://user-images.githubusercontent.com/42167036/54431915-f6b71100-4727-11e9-9d35-ab9847bb063f.png)
 
<br>

Installing **PHP Wkhtmltopdf** worked with Composer:
- composer require h4cc/wkhtmltopdf-amd64
- composer require mikehaertl/phpwkhtmltopdf

Binary location has to be set to "/app/vendor/bin/wkhtmltopdf-amd64". 
But after trying to fix other error messages regarding shared libraries libxrender.so.1 and libfontconfig.so.1, I only managed to successfully destroy my local instance of the CSIS :(

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

I've created the PDF View for [Assess Risk and Impact Summary](https://csis.myclimateservice.eu/study/1/step/22/view/summary) and PDF creation works without the need to install additional modules:[5.Assess.Risk.and.Impact.pdf](https://github.com/clarity-h2020/docker-drupal/files/2971516/5.Assess.Risk.and.Impact.pdf)

![grafik](https://user-images.githubusercontent.com/1788226/54438871-e6a72d80-4737-11e9-8edd-5daef9b03fa3.png)


The PDF doesn't look very nice yet, but I think this can be improved by configuring additional PDF Views, e.g. for Taxonomy Terms and Report Images. There also a possibility to style PDF with custom CSS. BTW @DenoBeno what about the availability Alejandro for developing some CSS styles for the CSIS in general?

**Comment by p-a-s-c-a-l** [comment]
Display of Data Package could be improved in Study/Summary, the identifier shouldn't be shown so prominently. This is related to https://github.com/clarity-h2020/docker-drupal/issues/52#issuecomment-473805313

![grafik](https://user-images.githubusercontent.com/1788226/54514191-c48cf580-4959-11e9-90de-99994d583d60.png)

**Comment by p-a-s-c-a-l** [comment]
Minor Issue: Scenario Analysis Report images are only relevant in RA/IA step, so the report image category "scenario analysis" should not be should be shown in the other Summary Views. @fgeyer16 any idea how this could be easily resolved?

![grafik](https://user-images.githubusercontent.com/1788226/54516056-1e8fba00-495e-11e9-86cd-258851b91f70.png)

**Comment by patrickkaleta** [comment]
> Display of Data Package could be improved in Study/Summary, the identifier shouldn't be shown so prominently. This is related to [#52 (comment)](https://github.com/clarity-h2020/docker-drupal/issues/52#issuecomment-473805313)

I altered the corresponding [display](https://csis.myclimateservice.eu/admin/structure/types/manage/data_package/display/teaser) to show the title and below that the identifier (in a less prominent way).
![study-summary-view](https://user-images.githubusercontent.com/42167036/54516725-0caf1680-4960-11e9-9fae-f1e61a2c6b25.png)

**Comment by p-a-s-c-a-l** [comment]
Basic Report Generation Functionality implemented.
