### ISSUE TITLE
Basic Map Integration Example

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#22]
Create a basic entity with **country** and **study_area** fields. Note: This basic entity will later be replaced by / integrated with the [Study Group Type](https://github.com/clarity-h2020/docker-drupal/issues/8).

- country field: 
  - used to center the map shown in Mockup 0130 on a country selected  by the user in in Mockup 0120
  - a *reference* to an entry in a [countries](https://github.com/clarity-h2020/docker-drupal/issues/7#issue-357383495) vocabulary. Properties of the Country Taxonomy Type: name, country code, geom (type: [Geofield](https://www.drupal.org/project/geofield)), etc.
- study_area field:
  - used for storing the spatial study area selected in Mockup 0130
  - a [Geofield](https://www.drupal.org/project/geofield)) attached to the [Study Group Type](https://github.com/clarity-h2020/docker-drupal/issues/8)) instance

Populate Countries Vocabulary (Taxonomy) with Couintry Data + Polygons, e.g. from https://github.com/clarity-h2020/docker-drupal/issues/7#issuecomment-419022715
Integrate React Map (e.g. Leaflet) via [Module](https://github.com/clarity-h2020/docker-drupal/issues/11) or [iFrame](https://github.com/clarity-h2020/docker-drupal/issues/18) (depending on the result of the evaluation).

Connect React Web App via [Drupal REST API](https://github.com/clarity-h2020/docker-drupal/issues/17) and / or [JavaScript](https://github.com/clarity-h2020/docker-drupal/issues/18#issuecomment-421252554) to Drupal Backend and implement the features for
- setting and showing the polygon of the selected country on the react map
- selecting the study area (bbox, polygon, etc.) in the react map and storing the geometry in the study_area field.

![0120 cca _ study _ definition context end-user guide](https://user-images.githubusercontent.com/1788226/45550886-8c7eeb80-b82c-11e8-8a7a-e38e6aa2bb34.png)

![0130 cca _ study _ area end-user guide](https://user-images.githubusercontent.com/1788226/45550761-24c8a080-b82c-11e8-8ca3-0896c628d893.png)

**Comment by therter** [comment]
**Add taxonomy terms via SQL:**

As example, the taxonomy country with the two fields country and study_area was created. 
When a shape file with the country data exists (e.g. from https://gadm.org/download_world.html), a import script can be created by the shp2pgsql command. 

**Example:**
```
shp2pgsql -d -W UTF-8 shapefile table-name > ~/import-script.sql
```

This script can be executed with the psql command. After this, the data from the shape file is available in the specified database table. This data can be added to the drupal system with a pgsql script like the following script:

```SQL
CREATE OR REPLACE FUNCTION public.import_countries()
    RETURNS boolean LANGUAGE 'plpgsql' COST 100 VOLATILE 
AS $BODY$
declare
        ref RECORD;
	tid integer;
begin
	--the imported data is contained within the table raw.countries
        for ref in select name, st_asText(the_geom) as the_geom from raw.countries  LOOP
		insert into taxonomy_term_data (vid, uuid, langcode)
		       values ('country', uuid_generate_v4(), 'en');
			
		select currval('taxonomy_term_data_tid_seq') into tid;

		insert into taxonomy_term_field_data (tid, vid, langcode, name, description__value, description__format, weight, changed, default_langcode)
		       values (tid, 'country', 'en', ref.name, null, null, 0, EXTRACT(EPOCH FROM now())::int, 1);

		insert into taxonomy_term__field_country (bundle, deleted, entity_id, revision_id, langcode, delta, field_country_value)
		       values ('country', 0, tid, tid, 'en', 0, ref.name);
                -- the following code also converts the postgis geometry to GeoJSON
		insert into taxonomy_term__field_study_area (bundle, deleted, entity_id, revision_id, langcode, delta, field_study_area_value)
		       values ('country', 0, tid, tid, 'en', 0, ST_AsGeoJSON(ref.the_geom));
        END LOOP;
		
	return true;
end
$BODY$;
```

**Comment by therter** [comment]
A first gif of a map component that interacts with the drupal system:

![anim](https://user-images.githubusercontent.com/1788509/47282000-d4d4ba80-d5dd-11e8-91fa-4f9cb35b87ec.gif)

**Comment by therter** [comment]
A first gif of  a map component that interacts with the drupal system

![anim](https://user-images.githubusercontent.com/1788509/47283101-19625500-d5e2-11e8-9671-50de1e08724d.gif)

**Comment by therter** [comment]
A first gif of  a map component that interacts with the drupal system

![anim](https://user-images.githubusercontent.com/1788509/47283101-19625500-d5e2-11e8-9671-50de1e08724d.gif)

**Comment by therter** [comment]
To allow the communication with the REST API, the *RESTful Web Services* module has to be activated (`/admin/modules permission`) and the permissions for the required resources should be set via the page `/admin/config/services/rest`.

![restapi](https://user-images.githubusercontent.com/1788509/47298208-7298ab80-d617-11e8-8f5a-cf65581ea051.png)

Example to access the RestAPI from javascript code
```javascript
    fetch('http://localhost:8080/taxonomy/term/93?_format=json')
    // see https://developer.mozilla.org/en-US/docs/Web/API/Body/json
    .then((resp) => resp.json())
    .then(function(data) {
        //do something
        //window.mapCom.setGeom(data.field_study_area[0].value);
    })
    .catch(function(error) {
      console.log(JSON.stringify(error));
    });         
```

**Comment by p-a-s-c-a-l** [comment]
done
