### ISSUE TITLE
Add User roles

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#23]
as suggested by @fgeyer16 : for now we should have the following user roles:

- [x] Administrator (already exists): can do anything

- [x] Developer: can do almost anything (able to manipulate content types, views, taxonomies,...)

- [x]  Editor: can create content & taxonomy terms

**Comment by patrickkaleta** [comment]
New user roles have been generated. Let's wait and see how many people will actually request a user account and then I will try to get some feedback to check if the existing roles and set permissions are sufficient or need to be adapted.

**Comment by p-a-s-c-a-l** [comment]
Done. See also https://github.com/clarity-h2020/csis/issues/26
