### ISSUE TITLE
OpenLayers 4.1.0 library not found

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#24]
OpenLayers 4.1.0 library not found at libraries/openlayers/build/ol.js. Please !download it to libraries/openlayers/build, or undo your changes to the libraries registry to use the CDN version. 

Steps to resolve this issue are described in https://www.drupal.org/project/openlayersd8/issues/2993446

**Comment by p-a-s-c-a-l** [comment]
There a are several additional issues when trying to add a OpenLayers map. Therefore we'll use our [own map application](https://github.com/clarity-h2020/map-component) and remove the open layers plug-in.

**Comment by Itsman-AT** [comment]
The BB:Sceneario Transferability will use GeoField Map for showing its content.

**Comment by p-a-s-c-a-l** [comment]
> The BB:Sceneario Transferability will use GeoField Map for showing its content.

And what kind of map implementation is used internally by GeoField Map? Leaflet.js, OpenLayers or ...?

@Itsman-AT perhaps it would be good to join the weekly stand-up telco (now) o discuss these issues and the status of the implementation.

**Comment by DenoBeno** [comment]
Apparently this library is not needed. Plus, we have [another ticket](https://github.com/clarity-h2020/docker-drupal/issues/111) by @patrickkaleta where he's asking about deleting them from the system. Closing this one.
