### ISSUE TITLE
Drupal Update to v8.6.x

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#3]
Apply Drupal Security Update v8.5.6.
See [Update core via Composer](https://www.drupal.org/docs/8/update/update-core-via-composer)

```sh
# backup:
pascal@V3LS1809:/docker/999-duplicity$ docker-compose run duplicity
# update
pascal@V3LS1809:/docker/100-csis$ docker exec --user 1002 -it csis-drupal bash
pascal@e23b98b9fa41:/app$ composer outdated drupal/*
pascal@e23b98b9fa41:/app$ composer update drupal/core --with-dependencies
pascal@e23b98b9fa41:/app$ drush updatedb
pascal@e23b98b9fa41:/app$ drush cr
pascal@e23b98b9fa41:/app$ drush cex
pascal@e23b98b9fa41:/app$ exit
pascal@V3LS1809:/docker/100-csis$ git commit -a -m"...."
pascal@V3LS1809:/docker/100-csis$ git push
```

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

Running `composer update drupal/core --with-dependencies` did **not** upgrade Drupal v8.5.6. Running `composer update` however did update Drupal v8.5.6 to v8.5.7 (along with all other updatable modules). However, the most recent version of Drupal is v8.6.1. Any ideas, why composer does not perform the update to v8.6.1?

**Comment by p-a-s-c-a-l** [comment]
Solution: update [composer.json](https://github.com/clarity-h2020/docker-drupal/blob/dev/drupal-data/composer.json):
```json
....
"require": {
        "drupal/core": "~8.6.0",
....
"require-dev": {
        "webflo/drupal-core-require-dev": "~8.6.0"
    },
````

and run 
```
composer update drupal/core webflo/drupal-core-require-dev --with-dependencies'
drush updb
drush cr
dursh cex
```

@patrickkaleta @fgeyer16 
Can we safely update to 8.6.2 without breaking your custom modules, etc.? Update is required due to https://github.com/clarity-h2020/docker-drupal/issues/27

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
I'm locally already running on a 8.6.1 version and the Help-widgets module is running as expected. Update to 8.6.2 should not break the module.

As far as I'm aware of this is also the only custom module we have right now (at least it's the only one I created).

**Comment by fgeyer16** [comment]
As far as I know  a update of the third number of the version (8.6.x) should never be a problem. This Updates never change the API itself so all installed modules can use it as before the update.

**Comment by p-a-s-c-a-l** [comment]
Updated from v8.5.x to v8.6.x to resolve the '[Files created with REST API are only temporary](https://github.com/clarity-h2020/docker-drupal/issues/27)' issue.
