### ISSUE TITLE
JSON API Authorisation Error

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#30]
Accessing the HAL+JSON representation of an entity (e.g. `/study/1?_format=hal_json`) results in the following error although accessing the XML or plain JSON representation (e.g. `/study/1?_format=json`) does work:

```json
{"message":"You are not authorized to view this group entity of bundle study."}
```

@fgeyer16 @patrickkaleta 

Is there anything else to configure apart from these setting in REST UI:

![grafik](https://user-images.githubusercontent.com/1788226/47985089-eab3a680-e0d8-11e8-8fec-d930e8e41d09.png)

**Comment by p-a-s-c-a-l** [comment]
~The error magically disappeared after editing the group entity. Perhaps a database / consistency problem.~

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
cannot reproduce this error. Requesting JSON and HAL_JSON worked for me (both, as anonymous user and as logged in administrator).

Didn't change anything, just flushed the cache a while ago. Not sure, what could be the cause for your problem.

**Comment by p-a-s-c-a-l** [comment]
Entity `/study/1` damaged beyond repair after changing some fields in the local dev instance, works with other entities.
