### ISSUE TITLE
iFrame Integration not working properly in Tab Group

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#36]
If an iFrame is embedded in a Field Group **Tab**, [iFrame integration](https://github.com/clarity-h2020/docker-drupal/issues/18) with [seamless.js](http://travistidwell.com/seamless.js/) does not work, especially if the iFame resides on a tab that is not visible when the page is loaded.

**Comment by fgeyer16** [comment]
Any output un the js console of the browser?

**Comment by p-a-s-c-a-l** [comment]
no js console output. problem probably related to the theme.
