### ISSUE TITLE
Cannot load GroupContent entities for an unsaved entity

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#37]
Creating a new entity in a group, e.g. `/group/1/content/create` doesn't work anymore:
``Drupal\Core\Entity\EntityStorageException: Cannot load GroupContent entities for an unsaved entity. in Drupal\group\Entity\Storage\GroupContentStorage->loadByEntity() (line 84 of /app/web/modules/contrib/group/src/Entity/Storage/GroupContentStorage.php).``

See also [issue #2966706](https://www.drupal.org/project/group/issues/2966706).

@fgeyer16 @patrickkaleta 
Any idea how to fix this?

**Comment by p-a-s-c-a-l** [comment]
🔥 Same problem when trying to create a new entity: `node/add/gl_step`.

**Comment by patrickkaleta** [comment]
Seems like all content entities show the same error message now. Even creating a default "Basic page" entity (which doesn't even have a relation to Group!) doesn't work anymore.

@p-a-s-c-a-l 
I would suggest a DB rollback, unless @fgeyer16 has an idea on how this can be fixed?

**Comment by fgeyer16** [comment]
I think I messed up something with the helpers module, Im on it

**Comment by fgeyer16** [comment]
The bug is repaired. I forgot that add and edit forms are the same.
