### ISSUE TITLE
We need more script memory

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#38]
In the moment the php memory limit is at 128  MB. Trying to implement the automatic generation of group content I get an exhausted memory error. 
So we definitely need more php memory. Lets try if memory_limit = 256M are enough.
Please somebody from AIT, who can do that on the server.Or is it an docker issue?

**Comment by p-a-s-c-a-l** [comment]
Since php.ini is not part of a docker-volume and changes to this file will be lost when the container is recreated, I added `ini_set('memory_limit', '512M');` to `web/sites/default/settings.php`.

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/48261603-ed3b3680-e41f-11e8-8afb-3b060f125f91.png)
