### ISSUE TITLE
Automatically create all GL-Step entities when creating a new Study group

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#39]
Added new functionality which creates all necessary GL-Step entities right after a new Study group is created by a user. Those entities receive a title (name of the EU-GL step) and the corresponding EU-GL taxonomy term. They also get assigned to the new group and the user who created that group.

@p-a-s-c-a-l 
I noticed some inconsistencies between the EU-GL terms used in the mockup and the infographic used here: https://myclimateservices.eu/about-us (infographic is missing "Hazard - Local Effect", while mockup doesn't include steps 5-7). Any idea, how it is supposed to be?

For now, I combined those two adding the "Hazard - Local Effect" step into second place, leaving us with a total of 8 different GL-Steps.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta Yes, that's a know issue.

**Comment by p-a-s-c-a-l** [comment]
done
