### ISSUE TITLE
Problem with file permissions on server

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#42]
There seems to be a problem with the file permissions on the server, leading to the website not being properly displayed (missing navigation for studies, wrong admin-toolbar in FE, CSS errors on modules-page etc).

Looks like the problem first occured on Wednesday (21.12.2018) around 11:30 a.m. Error is reproducible in local environment when using a new tar.gz files (created after Wednesday). Drupal log-files are not of much help, but the status report (/admin/reports/status) helped me solve this problem locally following these steps:

1) status report first shows error "File system: The directory /tmp is not writable..."
Fix: make folder "**/drupal-tmp**" writable

2) status report now shows error "File system: The directory /app/private is not writable..." 
Fix: make folder "**/drupal-data/private**" writable

3) status report now shows error "File system: The directory sites/default/files is not writable..."
Fix: make folder "**/drupal-data/web/sites/default/files**" writable

After that the website is being displayed properly again.

@p-a-s-c-a-l , @fgeyer16 , @Itsman-AT 
I don't know why this bug suddenly appeared and if my approach is the solution for this or just a workaround.

**Comment by p-a-s-c-a-l** [comment]
My fault. :-)
I "moved" /drupal-data to a [private GitLab repository](https://github.com/clarity-h2020/docker-drupal/issues/41) and thereby reset owner:group and permissions to defaults values.  
Your approach is the solution.

**Comment by Itsman-AT** [comment]
Dear all, 
I have been in contact with our IT this afternoon and we decided to take this machine offline over the weekend because we incountered this problem and suspected an intruder. If this is not the case any mor I will keep in online. Or is there still unusual behaviour visible?

**Comment by fgeyer16** [comment]
I changed the Permissions of the three folders to 777 for now, but this should be only the fix until the correct owners are restored.
@p-a-s-c-a-l : I did not change the owners, since I do not know who the should be so that we have no side effects to the docker system. Can you please fix this or tell me the correct owners?

**Comment by p-a-s-c-a-l** [comment]
OK. I set the correct owner to `www-data` (only available inside inside docker container) and assigned r/w permissions to the folders.

**Comment by patrickkaleta** [comment]
Closing this since no further actions seem necessary and website currently not showing errors anymore.
