### ISSUE TITLE
Replace autocomplete fields by drop-down Fields

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#44]
Please replace all autocomplete fields by drop-down fields / lists when selecting *existing* terms from a taxonomy to give the user a chance to view the selectable options. E.g. consider the following example: It is not possible to choose an existing license for a Data Package if you don't know the name of the license.

![grafik](https://user-images.githubusercontent.com/1788226/49506699-fe406180-f87e-11e8-9e43-6f5fe683d035.png)

**Comment by p-a-s-c-a-l** [comment]
I replaced the inline entity form of the *spatial context/*grid* property by a select list, since we should reuse as much entities as possible. E.g. the spatial context (including its grid) is the same for the [different HC Datasets](https://github.com/clarity-h2020/data-package/issues/8) I'm going to add. So there's no need to to duplicate all this information.

However, in the select list, it's not possible to **add a new entity**:

![grafik](https://user-images.githubusercontent.com/1788226/49718370-28689980-fc5a-11e8-9ee3-238d03d8307e.png)

@patrickkaleta @fgeyer16 
Is there something like a "select or create new" editor form?

**Comment by fgeyer16** [comment]
For adding or creating and add a new entity to a reference field there are two possibilities:

- Inline entity Form of type complex. Here you can select if the user can create and/or select existing entity. But the selection widget is an autocomplete widget.
- Entity Browser. Same idea as Inline forms but a more flexible implementation. Entity browsers are managed at admin/config/content/entity_browser. If you want to offer a selection you have to create a view of display type entity browser first. 

I replaced your select list by an entity browser for grids. For now it is an iframe, but we can make a modal popup as well

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
I created the remaining Entity Browsers for Contributors, Sources and Licences (which are used both in the forms for data package and dataset) in the same way @fgeyer16 did for the grids. Other than that I didn't find any other autocomplete fields which should get replaced.

Some CSS changes need to be further applied (should hopefully be done by the end of the day).

**Comment by patrickkaleta** [comment]
CSS changes were not necessary in the end, we just had to set the appropriate formatter for the Entity Browser display inside the forms.
