### ISSUE TITLE
General UI Improvements

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#45]
Here we collect some important improvements to the user interface that need to be addressed for [CSIS v1](https://github.com/clarity-h2020/docker-drupal/milestone/2).

- [x] Landing Page
- [x] Remove admin controls for non-admin users
- [ ] better separation between study and GL-step tabs
- [x] Progress Indicator
- [x] better separation between prototype implementation and mock-ups
- [ ] [Update Taxonomies](https://github.com/clarity-h2020/docker-drupal/issues/14)
- [ ] Open Taxonomies'  description in popups or inline (Study type, sector)
- [ ] remove links on Taxonomies in study ( country)

**Comment by p-a-s-c-a-l** [comment]
### Landing Page

If you visit https://csis.myclimateservice.eu/ as non-member, a landing page with explanations (what can expect from the csis, etc.) should be shown. Get in touch with the @clarity-h2020/dissemination-team and ask them to provide some editorially prepared statements. Information about the CSIS can be found in the mission statement of the CSS Architecture (D4.2 on OwnCloud) and WP5 Business Plan Canvas (ask Denis, Jorge or Andrea).

**Comment by p-a-s-c-a-l** [comment]
### Remove admin controls for non-admin users

![grafik](https://user-images.githubusercontent.com/1788226/49934473-c95f8a80-fece-11e8-9135-7a53032ce58d.png)

![grafik](https://user-images.githubusercontent.com/1788226/51324333-b9f1d500-1a6a-11e9-9211-c0924dcc78d8.png)

**Comment by p-a-s-c-a-l** [comment]
### better separation between study and GL-step tabs

 GL-step tabs should be smaller, compare Mockup vs. Implementation

**Mockup**
![grafik](https://user-images.githubusercontent.com/1788226/49943600-9fb35d00-fee8-11e8-90aa-ad4991328f84.png)

**Drupal**
![grafik](https://user-images.githubusercontent.com/1788226/49943641-bf4a8580-fee8-11e8-88c3-507d7807d503.png)

**Comment by p-a-s-c-a-l** [comment]
### Progress Indicator
Indicate to the user, that the the study follow a x-step progress. Current step should be highlighted. 
All steps but the first step should be locked (tab visible but disabled), next step should be unlocked when the previous step has been completed (visited). 

![grafik](https://user-images.githubusercontent.com/1788226/49943745-fb7de600-fee8-11e8-9d70-4794481c2a43.png)

![grafik](https://user-images.githubusercontent.com/1788226/49943751-046eb780-fee9-11e8-98ad-0a662c00b4a4.png)

**Comment by p-a-s-c-a-l** [comment]
### Better separation between prototype implementation and mock-ups

Remove prototype tab and move the content on top of mock-up tabs. Mock-Up tab remains closed. Ensure the content doesn't show any "under construction" placeholder but at least a (html) wireframe implementation of the mock-up.

![grafik](https://user-images.githubusercontent.com/1788226/49944068-ce7e0300-fee9-11e8-9cf3-cfebb5c5e457.png)


**Update therter/15.01.19: I have already done this for the tabs Table and Map, because the initialisation of the used components works different when the prototype tab is used.**

**Comment by p-a-s-c-a-l** [comment]
### Update Taxonomies

This is a very important task. IMHO @DanielRodera could easily take care about this as it's a pure editorial task and does not involve structural changes or module development.

Please act proactively and add missing taxonomy terms and their descriptions. 
- for [Sectors](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/sector/overview) please select a standard for economic sectors e.g. from world bank, eu-gl, eurostat, etc.
- for [EU-GL Steps](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/eu_gl/overview) description consult D3.1 for EU-GL module description, for HC-LE description contact PLINIVUS. Ignore sub-taxonomy terms (Open Spaces/Surface Temperature) as I'm not sure if we gonna need them.
- High Quality Descriptions + Images of [Exposure (Elements at Risk)](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/elements_at_risk/overview) and [Hazard](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/hazards/overview) **Types** are extremely important for the visualisation of [Data Packages](https://github.com/clarity-h2020/data-package/)! Get in touch with PLINIVS and the WP3 for a list of supported Hazards and Exposure and ask the @clarity-h2020/dissemination-team to polish the descriptions and provide pictures.**

**Example: Flood Hazard**
![grafik](https://user-images.githubusercontent.com/1788226/49945850-0ab36280-feee-11e8-9959-742ded8e5a1c.png)

**Example: Buildings Exposure**
![grafik](https://user-images.githubusercontent.com/1788226/49945888-1ef75f80-feee-11e8-9b20-d532d583b657.png)

**Comment by patrickkaleta** [comment]
### Regarding the Landingpage:

Drupal offers the possibility to set **one** front page (/admin/config/system/site-information). We could create a content entity of type **Basic page** and fill it with general information that would be displayed to everyone (logged in and anonymous users). 

We could then place a block at the top of this content, which would display more basic information just for anonymous (=not logged in) users when they visit [https://csis.myclimateservice.eu/](https://csis.myclimateservice.eu/).
For logged in users we could use a different block, which could display a list with e.g. the latest studies?

@p-a-s-c-a-l 
Would that work for you? If we really want two completely seperate landingpages for logged in and not logged in users, we would need the [Rules Module](https://www.drupal.org/project/rules), which is for Drupal 8 currently only in alpha version. Maybe @fgeyer16 also has another idea how we could deal with the frontpage/landingpage?

Also Pascal, could you send me the e-mail adress of @DeliaModest so that I can contact her? Couldn't find her mail address on the CLARITY contact list and on GitHub it's not visible to me.

**Comment by p-a-s-c-a-l** [comment]
> Drupal offers the possibility to set one front page (/admin/config/system/site-information). 

Yes, that's a good solution. We don't need two different landing pages for members and non-members. And since the main entry page is myclimateservice.eu, for the "About CSIS Block" we could simply reuse or summarise the editorial content about the CSIS that (has / will be ?) produced for myclimateservice.eu.

**Comment by fgeyer16** [comment]
### **Regarding the progress Indicator:**
> All steps but the first step should be locked (tab visible but disabled), next step should be unlocked when the previous step has been completed (visited).

How do we determine that the step has been visited? I propose an additional field which gets a certain value on the first visit. In this case we can easily extend the functionality to a certain field is filled in the step later. We can query this field in the navigation creation view and inactivate the following steps.
better separation between study and GL-step tabs

### **regarding the better separation between study and GL-step tabs**: 
This should be done in css only and is so becomming a task of [this issue on clarity-theme](https://github.com/clarity-h2020/csis-theme/issues/5)

**Comment by p-a-s-c-a-l** [comment]
> I propose an additional field which gets a certain value on the first visit.

Sounds reasonable.

**Comment by therter** [comment]
**Regarding "Better separation between prototype implementation and mock-ups"**

I have already done this for the tabs Table and Map, because the initialisation of the used components works different when the prototype tab is used.

**Comment by fgeyer16** [comment]
Demo user only should see the DC1 Study and has no rights to change anything.
The admin toolbar has to be not available for the Demo user (in the moment there is an issue concerning the navigation, which is dissapearing on deactivation of the toolbar)

add contact link on Study team overview. Full name and not username should be shown on the team overview

**Comment by patrickkaleta** [comment]
### Regarding the landing page:
Landing page has been implemented. I installed a new [module](https://www.drupal.org/project/views_slideshow) to create a slideshow. Additionally, I added a new boolean field to the content type "**Basic page**" to determine whether a basic page shall be displayed in the slideshow or not. 

Currently this slideshow is displayed to everyone (logged-in users and anonymous users), but this can easily be changed once we have more content.

**Comment by patrickkaleta** [comment]
### Regarding "Remove admin controls for non-admin users"

I deactivated the toolbar and the control & edit buttons for non-admin users. 

As mentioned [above](https://github.com/clarity-h2020/docker-drupal/issues/45#issuecomment-456348299) there was this problem with the navigation disappearing, when the toolbar was deactivated. This seems to be fixed now as well. I wasn't able to find the exact reason but I believe it was some caching issue together with the display mode of the individual tabs.

**Comment by patrickkaleta** [comment]
### Regarding the progress indicator

This has been implemented by adding a new field "Progress indicator" in the Group-type "Study". When a new study is created, this field is initialized with the value 1 and only the first step can be accessed in the navigation.

At the moment, when the user visits any of the tabs in the current step, the value is incremented and the next step gets activated in the navigation. This behaviour can later be adapted, once it is clear at which point each step can be considered "completed".

**Comment by patrickkaleta** [comment]
### Update regarding Landing page
I added a block to the landing page displaying all available studies. For that i updated the "Study" Group, so that now it can be set whether a Study should be made public (=visible on the CSIS for others) or not. This functionality was added accordingly to what Denis proposed during our last developer meeting. For now I only set Study 1 to be public.

I added another overview displaying all studies, which the user is a member of. This table can be found on the user profile under the tab "My studies"  (URL: /user/[USERID]/studies)

**Comment by p-a-s-c-a-l** [comment]
> **Regarding "Better separation between prototype implementation and mock-ups"**
> 
> I have already done this for the tabs Table and Map, because the initialisation of the used components works different when the prototype tab is used.

@therter so maybe you could take care of the other Tabs/Steps as well?

**Comment by p-a-s-c-a-l** [comment]
I've resolved 'better separation between prototype implementation and mock-ups'

**Comment by p-a-s-c-a-l** [comment]
'better separation between study and GL-step tabs' is probably just a small CSS modification. This could be done Alejandro? I've invited him to join UI Team.

**Comment by p-a-s-c-a-l** [comment]
### Open Taxonomies' description in popups or inline (Study type, sector)

When you click on 'energy' (should be renamed to **E**nergy, btw), a popup should be opened

![grafik](https://user-images.githubusercontent.com/1788226/54191320-fadbf800-44b5-11e9-98c3-f8edc16bd366.png)

I modified the view to show the taxonomy terms inline but but this looks bad:

![grafik](https://user-images.githubusercontent.com/1788226/54192017-59ee3c80-44b7-11e9-97f7-ecf6bea448cb.png)

@DanielRodera maybe you can have a look and ask Alejandro to take care about 'better separation between study and GL-step tabs'?

**Comment by p-a-s-c-a-l** [comment]
I expect that pending issues have been fixed in the [new CLARITY Theme](https://github.com/clarity-h2020/clarity-theme/) which just has to be [activated and tested](https://github.com/clarity-h2020/clarity-theme/issues/1).
