### ISSUE TITLE
Data Package Views

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#47]
Please update the Data Package Views (*Data* Tabs in Study, HC, EE, ....) so that they they properly show the contents of the Data Package. 

![grafik](https://user-images.githubusercontent.com/1788226/51122125-73f20280-1819-11e9-895d-ccdc4231dd39.png)

Views should follow the Mock-Ups. E.g. in the Study View (https://csis.myclimateservice.eu/study/1/view/data) is is probably sufficient to show the general meta-data of the whole [data package](https://github.com/clarity-h2020/data-package/blob/master/docs/data-package-general.md), possibly with the link to all actual [Data Resources](https://github.com/clarity-h2020/data-package/blob/master/docs/data-package-resource.md). In The Data Tabs of the Module Steps, only the relevant Data Resources (e.g. only Hazard Resources in Hazard Tab) should be shown ([Example](https://csis.myclimateservice.eu/study/1/step/2/view/data)).

**Mock-Up:** Data Package Content for EE Step
![_ hazard _ data hazard info _data2](https://user-images.githubusercontent.com/1788226/53243070-01413600-36a7-11e9-846f-cabb40076a46.png)

**Comment by fgeyer16** [comment]
I added further fields now. But I have troubles to map the three Scenario lines to fields of the Data Package content type or content types referenced by it (like data set, analysis context and so on).

**Comment by p-a-s-c-a-l** [comment]
Any further progress here? The Data Tabs are quite important, they show the content of the Data Package relevant for the current GL-Step (e.g. for [HC-LE](https://csis.myclimateservice.eu/study/1/step/3/view/data)) . This is also where we reuse most of our [Taxonomies](https://github.com/clarity-h2020/docker-drupal/issues/14), so its  quite important for [v1](https://github.com/clarity-h2020/docker-drupal/milestone/2). 

@DanielRodera perhaps you could have a look at this? :o)

**Comment by DanielRodera** [comment]
> Any further progress here? The Data Tabs are quite important, they show the content of the Data Package relevant for the current GL-Step (e.g. for [HC-LE](https://csis.myclimateservice.eu/study/1/step/3/view/data)) . This is also where we reuse most of our [Taxonomies](https://github.com/clarity-h2020/docker-drupal/issues/14), so its quite important for [v1](https://github.com/clarity-h2020/docker-drupal/milestone/2).
> 
> @DanielRodera perhaps you could have a look at this? :o)

sure I will

**Comment by p-a-s-c-a-l** [comment]
The data package view looks really terrible with the [new theme](https://github.com/clarity-h2020/clarity-theme). E.g. no indication that the list of resources are clickable links, but underlined link are not clickable, no clear separation between fields, important fields are missing (references, path, ...), etc.

Any change to improve this?

![data](https://user-images.githubusercontent.com/1788226/63343233-c5351800-c34d-11e9-93af-279d49db1bc7.gif)

**Comment by DanielRodera** [comment]
Hi, @p-a-s-c-a-l, 

Thank you for the feedback. I will inform Alejandro about the issue and we will propose a solution for this.

**Comment by p-a-s-c-a-l** [comment]
> Thank you for the feedback. I will inform Alejandro about the issue and we will propose a solution for this

Any news on that? See also the related issue: https://github.com/clarity-h2020/clarity-theme/issues/7

**Comment by bullz** [comment]
I am working on it.
By the way. Is there any way to change names like this one:
"**HI_tropical-nights_rcp85_20110101-20401231_ensstd** "
to something **shorter**, or with **spaces** at least. because long names are very restricting for display options

**Comment by p-a-s-c-a-l** [comment]
Thanks. We had this discussion with layer names and field_title vs. field_name (now ckan_id) in data package resource. But I don't remember what the conclusion was and how the title should be formatted. @DenoBeno @maesbri any suggestions?

**Comment by patrickkaleta** [comment]
> I am working on it.
> By the way. Is there any way to change names like this one:
> "**HI_tropical-nights_rcp85_20110101-20401231_ensstd** "
> to something **shorter**, or with **spaces** at least. because long names are very restricting for display options

And that's probably not even the worst title in our system. Looking at the page for [Study 1](https://csis.myclimateservice.eu/study/1/step/2/view/data), I doubt that this page can be improved with CSS only, so we need to do something with those names.

> Thanks. We had this discussion with layer names and field_title vs. field_name (now ckan_id) in data package resource. But I don't remember what the conclusion was...

The Drupal-default title is was can be seen on the page now. `field_title` is currently not used anymore and supposed to be removed at some point. `field_name` is used for storing the CKAN ID.

**I see two possibilities:**
1) Use the [field_title](https://csis.myclimateservice.eu/admin/structure/types/manage/data_package_metadata/fields/node.data_package_metadata.field_title) in the resources, which we originally wanted to remove. I think maybe we could use this field as some sort of a "simplified title", which we could show everywhere, where there is not much space available
2) or we come up with a good naming convention for the `title` field. (Maybe in addition to Denis and Miguel @RobAndGo has an idea for short yet meaningful resource titles?)

**Comment by RobAndGo** [comment]
As a quick suggestion, one could modify the periods from:
- 20110101-20401231 to 2011-2040
- 20410101-20701231 to 2041-2070
- 20710101-21001231 to 2071-2100

One could also change:
- "_ensmean" to "_mean", 
- "_ensstd" to "_std" 
with the knowledge that these are referring to the mean and standard deviation over multiple models.

**Comment by patrickkaleta** [comment]
> As a quick suggestion, one could modify the periods from:
> 
> * 20110101-20401231 to 2011-2040
> * 20410101-20701231 to 2041-2070
> * 20710101-21001231 to 2071-2100
> 
> One could also change:
> 
> * "_ensmean" to "_mean",
> * "_ensstd" to "_std"
>   with the knowledge that these are referring to the mean and standard deviation over multiple models.

Thanks @RobAndGo , seems good to me. I would've guessed the meaning of "std" and "mean", but from what I saw it's also always described in the resource description. Probably another great help (for @bullz and all the users) would be to use spaces instead of underscores. @maesbri would that be possible or would this be in violation of the specifications?

**Comment by maesbri** [comment]
No problem with that as in drupal we are not using the "name" property anymore (if I recall correctly), only the "title", which is text free. 
With respect to the suggested changes, in fact we were requested to provide some more human-readable titles for the resources. I already did it some days ago for the Tx75p hazard indices.

**Comment by bullz** [comment]
![FireShot Capture 002 - Data - CLARITY CSIS - localhost](https://user-images.githubusercontent.com/160349/64676031-e385c380-d474-11e9-9df1-e8ac4c762c42.png)

Here there is an example of the improved look of the page, but the tabs are not working.
I have configured the jquery tabs system already integrated in Drupal. But I could use some help on where this items are generated, I mean the code for "**general, Data, Contexts**" tabs

**Comment by patrickkaleta** [comment]
@bullz yes, this looks now much better than before!

> Here there is an example of the improved look of the page, but the tabs are not working.
> I have configured the jquery tabs system already integrated in Drupal. But I could use some help on where this items are generated, I mean the code for "**general, Data, Contexts**" tabs

Sure, the tabs are generated by two views (one responsible for the tabs of the Study group and one responsible for the tabs in all the individual GL-steps) as a custom text field `Tab-links` with the help of a little Twig logic:
- [Study tabs](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_tabs_for_group/edit/block_1)
- [GL-step tabs](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_tab_for_content/edit/block_1)

**FYI**: The tabs in the GL-steps don't always have to be there (if there is no content for the tab, that tab is not displayed), but the order of the tabs is always the same ("Data" is after "Introduction", "Maps" after "Table" etc.)

**Comment by bullz** [comment]
I have uploaded to the clarity theme a new version.
For getting the new tabs work there are some changes needed in the view:
https://csis.myclimateservice.eu/admin/structure/views/view/rest_node/edit/rest_export_3 

the content of the **display** field now should be:

````
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">General</a></li>
    <li><a href="#tabs-2">Data</a></li>
    <li><a href="#tabs-3">Contexts</a></li>
  </ul>
  <div id="tabs-1">
             <div id="edit-group-general--content" class="panel-body panel-collapse collapse fade">
          <div class="field field--name-field-sources field--type-entity-reference ">
            <h4>sources</h4>
            <div class="field--items">
              {{ field_sources }}
            </div>
          </div>
          <div class="field field--name-field-contributors field--type-entity-reference ">
            <h4>contributors</h4>
            <div class="field--items">
              {{ field_contributors }}
            </div>
          </div>
        </div>  
  </div>
  <div id="tabs-2">
            <div id="edit-group-data--content" class="panel-body panel-collapse collapse fade">
          <div class="field field--name-field-format field--type-list-string ">
           <h4>format</h4>
             <div class="field--item">{{ field_format }}</div>
          </div>
            <div class="field field--name-field-mediatype field--type-list-string ">
              <h4>mediatype</h4>
              <div class="field--item">{{ field_mediatype }}</div>
            </div>
            <div class="field field--name-field-encoding field--type-list-string ">
              <h4>encoding</h4>
              <div class="field--item">binary</div>
            </div>
            <div class="field field--name-field-bytes field--type-decimal ">
              <h4>bytes</h4>
              <div class="field--item">{{ field_bytes }}</div>
            </div>
            <div data-quickedit-field-id="node/380/field_url/en/full" class="field field--name-field-url field--type-string-long ">
              <h4>path</h4>
              <div class="field--item">{{ field_path }}</div>
            </div>
          </div>
    
    
  </div>
  <div id="tabs-3">
              <div id="edit-group-contexts--content" class="panel-body panel-collapse collapse fade">  <div data-quickedit-field-id="node/380/field_temporal_extent/en/full" class="field field--name-field-temporal-extent field--type-entity-reference ">
            <h4>temporal_extent</h4>
            <div class="field--item">{{ field_temporal_extent }}</div>
          </div>
          <div class="field field--name-field-spatial-extent field--type-entity-reference ">
            <h4>spatial_extent</h4>
            <div class="field--item">{{ field_spatial_extent }}</div>
          </div>
          <div class="field field--name-field-spatial-resolution field--type-entity-reference ">
            <h4>spatial_resolution</h4>
            <div class="field--item">{{ field_spatial_resolution }}</div>
          </div>
          <div class="field field--name-field-grid-info field--type-entity-reference ">
            <h4>grid_info</h4>
            <div class="field--item">{{ field_grid_info }}</div>
          </div>
          <div class="field field--name-field-service-type field--type-entity-reference ">
            <h4>service_type</h4>
            <div class="field--item"><a href="/taxonomy/term/156" hreflang="en"></a></div>
          </div>
          <div class="field field--name-field-analysis-context field--type-entity-reference ">
            <h4>analysis context</h4>
            <div class="field--item">{{ field_analysis_context }}</div>
          </div>
        </div>
  </div>
</div>
````

**Comment by patrickkaleta** [comment]
> I have uploaded to the clarity theme a new version.

Great, I will update the View and test this tomorrow in my local instance and deploy it afterwards to the CSIS server (I'm guessing this hasn't been done yet?).

**Comment by patrickkaleta** [comment]
Changes made by @bullz are now on the CSIS server, but it doesn't look quite like shown in [your screenshot](https://github.com/clarity-h2020/docker-drupal/issues/47#issuecomment-530254719). 

I will continue the discussion for this specific view here: https://github.com/clarity-h2020/clarity-theme/issues/7

**Comment by DenoBeno** [comment]
> I am working on it.
> By the way. Is there any way to change names like this one:
> "**HI_tropical-nights_rcp85_20110101-20401231_ensstd** "
> to something **shorter**, or with **spaces** at least. because long names are very restricting for display options

Well, we *are* trying to replace tons of resources with one using variables. This will take some time, but see https://github.com/clarity-h2020/data-package/issues/47. This will make the names shorter too.

**Comment by p-a-s-c-a-l** [comment]
Main issue resolved.
