### ISSUE TITLE
Configure Geofield Module in Drupal

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/docker-drupal#48]
Moved here from csis (05.02.2019):
Add hazards and adaptation measures demo locations to Geofield map in Drupal.

**Comment by p-a-s-c-a-l** [comment]
This error occurs when saving an entity with geofield:

![grafik](https://user-images.githubusercontent.com/1788226/56042112-9329fe80-5d3a-11e9-94d1-4e1b3b4df86a.png)

**Comment by p-a-s-c-a-l** [comment]
Here is a [6 year old bug report](https://www.drupal.org/project/geophp/issues/1864302). :-/
