### ISSUE TITLE
Install Geofield Module in Drupal

### ISSUE THREAD

**Issue by Itsman-AT** [clarity-h2020/docker-drupal#49]
Moved here from csis (05.02.2019):
In order get the map vi.sualisation for hazards and adaptation measures installed, we need to install the Geofield module in Drupal.

**Comment by patrickkaleta** [comment]
@Itsman-AT 
the modules [Geofield Map](https://www.drupal.org/project/geofield_map) and [Geofield](https://www.drupal.org/project/geofield) (which is required by the Geofield Map module as a dependency) are available in the Drupal system.

Do you need any other additional modules?

**Comment by p-a-s-c-a-l** [comment]
@Itsman-AT can we close this issue?

**Comment by Itsman-AT** [comment]
Yes.
