### ISSUE TITLE
Install/enable modules 

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#5]
I think we will need this modules:

- Group
- Form mode manager
- view mode page
- json api
- json field
- colorbox
- colorbox load or
  - Colorbox field formatter
  - Field Group Colorb
- REST
- REST UI

Please use composer to install the modules since updating will be the easiest with composer (concerning dependencies ).

**Comment by p-a-s-c-a-l** [comment]
Installed the following modules using `composer require`

- [x] drupal/group
- [x] drupal/form_mode_manager
- [x] drupal/view_mode_page
- [x] drupal/jsonapi
- [x] drupal/json_field
- [x] drupal/colorbox 
- [ ] drupal/rest
- [x] drupal/restui

`drupal/rest`is not available, is it part of drupal core?

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 
The installed modules do not show up in the Drupal Admin UI, e.g. JSON modules are not found:

![grafik](https://user-images.githubusercontent.com/1788226/45074981-d0177e00-b0e5-11e8-986c-e1451703f176.png)

This is the output of `composer require drupal/jsonapi`:

```
Using version ^1.23 for drupal/jsonapi
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by p-a-s-c-a-l** [comment]
OK, the modules are now available in the Drupal Admin UI. [This](https://github.com/clarity-h2020/docker-drupal/issues/5#issuecomment-418614929) was probably just a [caching issue](https://github.com/clarity-h2020/docker-drupal/issues/6#issuecomment-418646595).

![grafik](https://user-images.githubusercontent.com/1788226/45082099-e4b14180-b0f8-11e8-9317-d6f94fbfde64.png)
