### ISSUE TITLE
Scenario Analysis Tab not shown

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#51]
The [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis) Tab in Risk and Impact Assessment GL-Step is not shown anymore. This is the filter configuration of the [view Mode for GL-Step (Content)](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_7):

![grafik](https://user-images.githubusercontent.com/1788226/53562723-6c30b800-3b52-11e9-84d9-593fe361e79b.png)

The following error is shown:
``
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "structure" LINE 6: ... ((group_content_field_data_node_field_data.gid = 'structure... ^: SELECT node_field_data.created AS node_field_data_created, node_field_data.nid AS nid, group_content_field_data_node_field_data.id AS group_content_field_data_node_field_data_id FROM {node_field_data} node_field_data INNER JOIN {group_content_field_data} group_content_field_data_node_field_data ON node_field_data.nid = group_content_field_data_node_field_data.entity_id AND group_content_field_data_node_field_data.type = :views_join_condition_0 INNER JOIN {node__field_field_eu_gl_methodology} node__field_field_eu_gl_methodology ON node_field_data.nid = node__field_field_eu_gl_methodology.entity_id AND node__field_field_eu_gl_methodology.deleted = :views_join_condition_1 AND (node__field_field_eu_gl_methodology.langcode = node_field_data.langcode OR node__field_field_eu_gl_methodology.bundle = :views_join_condition_3) WHERE (((node__field_field_eu_gl_methodology.field_field_eu_gl_methodology_target_id = :node__field_field_eu_gl_methodology_field_field_eu_gl_methodology_target_id)) AND ((group_content_field_data_node_field_data.gid = :group_content_field_data_gid)) AND ((node_field_data.nid = :node_field_data_nid))) AND ((node_field_data.status = :db_condition_placeholder_4) AND (node_field_data.type IN (:db_condition_placeholder_5))) ORDER BY node_field_data_created DESC NULLS LAST LIMIT 1 OFFSET 0; Array ( [:node__field_field_eu_gl_methodology_field_field_eu_gl_methodology_target_id] => 6 [:group_content_field_data_gid] => structure [:node_field_data_nid] => view [:db_condition_placeholder_4] => 1 [:db_condition_placeholder_5] => gl_step [:views_join_condition_0] => study-group_node-gl_step [:views_join_condition_1] => 0 [:views_join_condition_3] => gl_step ) 
``

**Comment by fgeyer16** [comment]
The name of the corresponding EU-GL term changed. So the view which creates the Tabs had no chance to know that this tab is needed. This is now corrected. The tab is shown again.

**Comment by p-a-s-c-a-l** [comment]
done, thanks!

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

`/admin/structure/views/view/view_mode_for_gl_step/edit/page_7` still shoes the following error:

``
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "structure" LINE 6: ... ((group_content_field_data_node_field_data.gid = 'structure... ^: SELECT node_field_data.created AS node_field_data_created, node_field_data.nid AS nid, group_content_field_data_node_field_data.id AS group_content_field_data_node_field_data_id FROM {node_field_data} node_field_data INNER JOIN {group_content_field_data} group_content_field_data_node_field_data ON node_field_data.nid = group_content_field_data_node_field_data.entity_id AND group_content_field_data_node_field_data.type = :views_join_condition_0 INNER JOIN {node__field_field_eu_gl_methodology} node__field_field_eu_gl_methodology ON node_field_data.nid = node__field_field_eu_gl_methodology.entity_id AND node__field_field_eu_gl_methodology.deleted = :views_join_condition_1 AND (node__field_field_eu_gl_methodology.langcode = node_field_data.langcode OR node__field_field_eu_gl_methodology.bundle = :views_join_condition_3) WHERE (((node__field_field_eu_gl_methodology.field_field_eu_gl_methodology_target_id = :node__field_field_eu_gl_methodology_field_field_eu_gl_methodology_target_id)) AND ((group_content_field_data_node_field_data.gid = :group_content_field_data_gid)) AND ((node_field_data.nid = :node_field_data_nid))) AND ((node_field_data.status = :db_condition_placeholder_4) AND (node_field_data.type IN (:db_condition_placeholder_5))) ORDER BY node_field_data_created DESC NULLS LAST LIMIT 1 OFFSET 0; Array ( [:node__field_field_eu_gl_methodology_field_field_eu_gl_methodology_target_id] => 6 [:group_content_field_data_gid] => structure [:node_field_data_nid] => view [:db_condition_placeholder_4] => 1 [:db_condition_placeholder_5] => gl_step [:views_join_condition_0] => study-group_node-gl_step [:views_join_condition_1] => 0 [:views_join_condition_3] => gl_step ) 
``

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 
that error is caused by Drupal's "Auto preview" function, which tries to display the result of the view, even though it is not initially provided with the necessary values for the contextual filters.

In the FE this view is always called with the necessary values, since they are part of the URL, so IMHO this is not critical. 

However, we could add a validation criteria to the contextual filter (my suggestion: put it on the ContentID contextual filter and check if the value is a valid GL-step ID. If not -> hide the view). I tested this on my local instance and no errors appeared on the edit-page of the view. Proposed views, where we could implement this:
- [viewmode for GL-stes](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/default)
- [Study Group tabs for steps](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_tab_for_content/edit/block_1)

@fgeyer16 
what's your opinion? Do you see any possible negative impact if we implement this?

**Comment by fgeyer16** [comment]
@patrickkaleta 
I do not see any draw backs, if we set the validation oft the defaauöt value.Testingsome changes will work by providing an real id to the contextual Filter.
Keeping the log table clean is not wrong as well.

**Comment by patrickkaleta** [comment]
Validation implemented as suggested in https://github.com/clarity-h2020/docker-drupal/issues/51#issuecomment-470504885.

**Comment by p-a-s-c-a-l** [comment]
Broken again: 
``
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig\Error\SyntaxError</em>: An exception has been thrown during the compilation of a template (&quot;Attribute &quot;name&quot; does not exist for Node &quot;Twig\Node\CheckToStringNode&quot;.&quot;) in &quot;themes/contrib/bootstrap/templates/node/node.html.twig&quot;. in <em class="placeholder">Twig\Environment-&gt;compileSource()</em> (line <em class="placeholder">797</em> of <em class="placeholder">/app/vendor/twig/twig/src/Environment.php</em>).``

**Comment by p-a-s-c-a-l** [comment]
[Never change a running system](https://www.drupal.org/project/drupal/issues/3039408): Updated to twig 1.38.2 bugfix release
