### ISSUE TITLE
JSON:API File Upload not working

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#54]
For [Report Generation](https://github.com/clarity-h2020/scenario-analysis/issues/3), I want to send screenshots taken from within the [MCDA App](https://github.com/clarity-h2020/scenario-analysis/) to the Drupal JSON:API. However, the [JSON:API documentation for posting binary file content](https://www.drupal.org/docs/8/modules/jsonapi/file-uploads) is non-existent / not very helpful: It points to the release notes and includes just a single example in [Allow creation of file entities from binary data](https://www.drupal.org/node/3024331).

According to this example (Flow 2), I have to make a POST request **'like so'** (?!):

```
POST /jsonapi/node/report_image/field_image HTTP/1.1
Content-Type: application/octet-stream
Accept: application/vnd.api+json
Content-Disposition: file; filename="filename.jpg"
```
However, `HTTP/1.1 405 Method Not Allowed` is returned, probably because `/jsonapi/node/report_image/field_image` doesn't exist although the field `field_image` does exist.

I don't use basic authentication as mentioned in the "[documentation](https://www.drupal.org/docs/8/modules/jsonapi/creating-new-resources-post)", but cookie and CSRF Token which **used to work** with the legacy REST API (now I get 403). :hurtrealbad: 

@fgeyer16 @patrickkaleta Any idea what's wrong here and where to find working examples for using the JSON:API? Otherwise I have to mess with the REST API which doesn't work either: [Files created with REST API are only temporary](https://github.com/clarity-h2020/docker-drupal/issues/27).

**Comment by p-a-s-c-a-l** [comment]
Trying to create a repo_image entity first by POST

```json
{
  "data": {
    "type": "node--report_image",
    "attributes": {
      "title": "NEW REPORT IMAGE",
      "field_comment": {
        "value": "curl posted report image entity",
        "format": "plain_text"
      }
    }
  }
}
```

to `/jsonapi/node/report_image/` results in the 'very helpful' error message:

`The website encountered an unexpected error. Please try again later.<br />* Closing connection 0`

In the logs you can find more info:

``Argument 1 passed to Drupal\\jsonapi\\Normalizer\\EntityReferenceFieldNormalizer::isInternalResourceType() must implement interface Drupal\\Core\\Entity\\EntityInterface, null given
``

This is a known issue: [JSON API POST 500 ERROR](https://www.drupal.org/project/jsonapi_file/issues/2980653) and the last comment refers again to [Allow creation of file entities from binary data](https://www.drupal.org/node/3024331).  :suspect:

**Comment by p-a-s-c-a-l** [comment]
Guess what? Even their [article example](https://www.drupal.org/docs/8/modules/jsonapi/creating-new-resources-post) isn't working. Seems the whole Drupal JSON/REST stuff is messed up beyond repair.

@fgeyer16 @p-a-s-c-a-l Are there other alternatives to the REST / JSON API for putting the report screenshots into the system?

**Comment by fgeyer16** [comment]
@p-a-s-c-a-l 
Did you try the [Legacy REST API](https://www.drupal.org/docs/8/core/modules/rest/javascript-and-drupal-8-restful-web-services) of Drupal? The json to Post a little different. WI think I tested it long time agoand it worked.

**Comment by fgeyer16** [comment]
> Guess what? Even their article example isn't working.

Sometimes I think this is an issue on Tutorials in the Web generally. Found some tutorial and it is not working.

**Comment by fgeyer16** [comment]
Sorry I missed the thing with the only temporary file on Image upload when I asked using the Legacy REST API.
Did you try out [this REST path](https://www.drupal.org/node/2941420) already? 

otherwise we can enable the file entity module and apply the patch which is mentioned in #27

**Comment by p-a-s-c-a-l** [comment]
> Did you try out [this REST path](https://www.drupal.org/node/2941420) already?

Getting closer:

``  Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\HttpException: "Destination file path is not writable" at /app/web/core/modules/file/src/Plugin/rest/resource/FileUploadResource.php line 230
``

Would be really helpful to know what the 'Destination file path' is.  Never heard of contextual error messages?

Once that file upload works, we have to create a report image entity, reference the uploaded file to it and add the report image entity to the step entity using the REST API because JSON:API is broken. 

What could possibly go wrong?

**Comment by p-a-s-c-a-l** [comment]
OK, after upgrading to JSON:API 2.x, I finally managed to upload a file with curl.

**Comment by fgeyer16** [comment]
What was your REST Call? The path looks like this:
`/file/upload/node/<content_type>/<image_field`

- In the drupal ui go to structure->content types-><<content_type>-> manage fields.
- edit the field <image field> 
- in the edit tab check 'File directory'
- exists the the directory /app/web/sites/default/files/<file directory> and is it writable for the webserver?

If this is the case we have to make the error message contextual ourselves.
open 
`/app/web/core/modules/file/src/Plugin/rest/resource/FileUploadResource.php` 
for edit and change line 230 from
`throw new HttpException(500, 'Destination file path is not writable');`
to
`throw new HttpException(500, $destination .'is not writable');`

I discussed with @patrickkaleta  if we should create our own endpoint to create a report image node.
Doing this all by the existing rest interface would need

1. REST call: post image get as respond the fid of the image
2. REST call post new report_image node with image_filed set to fid and source_step to the nid of current Step. get nid 
3. REST call: post nid to add the node to the Study 

Since 3 makes troubles as well with our own endpoint it would be possible to create the node and add it to the study with first REST call only. And we have full control that the created image is on the right place and is permanent.

**Comment by fgeyer16** [comment]
> OK, after upgrading to JSON:API 2.x, I finally managed to upload a file with curl.

Needed to long to write my reply :-)
Can you post the call here?

**Comment by p-a-s-c-a-l** [comment]
``
curl -v "http://xxx/jsonapi/node/report_image/field_image" -H "Pragma: no-cache" -H "Cookie: xxx=xxx" -H "Origin: http://xxx" -H "Accept: application/vnd.api+json" -H "X-CSRF-Token: xxx" -H "Content-Type: application/octet-stream" -H "Content-Disposition: file; filename=\"filename.png\"" -H "Cache-Control: no-cache" --data-binary @filename.png 
``

[more on OwnCloud](https://repository.atosresearch.eu/owncloud/index.php/apps/files?dir=%2FCLARITY%2FWP4%20Technology%20Support%2FT4.5%20Scenario%20Analysis%2C%20Decision%20Support%20and%20Reporting%20Generation%2Fcurl)

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/54191025-5f4a8780-44b5-11e9-9e81-f899f8719b3c.png)
