### ISSUE TITLE
Twins prototype requirements

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#55]
Last week, I started implementing a first prototype for the Twins in my local environtment using the [Geofield_map](https://www.drupal.org/project/geofield_map) and Geofield module.

So far, I have a new content type called "Twin" with the following fields:
-	Title
-	Summary 
-	Link to an external website
-	Type of twin (Hazard twin, ....idk what other types there might be in the future but for now I think it’s just hazards)
-	Involved hazards
-	Involved elements at risk
-	Geolocation (stores just the point as latitude and longitude)

@Itsman-AT Do we need anything else for now?

On the [Twins-tab](https://csis.myclimateservice.eu/study/1/step/2/view/twins) in the study this could then look something like this:
![prototype-for-twins](https://user-images.githubusercontent.com/42167036/54109032-cf85da00-43dd-11e9-8c77-1ff4c87c969f.png)

@Itsman-AT as discussed last week, we need a Google Maps API key, so that we can fully use the [Geofield_map](https://www.drupal.org/project/geofield_map) module. Let me know, once you have one.

**Comment by Itsman-AT** [comment]
@patrickkaleta : Thanky, looks good. I think we do not need more at the moment.

**Comment by patrickkaleta** [comment]
> @patrickkaleta : Thanky, looks good. I think we do not need more at the moment.

ok, I will implement this in the CSIS

**Comment by patrickkaleta** [comment]
I implemented the [entity type](https://csis.myclimateservice.eu/admin/structure/types/manage/twin/fields) and the [view](https://csis.myclimateservice.eu/admin/structure/views/view/twins) and configured the GL-step and its view to display the twins.

For now, I also deactivated the Twins-tabs for all other steps except the first step (Hazard Characterization), since they are not yet defined and not even the mock-ups exist for those twins.

**Comment by Itsman-AT** [comment]
> 
> 
> @Itsman-AT as discussed last week, we need a Google Maps API key, so that we can fully use the [Geofield_map](https://www.drupal.org/project/geofield_map) module. Let me know, once you have one.

@patrickkaleta : I sent you the Key via e-mail, please check, if it is working.

**Comment by patrickkaleta** [comment]
@Itsman-AT: the key works. I've added it to the CSIS site.

**Comment by p-a-s-c-a-l** [comment]
Here is the updated Twins data model (already implemented in CSIS Drupal): [Marketplace-Entities.svg](https://github.com/clarity-h2020/marketplace/blob/master/src/main/svg/Marketplace-Entities.svg)

@Itsman-AT Please discuss the Hazard Twins with @DenoBeno. I seems that the Hazard Twins idea has been abandoned.

**Comment by patrickkaleta** [comment]
> 
> @Itsman-AT Please discuss the Hazard Twins with @DenoBeno. I seems that the Hazard Twins idea has been abandoned.

I would appreciate a fast decision on this matter, since I'm currently working on a function to include these Twins (or whatever it's going to be in the end) into the final report (similar to the recently implemented [Report image functionality](https://github.com/clarity-h2020/docker-drupal/issues/46#issuecomment-482537744))

Locally, I already managed to establish a working prototype, which displays the available Twins below the Twins-Map and separates them into those who are already included (always shown on top) and the ones who are available (and could be included in the report). 
**Knowing whether this has to work only for Twins or Showcases or for both will save me quite some time implementing this.**
![included-nonincluded twins](https://user-images.githubusercontent.com/42167036/56201741-d8ec0d00-6041-11e9-9c70-31499c86021d.png)

**Comment by p-a-s-c-a-l** [comment]
Some improvements that should be implemented before [ECCA 2019](https://github.com/clarity-h2020/docker-drupal/milestone/4):

### Filter is applied on map only
The (Hazard) and type filter are applied on the map only, but not on the table

![grafik](https://user-images.githubusercontent.com/1788226/57849602-fb597d80-77db-11e9-99a3-65bb876e34c6.png)

### Twin Maps for additional EU-GL  Steps
We should add Twin Maps for the other EU-GL Steps and show Twin and Showcase Entities that are assigned to the respective step.

For Twin and Showcase Entities related to Elements at Risk (EE Step) and [Adaptation Options] (IAO Step)), we can show Elements at Risk and Adaptation Options filters, too.

### Avoid i18n duplicates
See https://github.com/clarity-h2020/marketplace/issues/1#issuecomment-493023784

**Comment by patrickkaleta** [comment]
> Some improvements that should be implemented before [ECCA 2019](https://github.com/clarity-h2020/docker-drupal/milestone/4):
> 
> ### Filter is applied on map only
> The (Hazard) and type filter are applied on the map only, but not on the table
> 
Filters are applied to the map and the table showing "Available Twins/Showcases". For the "Included in Study report" table I deactivated the filters on purpose, since IMO users would get confused if those filters would "remove" already selected Elements from their study again. But it's not a problem to change that and make the filters affect this table as well. 

> 
> ### Twin Maps for additional EU-GL Steps
> We should add Twin Maps for the other EU-GL Steps and show Twin and Showcase Entities that are assigned to the respective step.
> 
> For Twin and Showcase Entities related to Elements at Risk (EE Step) and [Adaptation Options] (IAO Step)), we can show Elements at Risk and Adaptation Options filters, too.
> 
That's the way it was intended. I've hidden the Twins-Tab on all others steps, because currently all existing Twins/Showcases are assigned to the "Characterize Hazard" Step, so the Twins-Tab would be completely empty on all other steps. I'll have a look at it tomorrow to see if some of the Twins/Showcases would better fit into another step.

Regarding the shown select filters I talked to Denis and he wants (for now) to only show the "select hazard" option to keep it simple and not confuse the users. I therefore deactivated the "Select Type" option. 

> ### Avoid i18n duplicates
> See [clarity-h2020/marketplace#1 (comment)](https://github.com/clarity-h2020/marketplace/issues/1#issuecomment-493023784)

Done, as mentioned in this [comment](https://github.com/clarity-h2020/marketplace/issues/1#issuecomment-493045196).

**Comment by p-a-s-c-a-l** [comment]
> Filters are applied to the map and the table showing "Available Twins/Showcases".

You are right, it seems to work - but not very reliably. If you filter by "heat" and then by "flood" both tables disappear:

![twins](https://user-images.githubusercontent.com/1788226/57906771-6ad27a00-787b-11e9-91b1-6026f87b3b8d.gif)

>  For the "Included in Study report" table I deactivated the filters on purpose, since IMO users would get confused if those filters would "remove" already selected Elements from their study again. 

You're right, the filter should be applied to the second table only.

**Comment by patrickkaleta** [comment]
> > Filters are applied to the map and the table showing "Available Twins/Showcases".
> 
> You are right, it seems to work - but not very reliably. If you filter by "heat" and then by "flood" both tables disappear:

Strange, the tables disappear after the second time filter are applied (no matter which filters are used). Those filters are not custom-made but the ones provided by default by the Drupal Views. So probably it's just some misconfiguration, I'll check that.

**Comment by patrickkaleta** [comment]
### Grouping Twins/Showcases into the EU-GL Steps
I had a look at the currently available Twins/Showcases (10+1) and grouped them by the most relevant EU-GL step. For the Studis we now have Twins-Maps shown for the following 4 EU-GL Steps:

#### [Hazard characterization](https://csis.myclimateservice.eu/study/1/step/2/view/twins):
- 2003 European heat wave
- 2013 Sardinia floods
- Avalanche - Erdlach/Rax
- Campania Region Landslides
- **!!!** Heat Wave Index and Hazards in Vienna
- **!!!** Severe Wind Chorvatsky Grob

#### [Hazard characterization - Local effects](https://csis.myclimateservice.eu/study/1/step/3/view/twins):
- Heavy rain hazard map for Wuppertal

#### [Exposure Evaluation](https://csis.myclimateservice.eu/study/1/step/83/view/twins):
- European Drought Observatory
- Fire Danger in Europe

#### [Adapt. Opt. Identification](https://csis.myclimateservice.eu/study/1/step/445/view/twins):
- Airlite C02 absorbing paint ("adaptation option at work" example)
- Drought Management Planning Policy: From Europe to Spain

@Itsman-AT could you please have a look and decide if this is reasonable or if you would change some of them? Also I prefixed some of the Twins with "**!!!**" - those have little to no description, so it would be great if this could be fixed.
Last question: Any idea/plans on when we can expect some new Twins?

**Comment by patrickkaleta** [comment]
> > Filters are applied to the map and the table showing "Available Twins/Showcases".
> 
> You are right, it seems to work - but not very reliably. If you filter by "heat" and then by "flood" both tables disappear:

This bug is fixed now and tables stay visible after applying filters multiple times. Apparently Drupal's Contextual filters can run into problems when using Exposed filters and AJAX. Changing the Contextual filter's parameters was the solution.

**Comment by p-a-s-c-a-l** [comment]
@patrickkaleta Now it seems that showcases are missing on map and in table.

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l after having a look at all twins/showcases I moved some of them into different tabs (by setting the `workflow_step` field). So I moved the Heavy Rain in Wuppertal into the Hazards local effects tab (sorry if I didn't make it clear enough before). But if you think it should rather stay in the Hazards tab, I can move it back.

The second showcase cids GUP-MV is shown on the Exposure tab in the map and in the table (at least for me thats the case).

**Comment by p-a-s-c-a-l** [comment]
``
The Google Maps Platform server rejected your request. This IP, site or mobile application is not authorized to use this API key. Request received from IP address xxxxxxxxx, with referer: https://maps.googleapis.com/maps/api/staticmap?size=650x400&scale=1&zoom=5&language=en&maptype=roadmap&markers=color:0xFF0000|size:normal|59.333759%2C18.074999&sensor=false&key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
``

at https://csis.myclimateservice.eu/node/1287

@Itsman-AT Can you please check what's going on? Quota exceeded, wrong key?

**Comment by Itsman-AT** [comment]
> @Itsman-AT Can you please check what's going on? Quota exceeded, wrong key?
I will check it now.

**Comment by Itsman-AT** [comment]
First find: Quota does not seem to be exceeded: 

>  Free trial status: €251.05 credit and 57 days remaining - with a full account, you'll get unlimited access to all of Google Cloud Platform.

**Comment by Itsman-AT** [comment]
Hm, for me the above link works with the Google Maps API key:

![grafik](https://user-images.githubusercontent.com/41750112/72341537-cf73fc00-36ca-11ea-88a2-946f9ddeae80.png)

**Comment by Itsman-AT** [comment]
Although there seem to have been errors in the past:

![grafik](https://user-images.githubusercontent.com/41750112/72341628-fe8a6d80-36ca-11ea-8755-4a83087e5dca.png)

and I do not know what this graph means:

![grafik](https://user-images.githubusercontent.com/41750112/72341671-17931e80-36cb-11ea-8fd1-27bac98bdffc.png)

**Comment by Itsman-AT** [comment]
I am investigating on the 100% error value.

**Comment by p-a-s-c-a-l** [comment]
Works in _Chrome. Probably a firefox issue. They added a lot of tracking protection functionality lately.

 > 57 days remaining

O.K. And what happens on day 58? :-)

**Comment by Itsman-AT** [comment]
> O.K. And what happens on day 58? :-)

AIT DRC would have to pay the bill :-) - not a good solution ;-)

**Comment by p-a-s-c-a-l** [comment]
IMHO this is revolved and can be closed?

**Comment by Itsman-AT** [comment]
> IMHO this is revolved and can be closed?

@p-a-s-c-a-l : Yes, please close the issue. We will handle this AIT internally.

**Comment by Itsman-AT** [comment]
@DenoBeno : Did you already create a DSS Google Maps Billing Account for Clarity? The Key expired now which is unfortunate. Can I be of any help?
