### ISSUE TITLE
Enable HTTPS URLs

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#57]
Although CSIS is served via HTTPS through [our nginx reverse proxy](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion) (X-forwarded headers is set), Drupal does not recognise this:

![grafik](https://user-images.githubusercontent.com/1788226/54427240-2fe88480-471a-11e9-82ba-e66b4746a113.png)

In consequence, all URIs in JSON responses point to HTTP instead of HTTPS:

![grafik](https://user-images.githubusercontent.com/1788226/54427455-d3d23000-471a-11e9-99ae-861c955c806d.png)

While nginx redirects all request to HTTP to HTTPS (301), this doesn't work when a JS Client parses the JSON and makes a HTTP request first because of the wrong HTTP URI: The browser will throw a mixed content error.

There are some issues that deal with the problem:
- [Option to force URLs to return HTTPS instead of HTTP](https://www.drupal.org/project/drupal/issues/2842702)
- [Forcing to HTTPS](https://www.drupal.org/forum/support/post-installation/2018-04-15/forcing-to-https)
- [Enabling HTTP Secure (HTTPS)](https://www.drupal.org/https-information)

But there is no 'solution' that actually works in our current setup (Apache PHP Drupal behind ngnix reverse proxy).

**Comment by fgeyer16** [comment]
Just to be sure how it works:

1. The request goes to nginx
2. nginx is responsible for the ssl stuff 
3. nginx forward the request to the apache in the docker-container or more specific: ngnix requests the page at docker (=apache) and send this response to the browser
Is this correct so far? 

I checked apache config in the docker container and it only listens on port 80 (http). So ngnix requests the data at port 80 from docker?
I suspect nxinx has to perfom the request to the docker by https as well.

I already half configured the ssl conf for apache, but I am not sure how to handle the part with the certificates.

**Comment by p-a-s-c-a-l** [comment]
There is no need to encrypt traffic between the internal Apache web server and the outbound proxy. Apache needs to serve HTTP on the internal interface only.  The outbound nginx proxy takes care about certificate handling, etc. So it is just a matter of telling Drupal that the pages are outbound served via https.

**Comment by fgeyer16** [comment]
I am no expert on nginx but In nginx configuration (conf.d/default.conf)  line 40:

> proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;

shouldn't it be 

> proxy_set_header  X-Forwarded-Proto $scheme

?
I interpret 

> map $http_x_forwarded_proto $proxy_x_forwarded_proto {
>   default $http_x_forwarded_proto;
>   ''      $scheme;
> }

on the start of the file, that $proxy_x_forwarded_proto is set if nginx is behind a reverse Proxy. 
Otherwise I need access to apaches log files if there are any.  Who can give me access to them or send me the one from today? Just to be sure the headers are set properly.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 OK, if set the X-Forwarded-Proto header in [vhost.d/csis.myclimateservice.eu](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/blob/clarity/data/vhost.d/csis.myclimateservice.eu)

You can access the apache logs via: `docker logs --since 5m -f csis-drupal`

But there are still 'http' URLs in the JSON. So IMHO this a Drupal issue.

**Comment by fgeyer16** [comment]
I appended the X-Forwarded, X-Forwarded-proto and X-Forwarded-For headers of a request to the apache log of drupal-csis
, and it seems, that only the X-Forwarded-For header exists.
 ![Bildschirmfoto von »2019-04-15 08-37-00«](https://user-images.githubusercontent.com/25331450/56112766-50477100-5f5c-11e9-8291-ee6bc415f4fe.png)

**Comment by p-a-s-c-a-l** [comment]
The log doesn't show any headers.

**Comment by fgeyer16** [comment]
These are the request headers Drupal sees:

```
SymfonyComponentHttpFoundationHeaderBagObject([headers:
	protected ] => Array(
		[authorization] => Array(
			[0] =>
		) [x - forwarded -
		for ] => Array(
			[0] => 217.149.167.232
		) [x - forwarded - host] => Array(
			[0] => csis . myclimateservice . eu:
				443
			) [x - forwarded - server] => Array(
				[0] => csis . myclimateservice . eu
			) [host] => Array(
				[0] => csis . myclimateservice . eu
			) [connection] => Array(
				[0] => close
			) [upgrade - insecure - requests] => Array(
				[0] => 1
			) [user - agent] => Array(
				[0] => Mozilla / 5.0(X11;
				Linuxx86_64) AppleWebKit / 537.36(KHTML, likeGecko) Chrome / 73.0.3683.88Safari / 537.36Vivaldi / 2.4.1488.36
			) [accept] => Array(
				[0] => text / html,
				application / xhtml + xml,
				application / xml;
				q = 0.9,
				image / webp,
				image / apng, * /*;q=0.8 ) [referer] => Array ( [0] => https://csis.myclimateservice.eu/study/1/view/intro ) [accept-encoding] => Array ( [0] => gzip, deflate, br ) [accept-language] => Array ( [0] => de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7 ) [cookie] => Array ( [0] => SESS7a689a227408b9e8f3b5db4bbea62abf=u9wNNCzOqlz84ucki6ZBKUEE7FqleZsP5veplvw7Tvo; sf_redirect=%7B%22token%22%3A%2277a424%22%2C%22route%22%3A%22system.modules_uninstall%22%2C%22method%22%3A%22POST%22%2C%22controller%22%3A%22controller.form%3AgetContentResult%22%2C%22status_code%22%3A303%2C%22status_text%22%3A%22See%20Other%22%7D ) [x-php-ob-level] => Array ( [0] => 0 ) ) [cacheControl:protected] => Array ( ) )
```
even there no X-Forwarded-proto header

**Comment by fgeyer16** [comment]
I am not able/allowed to change the vhost.d of nginx. Can we try to change
`proxy_set_header X-Forwarded-Proto https;`
to
`proxy_set_header X-Forwarded-Proto "https";
`
?
like in 
```
if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
}
```

**Comment by p-a-s-c-a-l** [comment]
OK. Changes applied in [vhost.d/csis.myclimateservice.eu](https://github.com/clarity-h2020/docker-compose-letsencrypt-nginx-proxy-companion/blob/clarity/data/vhost.d/csis.myclimateservice.eu).

**Comment by fgeyer16** [comment]
So now the header is there, the settings page still reads http but can you test what happens on REST calls?

**Comment by therter** [comment]
The REST calls still delivers http links

**Comment by p-a-s-c-a-l** [comment]
Replaced proxy ip in `$settings['reverse_proxy_addresses'] = array(xxx.xxx.xxx.xxx);` with `$settings['reverse_proxy_addresses'] = array($_SERVER['REMOTE_ADDR']);`

JSON:API delivers now HTTPS Links.
