### ISSUE TITLE
Scenario Selection UI

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#58]
We need some selection boxes (probably in study/context or in HC-LE) to let the user choose
- The (3?) Hazard Events used for calculation of the impact scenario (they might be pre-chosen in the data package, so user wouln't be able to change the selection)
- ~The time period used for calculation of the impact scenario (currently we have only historical events in the reference data package, 3 future times periods will b made available)~
- ~the RCP used for the calculation of the impact scenario (for future climate we'll get 3 RCPs for each time period)~

@humerh @bernhardsk 
This information is then saved at the level of the GL step object and then sent as request parameters to EMIKAT REST API for calculation of RA/IA. The request parameters may include for example the unique ids of the respective HC-LE input layers for the selected time period and RCP as well as IDs of the hazard events but only if there are more than 3(?) representative pre-selected events in the HC-LE layers.

**Comment by p-a-s-c-a-l** [comment]
@humerh @bernhardsk any opinions on this topic?

**Comment by p-a-s-c-a-l** [comment]
@humerh @bernhardsk any opinions on this topic?

**Comment by humerh** [comment]
I do not know, what the UI of CSIS for selecting the Scenario will look like.
I will try to describe the functionality of selecting the Hazard Events, which are "relevant" or typically for a specific project area:

1. Create new study and study area

2. The "middle point" of the study area should be used for selecting the relevant events for a study. EmiKat will implement the tables for "Heat Wave Hazard Events for Europe" (see discussions in 
https://github.com/clarity-h2020/csis/issues/57

3. Emikat will implement a possibility (REST-Interface) to make a query for the current "Study" with the input paramters: rcp-scenario, time-periode and the results will be 3 Hazard-Events:
    
- "Frequent" (Probability = 1.0; yearly event),
-  "Occasional" (Probability = 0.2; 1 in 5 year event),
-  "Rare" (Probability = 0.05; 1 in 20 year event)

This names of Events can be used for filtering results (IMPACT, ...) from EmiKat.

**Comment by p-a-s-c-a-l** [comment]
OK, we'll allow the user to ~select one RCP and one time period~ **one event from the future** for comparison against the baseline scenario. This will become our basis for adaptation scenarios. 

The choice [should be made](https://github.com/clarity-h2020/docker-drupal/issues/72#issuecomment-504327557) in the HC or HC-LE tab, depending on what we show in the HC-LE table and sent to the [EMIKAT RA/IA API](https://github.com/clarity-h2020/emikat/issues/9).

**Comment by p-a-s-c-a-l** [comment]
Duplicate of https://github.com/clarity-h2020/csis/issues/109
