### ISSUE TITLE
Module Filter and Admin Toolbar not working

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#6]
The module filter and Admin Toolbar are not working. Maybe there is some confusion for drupal where to find files (I assume some js thing)

Since this will affect other modules as well we have to research and fix this.

**Comment by p-a-s-c-a-l** [comment]
I cannot reproduce the problem with the admin toolbar, for me it's working:

![grafik](https://user-images.githubusercontent.com/1788226/45073179-7fe8ed80-b0de-11e8-8bf5-cabe5b2d14a4.png)

But I performed a modules update with `composer update` in 4f3cdfe before installing new modules for #4. So perhaps that fixed the issue with the toolbar.

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 

How can I check if the filter module is working or not? Is this the module?:

![grafik](https://user-images.githubusercontent.com/1788226/45074251-0acbe700-b0e3-11e8-8e24-51c4ae59aa6d.png)

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l 

No the filter module should change the look of the modules overview page (/admin/modules). If it's installed and working the page should look like shown here (https://www.drupal.org/project/module_filter) in the first picture.

**Comment by p-a-s-c-a-l** [comment]
OK. Indeed, this filter did not work: JavaScript error: `ModuleFilter.localStorage is undefined`. 

Clearing the Drupal Cache under admin/config/development/performance resolved the issue. I assume this re-generated the aggregated JS and CCS files in `/drupal-data/web/sites/default/files`.

![grafik](https://user-images.githubusercontent.com/1788226/45081275-24772980-b0f7-11e8-9c8f-c996da30b60d.png)

**Comment by p-a-s-c-a-l** [comment]
NB: During development, we should disable the bandwidth optimization options. This will make debugging JavaScript files a lot easier.

**Comment by fgeyer16** [comment]
Yes during Development the css and js aggregation is better to switched of. I did this now.
