### ISSUE TITLE
Fixing invalid JSON formatting for nested REST Views 

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#65]
Some time ago we discussed the possibility to define REST Views ([here](https://github.com/clarity-h2020/csis/issues/22#issuecomment-444463061)), which would allow to provide only the desired fields of a content type and even fields of referenced entities by using nested REST Views (idea was to minimalize number of needed REST calls and the size of the payload). This could now be interesting e.g. for sharing content between CSIS and the marketplace via REST ([issue](https://github.com/clarity-h2020/marketplace/issues/13)).

Nesting REST Views can be achieved by including a REST view inside another REST view. But the problem was that this nested view wasn't properly formatted (a problem in the Core REST module). Example below shows wrong formatting for `field_analysis_context`, which is another nested View. 
![nested-wrong-format](https://user-images.githubusercontent.com/42167036/56898968-9b03d580-6a92-11e9-926a-9928ba7e597b.png)
<br>
@fgeyer16 found a [module](https://www.drupal.org/project/rest_export_nested), which fixes this bug and creates proper JSON objects with nested REST Views. This module is currently only available in Alpha, but I tested it locally and it seems to be working as expected (even with double-nested Views :-) ).
![nested-right-format](https://user-images.githubusercontent.com/42167036/56899665-4b260e00-6a94-11e9-8753-5ecbf9026b1f.png)

**Comment by p-a-s-c-a-l** [comment]
Is this module now used / still needed in our public CSIS  instance?

**Comment by patrickkaleta** [comment]
It is currently not used nor installed and not needed as long as all external services are ok with making multiple REST calls to get what they want. Personally, I'd like to avoid using it since it's still alpha, not very actively developed and not used on many sites.
