### ISSUE TITLE
Improving Taxonomy structures

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#67]
At the moment the structure is not consistent. Taxonomy [Elements at Risk](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/elements_at_risk/overview) currently has 3 el. at risk (as root terms), each containing its individual vulnerability-classes & damage-classes, but there is also a separate [Damage class](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/damage_classes/overview) taxonomy containing for each element at risk all their damage classes. (**Which of those taxonomies should we use for the damage classes?**)

On the other hand we have the [Hazards ](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/hazards/overview)taxonomy, which has not only the hazards itself, but also the hazard indexes. 
**Question for both taxonomies (Hazards, Elements at risk) is whether we want to include this additional, related information (vulnerability classes, damage classes, hazard indexes) in those 2 taxonomies or if we should exclude them and create separate taxonomies for each of them?**

Structure of the taxonomy terms impacts how content is filtered in Views and also how those terms are displayed in forms when creating or updating content, which references taxonomy terms. A way how to format/filter taxonomy terms in forms is shown in this [issue](https://github.com/clarity-h2020/docker-drupal/issues/66).

**Comment by p-a-s-c-a-l** [comment]
IMHO the nested taxonomy structure makes sense as the structure reflects the relationships between e.g. the damage classes and elements at risk. The Damage class taxonomy seems redundant and should be removed.

**Comment by patrickkaleta** [comment]
I updated title and description of the Damage classes taxonomy to indicate that this one should not be used in any way. I'll check for any possible side-effects of removing this taxonomy in my local instance and then proceed to removing it from the CSIS site.

**Comment by patrickkaleta** [comment]
As it turned out in other places, removing Element types (content types, taxonomies) can have unexpected side-effects. So, the [Damage Classes](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/damage_classes/overview) taxonomy title was updated with a `REMOVE`, so that we can later remove it when we find the time to completely clean up the Drupal system.
