### ISSUE TITLE
Create Taxonomies

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#7]
We need some Taxonomies:

- country
   - beside the name this taxonomy should have a geofield so that we can store the boundaries of the country
- Sector subsectors will be child terms of the sector term 
- maybe we should make the study mode a Taxonomy as well?

**Comment by p-a-s-c-a-l** [comment]
Related to [this action](http://cat.clarity-h2020.eu/content/building-blocks-datasets-and-models-test-cases). AFAIR @bernhardsk had a look at different sector taxonomies. Example: [Worldbank Project Sectors](https://climatescreeningtools.worldbank.org/general/screening-tool-overview)

**Comment by p-a-s-c-a-l** [comment]
For country polygons we could use [world.geo.json](https://github.com/switchonproject/world.geo.json) or [world-atlas](https://github.com/mbostock/world-atlas). However, GeoJSON's [standard projection](https://macwright.org/2015/03/23/geojson-second-bite.html#projections) is **ESPG:4326** and AFAIK @humerh wanted to use **ETRS89** for the [processed data](https://github.com/clarity-h2020/csis/issues/20). Moreover, some background layers (public OSM Tile Layers) may use **EPSG:3857**, so we have to make sure that the **Map Component** can handle different projections or that the layers are re-projected on [server side](https://github.com/clarity-h2020/docker-geonode)!

**Comment by helllth** [comment]
We use the https://kartena.github.io/Proj4Leaflet/ project in other solutions to display data in different projections. 


There is this example on the page: 
GeoJSON example displaying a GeoJSON with coordinates in EPSG:26915 on a Leaflet map with spherical mercator projection 

You just have to add the projection info to your geojson file.

**Comment by p-a-s-c-a-l** [comment]
@maesbri Select and enter the economic sectors taxonomy

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16: Import countries taxonomy, at least name and county code. Optionally add geofield with bbox or polygon as geofield to the countries taxonomy and import polygons from https://github.com/clarity-h2020/docker-drupal/issues/7#issuecomment-419022715

**Comment by p-a-s-c-a-l** [comment]
Taxonomies are created, but content is still missing:

![grafik](https://user-images.githubusercontent.com/1788226/48185861-4034c100-e32e-11e8-934a-327e6c40ce59.png)

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera select a sector taxonomy (e.g. EIB, world bank, ...) and add to system. 

Sources: 
- http://cat.clarity-h2020.eu/outreach/information-sources
- http://www.eib.org/attachments/fi/eib_hleg.pdf

**Comment by DanielRodera** [comment]
> @maesbri Select and enter the economic sectors taxonomy

I added the sectors taxonomy

**Comment by p-a-s-c-a-l** [comment]
Done. If anything else is missing it can be discussed in https://github.com/clarity-h2020/docker-drupal/issues/14
