### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#71]
File upload not working any more! You can select a file, but nothing happens (no upload), even if you save the entity: 
![grafik](https://user-images.githubusercontent.com/1788226/58178047-bd5dcd00-7ca5-11e9-9e52-bbff878a5549.png)

**Comment by p-a-s-c-a-l** [comment]
Drupal does not show any error message if file size exceeds the maximum size (currently 2MB) but silently refused to upload the image.

**Comment by fgeyer16** [comment]
On which form/page Drupal did not complain about to big files? It schoul and normally does.
