### ISSUE TITLE
"composer install" downgraded several modules on production site only

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#73]
I just added two patches to the composer.json as shown in this [tutorial](https://punkt.de/de/blog/2017/patchen-mit-composer.html) and ran "composer install" command (all from within the docker container). Patches were applied, however this also lead to several modules being downgraded (also Drupal itself downgraded from 8.6.17 to 8.6.16).

![install-downgrade](https://user-images.githubusercontent.com/42167036/60010477-2b682c00-9678-11e9-8204-44e036dbd40e.png)

I first tested this locally with the current version of the system and all went as expected. Not sure why this happenend and how it would be best to proceed now?

**Comment by p-a-s-c-a-l** [comment]
Hm, did you try `composer update` afterwards?
Downgrading modules, especially Drupal core, is not an option as we need to apply the latest security updates.

**Comment by patrickkaleta** [comment]
@p-a-s-c-a-l thanks, looks like all downgrades have been reverted now, while patches are still active. I guess, I'll use the `composer update` command next time when applying new patches.
