### ISSUE TITLE
Check content of tag field in datapackage

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#76]
Please check if the tag field in the resources  contains all data from its different predecessors fields. It seems that the Hazard and Exposure data are missing.

**Comment by maesbri** [comment]
Only resources r1 and r15 (in Naples data package) were updated according to the new properties. The rest of resources are still pending.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/data-package/issues/18
