### ISSUE TITLE
Broken CSS for select lists

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#79]
Somebody installed the [Chosen ](https://www.drupal.org/project/chosen) module, which allows to search through select lists with more than 20 elements. It is a useful feature, but currently breaks the whole select list making them completely useless (screenshot taken for Solution offers overview page):
![chosen-CSS-bug](https://user-images.githubusercontent.com/42167036/60796016-fb875100-a16c-11e9-9453-c672b9cb22b3.png)

Applying the default theming for this module in its [configuration](https://csis.myclimateservice.eu/admin/config/user-interface/chosen) (chose per theme options) fixes the problem, but the visual appearance doesn't quite match our CSIS theme.

**I suggest to add the necessary styling to the new proposed CSIS theme, so that we can use this module.** @maesbri could you please inform Alejandro about this and maybe even add him to the GIT repository as well, so we can assign issues directly to him?

Also, please test newly installed modules to avoid such unwanted side-effects.

**Comment by p-a-s-c-a-l** [comment]
The mentioned styling has to be implemented by @bullz in https://github.com/clarity-h2020/clarity-theme

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/60800617-cc291200-a175-11e9-92cd-745d8b20c94c.png)

BTW, is there any change to limit the country selection to just one.? The field_country is unlimited, which is an error. But changing this by deleting and recreating the field would cause to many changes in other parts of the system:

![grafik](https://user-images.githubusercontent.com/1788226/60801000-76a13500-a176-11e9-8d9c-eeae3c52a5a4.png)

**Comment by patrickkaleta** [comment]
> BTW, is there any change to limit the country selection to just one.? The field_country is unlimited, which is an error. But changing this by deleting and recreating the field would cause to many changes in other parts of the system:
 
Changing the cardinality and limiting this field to just one value should work as long as there are no entities with more than 1 element in that field.
The problem is that **Solution offers** are using the exact same field for listing all the countries, where they can be applied. Here it makes sense to allow multiple countries (also the case for the CIDS solution)

I believe the easiest solution is to remove that field from the Solution offer group (since it is not going to have so many effects on the system) and create a new one only used by Solution offers. Then the country field in the Studies can be limited to just one element. 

I can make those changes in the afternoon.

**Comment by patrickkaleta** [comment]
Solution offers now have a `available countries` field, where unlimited numbers of countries can be added. The original `country` field for Studies now allows only one value.

**Comment by patrickkaleta** [comment]
Regarding the usage of the [Chosen ](https://www.drupal.org/project/chosen) module, I just noticed that we cannot simply apply it to all select fields, since that would break the dynamic selection of available cities based on the country in our Study groups.
**Solution**: we have to explicitly set in the [configuration ](https://csis.myclimateservice.eu/admin/config/user-interface/chosen) of the Chosen module, for which elements it should be applied.

**Comment by DenoBeno** [comment]
is this fixed now?

**Comment by patrickkaleta** [comment]
> is this fixed now?

If you are talking about the broken CSS mentioned in my [first comment](https://github.com/clarity-h2020/docker-drupal/issues/79#issue-465132840) **than yes, this is fixed now.** 

Regarding this [comment](https://github.com/clarity-h2020/docker-drupal/issues/79#issuecomment-509637920), there is nothing to fix. The "Dependent fields" in Business rules only work on default `select` elements. Therefore we cannot apply the Chosen module per default on all `select` elements, but instead have to explicitly list them in the [configuration](https://csis.myclimateservice.eu/admin/config/user-interface/chosen) for this module.

So IMO this issue can be closed.
