### ISSUE TITLE
Create Group type study

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#8]
Each study will be a group: In this way we can easily maintain the team.
Fields for the moment:
- acronym short name -> text
- name -> text
- study goal -> long text (without summary)
- study mode -> Taxonomy  reference
- sector -> Taxonomy reference
- country -> Taxonomy reference
- area -> geo field

**Comment by p-a-s-c-a-l** [comment]
Basic Group Type available: https://csis.myclimateservice.eu/admin/group/types/manage/study

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

How are the different steps of the complete process represented in terms of user interfaces and types / entities? 

- Study Context Definition (this is current the [display of a study group entity](https://csis.myclimateservice.eu/group/1))
- Study Area Selection
- Data Package Selection
- EU-GL Steps
  - HC
  - EE
  - ...
- [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis)
- Report Generation

In particular how can we perform the selection of the [study area](https://github.com/clarity-h2020/docker-drupal/issues/22) on a **separate page** as shown in the [Mock-Up](https://user-images.githubusercontent.com/1788226/45550886-8c7eeb80-b82c-11e8-8a7a-e38e6aa2bb34.png)? When we add the respective *study_area* field to [Study Group Type](https://csis.myclimateservice.eu/admin/group/types/manage/study) it will appear on the [Study Context](https://csis.myclimateservice.eu/group/1) page (see [Mock-Up](https://user-images.githubusercontent.com/1788226/45550886-8c7eeb80-b82c-11e8-8a7a-e38e6aa2bb34.png)).

**Comment by p-a-s-c-a-l** [comment]
done
