### ISSUE TITLE
Adding new Studies in the CSIS

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#83]
### "Create new Study" button
I added a new button to create a new Study, which is displayed under all tables listing currently available studies (just for now this button is only visible for admins). It shows a simplified form (following the approach we choose for data packages and resources) asking for:
- Title
- Short name
- Study goal
- Study type

All remaining fields (Country, Sector, data package, ...) can then be filled in later in the appropriate tabs of the study group.

### Updating business rules for automatically creating GL-step entitites
Once user creates a new study, Business rules create the necessary 8 GL-steps in the background and prefill them with the needed data. I updated the corresponding rules to include the Map & Table component and the Scenario Analysis app just like it is currently configured for the first study.

**1) HC:** 
Map app: Characterise Hazard initialised React Map (NodeID: 118)
Table app: Characterise Hazard initialised React table (NodeID: 121)

**2) HC-LE:** 
Map app: Hazard Local Effects initialised React Map (116)
Table app: Hazard Local Effects initialised React table (124)

**3) EE:** 
Map app: Evaluate Exposure initialised React Map (114)
Table app: Exposure initialised react table (122)

**4) VA:** 
Map app: Analyse Vulnerability initialised React Map (120)
Table app: Vulnerability initialised React table (126)
Twins-tab hidden

**5) RIA:**
Scenario Analysis Application: Scenario Analysis (21) 
Map app: Assess Risk and Impact initialised React Map (105)
Table app: Risk and Impact initialised React table (106)
Twins-tab hidden

**6) AOI:** 
Table app: Adaptation Options initialised React table (384)

**7) AOA:** 
nothing yet configured

**8) AAPI:** 
nothing yet configured

I believe that's all that's necessary to create a new study with the same functionality as our currently available Study 1. I created a new [Study](https://csis.myclimateservice.eu/study/13/view/intro) (everyone with an admin account should be able to view this) and only filled out the initial form so far. 

@therter, @p-a-s-c-a-l, @fgeyer16: Are there any other fields in the GL-Steps that need to be automatically filled upon creation, which I might have missed? 

**Note:** Keep in mind the current [step-by-step wizard](https://github.com/clarity-h2020/docker-drupal/issues/72#issuecomment-504327557) implementation. So right after creating a new study, dont be surprised if only the "Hazard Characterization" step is clickable :-)

**Comment by p-a-s-c-a-l** [comment]
So we'll keep the steps? I remember there was a discussion / proposal to remove them entirely. 😕 

Anyway. ATM the information in newly created steps is all we need. EMIKAT id is added to the study by [this trigger](https://github.com/clarity-h2020/emikat/issues/6), right?

Note: Eventually we [switch from ReactMount to iFrames](https://github.com/clarity-h2020/map-component/issues/37), then we have to update the default Map and Table Components.

**Comment by patrickkaleta** [comment]
> So we'll keep the steps? I remember there was a discussion / proposal to remove them entirely. 😕

I'm aware of the discussion started by @DenoBeno to remove the GL-Step entity type and have it all in the study group. But as you rightly mentioned this would have a major impact on all we have so far developed. So (to my recollection) the conclusion was to continue the way it is right now, while Denis works in parallel on his proposal without disrupting our current implementation.
> 
> Anyway. ATM the information in newly created steps is all we need. EMIKAT id is added to the study by [this trigger](https://github.com/clarity-h2020/emikat/issues/6), right?
> 

Correct.
> Note: Eventually we [switch from ReactMount to iFrames](https://github.com/clarity-h2020/map-component/issues/37), then we have to update the default Map and Table Components.

Updating the corresponding Business rules to include the updated components is not a problem. For already existing studies with GL-steps showing the then obsolete components, I suggest to update them manually.

**Comment by DenoBeno** [comment]
Last week someone complained that they don't see the "add study" button. (could be false flag too)

Please double-check if this button is shown to all the user types that are allowed to add studies.

**Comment by LenaStr** [comment]
I can not see the add study button on CSIS, meaning I can not play around with studies.

Also, other people (i.e. Anna from WSP) has had problems with adding Solution Offers and Showcases.

It is important that we can start to test the system and produce material.

Best,
Lena

Från: Denis Havlik [mailto:notifications@github.com]
Skickat: den 19 augusti 2019 15:16
Till: clarity-h2020/docker-drupal
Kopia: Subscribed
Ämne: Re: [clarity-h2020/docker-drupal] Adding new Studies in the CSIS (#83)


Last week someone complained that they don't see the "add study" button. (could be false flag too)

Please double-check if this button is shown to all the user types that are allowed to add studies.

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/docker-drupal/issues/96

**Comment by patrickkaleta** [comment]
> Last week someone complained that they don't see the "add study" button. (could be false flag too)
> 
> Please double-check if this button is shown to all the user types that are allowed to add studies.

The "Create a new Study" button is **currently only visible to administrators** and until #90 is fully resolved, I wouldn't change that. In the end I guess every authenticated user (so everyone who has an account) should be able to create a new Study.

**Comment by DenoBeno** [comment]
Please note that #90 has been resolved. Now we need testers.

**Comment by DenoBeno** [comment]
To the best of my knowledge, adding new studies and changing the study type works as designed now.

**Comment by p-a-s-c-a-l** [comment]
I created a [new study](https://csis.myclimateservice.eu/group/28) of type [Basic Screening: General ](https://csis.myclimateservice.eu/taxonomy/study-type/basic-screening) by following the [create new study link](https://csis.myclimateservice.eu/group/add/study). The result is a study group without navigation tabs:

![grafik](https://user-images.githubusercontent.com/1788226/64428618-7a88ff00-d0b4-11e9-95aa-15c50122d0f5.png)

**Comment by DenoBeno** [comment]
Hm.

The GL-steps are generated as they should, but you should end up on the https://csis.myclimateservice.eu/study/<node-id>/view/intro. However, the https://csis.myclimateservice.eu/study/28/view/intro doesn't exist, because the alias hasn't been generated.

![image](https://user-images.githubusercontent.com/2961790/64481572-693c1180-d1de-11e9-8c9d-7e676beba7b6.png)

It should be, according to 
https://csis.myclimateservice.eu/admin/config/search/path/patterns/study_group?destination=/admin/config/search/path/patterns

I run the "bulk generate aliases" and now it's OK. But this shouldn't happen. Is this somehow related to "rules" not working occasionally? Now the bulk path generation occasionally fails too?

**Comment by patrickkaleta** [comment]
Turns out the problem was caused by the `Country` and the `City` field, which is a dependent field created with Business Rules. We implemented this dependent field, since it allows to dynamically limit the cities based on the selected country. And for some reasons this dependent field is messing with Pathauto (seems like a new bug and just now a new development version of pathauto was introduced, I will check this out later).

For now, I removed the `Country` and `City` selection from the initial form. The URL aliases are now created as expected and the `Country` and `City` can still be set in the Context tab of the Study (as it was already the case).

On a related note, I also made the `Study type` field a requirement, since the new Business rules cannot work without a Study type being selected.

**Comment by DenoBeno** [comment]
I just read the initial entry on "Updating business rules for automatically creating GL-step entitites". This is completely outdated now, it would be good to close this issue and open a new one if necessary.

**Comment by patrickkaleta** [comment]
> I just read the initial entry on "Updating business rules for automatically creating GL-step entitites". This is completely outdated now, it would be good to close this issue and open a new one if necessary.

You're probably right, but before we close this issue let me just first remove this outdated rules, actions and variables from the system. Looking at the Business rules overview, it's really starting to get confusing.

**Comment by DenoBeno** [comment]
I have removed all the garbage from the rules. This could be in principle closed, but something has been seriously messed up lately. First this:

![image](https://user-images.githubusercontent.com/2961790/65380153-37927280-dcd5-11e9-8319-6cd6447d0c05.png)

And second, when I try to edit a rule, it causes "out of memory" error. Not always, but quite often. Cleaning the cache helps for a short time.

**Comment by DenoBeno** [comment]
why is this still open?
