### ISSUE TITLE
Using two different sources for defining ServiceType of dp_resources and dp_references

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#85]
@DenoBeno informed me that for the content type **dp_reference** the [reference_type](https://csis.myclimateservice.eu/admin/structure/types/manage/dp_reference/fields/node.dp_reference.field_reference_type/storage) field uses a list of strings, while the **dp_resource** uses the [DP_serviceType](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/service_type/overview) taxonomy to define its ServiceType.

In his opinion, if both describe the same thing, it's a bad idea to use different sources (the available items are already not consistent) and we should change the **dp_reference** to use the taxonomy as well.

@maesbri Is the `reference_type` field in the **dp_reference** describing the same thing as the `ServiceType` in the **dp_resource** (which is set in the Categorization - Tags field) or are those two different things (in which case this issue could be closed again)?

@p-a-s-c-a-l , @therter 
From Drupal-side it wouldn't be a problem to change the **dp_reference** and use another field to describe the `reference_type`, since it's barely used ATM. Is that also the case for the external components?

**Comment by p-a-s-c-a-l** [comment]
> Is that also the case for the external components?

No, it's not. I wouldn't touch dp_reference any more, it will break our components (again). reference_type is a string. This is simple and exactly what we want. No taxonomies please. Instead, it would even be better to replace ServiceType by a list of strings. This keeps the JSON less complicated to handle. IMHO those are two separate things, there should be a documentation in https://github.com/clarity-h2020/data-package that explain the difference, but i cannot find it.

Example why we need both:
- service_type = EMIKAT
- reference_type  = mapview:wms

IMHO service type applies to the path, so the default representation of the resource.

**Comment by patrickkaleta** [comment]
> > Is that also the case for the external components?
> 
> No, it's not. I wouldn't touch dp_reference any more, it will break our components (again). ... IMHO those are two separate things...

Alright, let's keep it the way it is.

>reference_type is a string. This is simple and exactly what we want. No taxonomies please. Instead, it would even be better to replace ServiceType by a list of strings. This keeps the JSON less complicated to handle.

Changing the ServiceType to a list of strings would make things more difficult on the Drupal-side. **However**, I just thought about the possibility to use Business Rules to automatically fill in a new field (which would be hidden to the user) with simple strings based on what the user selected in the ServiceType. That should make things easier for you, since you could focus on that simplified field instead of the original ServiceType field. I first need to check the feasibility of this idea.

**Comment by p-a-s-c-a-l** [comment]
> **However**, I just thought about the possibility to use Business Rules to automatically fill in a new field (which would be hidden to the user) with simple strings based on what the user selected in the ServiceType.

OK. I don't think that it's worth the effort. We should then keep ServiceType  it as it is and I'll work with what is available **now**.
