### ISSUE TITLE
Level of detail for terms in DP_ServiceType taxonomy

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/docker-drupal#86]
Another question raised by @DenoBeno was if the current state of [ServiceType](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/service_type/overview) taxonomy will suffice for further usage. E.g. there is a term "emikat", but will that alone be enough to tell how to handle the service, since Emikat could potentially provide multiple services using wms, wfs, wcs, json, xml,...

@therter @maesbri any thoughts about this? Do we need to expand the taxonomy, use some kind of hierachy or something else?

**Comment by p-a-s-c-a-l** [comment]
At the moment ServiceType isn't recognized by any of our components. How to handle resource URLs is ATM controlled by the type of the reference e.g. *@ mapview:wms*. In the future, we may also have a look at the service type and, in case of EMIKAT, substitute `$study_id` in the reference URL with the value taken from the study group entity.

**Comment by p-a-s-c-a-l** [comment]
As mentioned [here](https://github.com/clarity-h2020/docker-drupal/issues/85#issuecomment-517638669), from implementation point of view it would ServiceType list of strings instead of a taxonomy.
