### ISSUE TITLE
List fields with numeric values broken (solved)

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#88]
Today I noticed that the "list" fields don't work with numeric keys. 

Patrick traced the issue down to incompatibility with the "select or other" module. It works again with the latest version of the select or other module.

**Comment by patrickkaleta** [comment]
Just for documenation, [this](https://www.drupal.org/node/3052563) was the problem, which was fixed in the latest (1.0-alpha4) version of the module.
