### ISSUE TITLE
Geolocation module can be removed

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#89]
I managed to produce a reasonably good map + list view with geofield and related modules. Consequently, we do not need geolocation and related modules anymore.

I have already disabled the modules in the admin gui, they aren't used anywhere and can be removed from the image now.

**Comment by DenoBeno** [comment]
can this be closed?

**Comment by patrickkaleta** [comment]
Yes, module has been removed. Closing this issue.
