### ISSUE TITLE
create content type "data package" 

### ISSUE THREAD

**Issue by fgeyer16** [clarity-h2020/docker-drupal#9]
May be for the moment just an "empty" content type since the needed fields are not clear ( at least for me)
proposed fields:
- a field containing the url to the metadata on ckan (link or just text? or iframe?)
- References to properties. This has to be discussed on telco on 10th of September
- maybe a field containing the metadata from ckan? If they are not changing frequently. Showing in Summary would be easier then.

**Comment by p-a-s-c-a-l** [comment]
Depends on https://github.com/clarity-h2020/csis/issues/13 and https://github.com/clarity-h2020/csis/issues/20 and @humerh

**Comment by fgeyer16** [comment]
This is a duplicate of https://github.com/clarity-h2020/docker-drupal/issues/19
so I am closing this one.
