### ISSUE TITLE
Support for changing the study type

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#91]
Related to #90 : what happens if user changes the study type?

Or better said, what *should* happen?

Should all the gl_steps be reset/deleted? Or the ones that aren't allowed in this study type hidden (unpublished)?

**Comment by p-a-s-c-a-l** [comment]
There is no need for changing the study type. We shouldn't support this feature.

**Comment by DenoBeno** [comment]
See last comment at #92
