### ISSUE TITLE
Support for changing the study area

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#92]
Related to #90 and #91 :

What (should) happen if the user changes the study area.

Two options : within the same city or change the country/city first?

Should we leave the existing content in place or reset/delete all gl_steps?

@humerh : Does emikat need to reset the study on its side? Can it do so?

**Comment by DenoBeno** [comment]
I could post a separate issue for changing of a data package, but it sounds as overkill.

In my opinion, all these changes should have the same result: 

1) warn the user that all the information in the 
2) delete or reset all gl_steps and the study in emikat.

Effectively, the user gets a new study....

**Comment by p-a-s-c-a-l** [comment]
> What (should) happen if the user changes the study area.

Same as [here](https://github.com/clarity-h2020/docker-drupal/issues/91#issuecomment-522442405): We don't support it, specially for reasons of consistency (what happens with report images referring to the old study area?) and KISS.

If the user wants a new study area, he has to create a new study. So after the implementation and testing phase, study area can only be defined once and then not be changed any more. This could be handled inside of the map-component by @therter.

> Effectively, the user gets a new study....

Exactly!

**Comment by DenoBeno** [comment]
I agree that we need to assure consistency. This boils down to "new study type or area== new study"

Possibility one:  assure that users can't edit the study type, country, city and area once they have been defined.

Possibility two: the GL steps are deleted, new ones added and effectively one has a new study.

Note: We may get the possibility two implemented "for free" when we implement study type dependent studies - I'll explain this separately.

**Comment by humerh** [comment]
If some changes the Study area, CSIS has to trigger a general "forceRecalculation" on the Emikat side.

**Comment by p-a-s-c-a-l** [comment]
ATM we cannot implement this feature in the StudyAreaMap. See https://github.com/clarity-h2020/map-component/issues/52 for the reasons.

So if this is **really** required, the trigger has to be implemented in Drupal.

**Comment by DenoBeno** [comment]
The re-calculation triggering already works.
Whenever a study area or a data package changes, EMIKAT calculates again...

This has been implemented long ago by Patrick, just not clearly communicated.

What should be done is to avoid triggering the re-calculation if "expert" study types are used. Not very high priority, but it's a waste of resources on EMIKAT side.
