### ISSUE TITLE
Which fields do we need in a template?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#93]
Related to the work I just reported under #90 , it's important to know what template should contain. And which fields should be set.

The way I understand it, this is what needs to be in a template:

![image](https://user-images.githubusercontent.com/2961790/63283986-e72d8c80-c2b2-11e9-8f73-a39b3755b35e.png)

I'm not sure about the "MCDA *" fields. Do we need them in all steps? Just in one step?  

Since we are going to work with "real" templates, we could clean this up and leave the MCDA fields only in the steps where it's needed. And if that's only one step, *maybe* it should be moved to the group (I don't really care, but having clean templates would be good IMO).

**Comment by DenoBeno** [comment]
btw, I have cleaned up "Edit as template" a bit. See e.g.  https://csis.myclimateservice.eu/node/add/gl_step/template

![image](https://user-images.githubusercontent.com/2961790/63285065-396fad00-c2b5-11e9-964c-bd92abe95cba.png)

**Comment by p-a-s-c-a-l** [comment]
> I'm not sure about the "MCDA *" fields. Do we need them in all steps? Just in one step?

We need them in RA/IA. **I wouldn't touch them now!** Maybe we need some more. MCDA app implementation is currently on hold until we have have real impact results and adaptation scenarios to compare.

**Comment by p-a-s-c-a-l** [comment]
[Scenario Analysis App doesn't work anyore](https://github.com/clarity-h2020/scenario-analysis/issues/15): 

`node object is null or field "field_mcda_decision_strategy" is empty!`

Did you remove any of the mcda fields or their default values?

**Comment by DenoBeno** [comment]
No, I didn't remove anything. At least not from the groups as they are today. I also didn't change anything in the "old" way of adding groups as far as I can remember, but I can double-check.

I'm trying to make the new adding of a group work, but everything I do is limited to a group 17 and only done on group updates. And it doesn't work yet, sorry.

**Comment by DenoBeno** [comment]
FYI: i asked which fields we need just to know which ones to have pre-filled in the templates. I haven't changed the data model of GL-step

**Comment by DenoBeno** [comment]
Nothing to do here at the moment. If we ever want to change the data model, rules will not mind.
