### ISSUE TITLE
If EU-GL title (name) is the same as GL-Step, why isn't this enforced?

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#94]
Related to: #39 , #90 

It seems to me that EU-GL step name is always the same as the EU-GL step taxonomy used for this step. If so, why don't we generate the title on the fly?

And why isn't the "EU-GL step" (field_field_eu_gl_methodology) mandatory field?

**Comment by p-a-s-c-a-l** [comment]
How does this relate to the GL-Step templates? It makes sense to use different titles for different templates of the same type e.g. "simple HC" vs "Expert HC" GL-Step otherwise it's hard to know to which study template the template step belongs to.

Is `name` the same as `title`?

**Comment by patrickkaleta** [comment]
> Is `name` the same as `title`?

Yes, for the GL-Step entity that's the case, since we are using **"Name"** as the label for the `title` field. (This can be set/changed [here](https://csis.myclimateservice.eu/admin/structure/types/manage/gl_step)).

**Comment by DenoBeno** [comment]
This is not important anymore. 

1) I am using the title to describe the template and it can be anything now.
2) Rules set the title for the steps based on the information in another template field. If we want, we can give the steps different names depending on the study type now. But we don't have to.

Seems like a good solution to me - closing.
