### ISSUE TITLE
Urgently need busines rules beta 8!

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#95]
I run in a problem with busines rules that is allegedly fixed in beta 8. This is really urgent - without this we can't support adding new studies of different types.

@fgeyer16 : see this https://csis.myclimateservice.eu/admin/config/workflow/business_rules/action/loop_through_step_templates/edit

What this SHOULD do is to loop through templates and show some debug information on https://csis.myclimateservice.eu/study/17

As you can see from the illustration, it really gets the node ide-s correctly in a loop (it's in {{study_type_step_templates->nid}}  variable), but it doesn't fetch the nodes by id in a loop

This fails in a loop: https://csis.myclimateservice.eu/admin/config/workflow/business_rules/action/fetch_step_templ_by_id/edit?destination=/admin/config/workflow/business_rules/action/loop_through_step_templates/edit

It does work if I put a static ID in it, so it's really a bug...

![image](https://user-images.githubusercontent.com/2961790/63356050-6e3c3c80-c367-11e9-8f76-abef3f6c1fa8.png)

related drupal bug report: https://www.drupal.org/project/business_rules/issues/3020852#comment-13228933

Final comment implies that beta 8 should work

**Comment by patrickkaleta** [comment]
Business_rules has been updated to beta8. 
Closing this issue now even though this update didn't fix the problem mentioned above. Discussion on that problem continues in #90.
