### ISSUE TITLE
Need rights for creating studies

### ISSUE THREAD

**Issue by LenaStr** [clarity-h2020/docker-drupal#96]
I can not create a study in the CSIS. (I assume this is a general problems, all editorial users should have the rights to create and edit studies.)

**Comment by p-a-s-c-a-l** [comment]
BTW, [study templates](https://github.com/clarity-h2020/docker-drupal/issues/90) for expert studies are not ready yet. So ATM it's not recommended to create new studies.

**Comment by LenaStr** [comment]
When will expert studies templates be ready? Anyhow it would be very valuable to create something related to sweden for the Swedish workshop on the 5th

**Comment by patrickkaleta** [comment]
> When will expert studies templates be ready? Anyhow it would be very valuable to create something related to sweden for the Swedish workshop on the 5th

@LenaStr: Then we will try to have this ready and working before the 5th (I'm assuming you mean September?), but ATM I can't say for sure when we will have solved all the related issues with this.

@p-a-s-c-a-l, @DenoBeno: I stumbled upon this [bug](https://www.drupal.org/project/drupal/issues/2920527) affecting systems using:

1. a Postgres DB 
2. the Group module 
3. and any third module that triggers a DB query inside another DB query (in our case the Business rules module). 

This bug makes it impossible for users without admin-rights to create a new study. Already talked to @fgeyer16 about this and tested the available patch locally, which fixes the issue. I will apply this patch on the CSIS now.

**Comment by LenaStr** [comment]
I need at least one week before the fifthe to prepare for the demo. (If not available we have to think of something else.)

**Comment by DenoBeno** [comment]
I am almost finished with templates, will be finalized this evening. As for the permissions, is this working now?

**Comment by DenoBeno** [comment]
I can't help with this one, getting myself out of the loop

**Comment by p-a-s-c-a-l** [comment]
@LenaStr Is the problem solved? Are you able to create new Data Packages and [new Studies](https://github.com/clarity-h2020/docker-drupal/issues/83#issuecomment-524495206)?

**Comment by LenaStr** [comment]
Yes, I am able to create new data packages and studies now.

(Do not get any EU-GL steps in the studies I am playing with, but I guess this is something you are working on for the moment.)

/Lena

Från: Pascal Dihé [mailto:notifications@github.com]
Skickat: den 26 augusti 2019 10:54
Till: clarity-h2020/docker-drupal
Kopia: Strömbäck Lena; Mention
Ämne: Re: [clarity-h2020/docker-drupal] Need rights for creating studies (#96)


@LenaStr<https://github.com/LenaStr> Is the problem solved? Are you able to create new Data Packages and new Studies<https://github.com/clarity-h2020/docker-drupal/issues/83#issuecomment-524495206>?

**Comment by p-a-s-c-a-l** [comment]
> (Do not get any EU-GL steps in the studies I am playing with, but I guess this is something you are working on for the moment.)

No, that should be working right now! @DenoBeno  ?
What's the study you are playing with?

**Comment by DenoBeno** [comment]
Adding studies should work since Friday.

Which study type did you add?

**Comment by LenaStr** [comment]
I have played with different types of studies:


This is what I get: (Mening I can only set up the basics)

Which one should I choose?

[cid:image001.png@01D55C26.3940FA50]
Från: Denis Havlik [mailto:notifications@github.com]
Skickat: den 26 augusti 2019 15:46
Till: clarity-h2020/docker-drupal
Kopia: Strömbäck Lena; Mention
Ämne: Re: [clarity-h2020/docker-drupal] Need rights for creating studies (#96)


Adding studies should work since Friday.

Which study type did you add?

**Comment by DenoBeno** [comment]
Well, most of them should be producing data. You can also play with changing the study type - every time you do so, old gl-steps get deleted and new ones added.

Pascal, can you test? I'm in a car..

**Comment by DenoBeno** [comment]
Ah, I see what's the issue. Will be fixed in a few minutes.

**Comment by DenoBeno** [comment]
OK, fixed. At least part of the issue was that I didn't explicitly set the author of the new nodes to ds up being owned by the author of the original node. So now we have a whole lot of EU-GL step nodes that are owned by Deno...

Works now.

**Comment by DenoBeno** [comment]
Ah, btw. don't worry about not having all the apps/widgets working yet. This can be fixed manually later (for a few studies).
