### ISSUE TITLE
Please assign the EU-GL step templates to study types and assure that they are configured correctly

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/docker-drupal#99]
related to https://github.com/clarity-h2020/docker-drupal/issues/39

@p-a-s-c-a-l : I need you to double check all the "default" templates and assure they are correctly assigned to the studies. Tell me if you need more templates. 

FYI: 

**All the currently defined templates can be easily found now [here](https://csis.myclimateservice.eu/admin/content?title=template&type=gl_step&status=All&langcode=All&order=title&sort=asc)**

**I have defined two sets of templates:** 

1. "default" ones are exactly as they were in our studies so far. Except that the MCDA information is only set in the Assess Risks and Impact step . That's this one: https://csis.myclimateservice.eu/node/938/edit/template . Since I have no idea which applications are working now, it's best if you go through them and assure that all is correct.

2. "simple" ones are rather empty at the moment - just maps and twins. I will rename them to "testing" because that's what they are used for now - testing how new features work without breaking the studies that use the "standard" template type.

3. Assigning the templates to study types can be done quite easily, just edit the corresponding taxonomy term. https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/study_type/overview

**Comment by p-a-s-c-a-l** [comment]
ATM the MCDA App is broken, probably due to [**undocumented** format changes in the EMIKAT API](https://github.com/clarity-h2020/scenario-analysis/issues/15#issuecomment-524209258). Therefore I'm going to remove it from all Assess Risks and Impact step templates until the problem has been fixed.

Transformation of Map Component to iFrame is in progress, once completed, this will require to change **all** step temples that use a map component. I'm going to test the new iFrame based Map Component in the "testing" templates first, the "default" templates will continue to use the ReactMount Map Component for now.

**Comment by p-a-s-c-a-l** [comment]
Or maybe it's better to hide the the [Scenario Analysis Tab](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_7) completely and re-enable when the APIs have stabilised.

@patrickkaleta What would be the best option to hide `Assess Risks and Impact/Scenario Analysis`? Maybe set `Page settings/permissions` to role:administrator ?

**Comment by DenoBeno** [comment]
There is a more general ticket asking for a way to hide sub-steps. I didn't look at the way they are implemented, but I suspect that they might disappear if there is nothing to show or if the system cannot show anything.

**Comment by patrickkaleta** [comment]
> Or maybe it's better to hide the the [Scenario Analysis Tab](https://csis.myclimateservice.eu/admin/structure/views/view/view_mode_for_gl_step/edit/page_7) completely and re-enable when the APIs have stabilised.
> 
> @patrickkaleta What would be the best option to hide `Assess Risks and Impact/Scenario Analysis`? Maybe set `Page settings/permissions` to role:administrator ?

[ That's](https://github.com/clarity-h2020/csis/issues/81#event-2577564511) the issue Denis is talking about. I'm working on that now and during that process I will hide the Scenario Analysis tab.

**Comment by p-a-s-c-a-l** [comment]
If I want to replace map components (Extended iFrame) in e.g. all [Characterize Hazard](https://csis.myclimateservice.eu/admin/content?title=Characterize+Hazard&type=gl_step&status=All&langcode=All) steps, how can this be done?

**Comment by p-a-s-c-a-l** [comment]
> @p-a-s-c-a-l : I need you to double check all the "default" templates and assure they are correctly assigned to the studies. Tell me if you need more templates.

We should remove the following steps from all study templates, since we there's ATM nothing to show there:
 -  Analyze vulnerability step See https://github.com/clarity-h2020/csis/issues/16#issuecomment-507636499
-  Appraise Adaptation Options
- Implement/Integrate Adaptation Action Plan

**Comment by DenoBeno** [comment]
in all the existing ones? Either by a rule or with a bulk edit.

**Comment by p-a-s-c-a-l** [comment]
> bulk edit.

is bulk edit installed? where do it find it?

**Comment by DenoBeno** [comment]
> 
> 
> > @p-a-s-c-a-l : I need you to double check all the "default" templates and assure they are correctly assigned to the studies. Tell me if you need more templates.
> 
> We should remove the following steps from all study templates, since we there's ATM nothing to show there:
> 
>     * Analyze vulnerability step See [clarity-h2020/csis#16 (comment)](https://github.com/clarity-h2020/csis/issues/16#issuecomment-507636499)
> 
>     * Appraise Adaptation Options
> 
>     * Implement/Integrate Adaptation Action Plan

OK, I'm removing these steps from all templates.

**Comment by DenoBeno** [comment]
> 
> 
> > @p-a-s-c-a-l : I need you to double check all the "default" templates and assure they are correctly assigned to the studies. Tell me if you need more templates.
> 
> We should remove the following steps from all study templates, since we there's ATM nothing to show there:
> 
>     * Analyze vulnerability step See [clarity-h2020/csis#16 (comment)](https://github.com/clarity-h2020/csis/issues/16#issuecomment-507636499)
> 
>     * Appraise Adaptation Options
> 
>     * Implement/Integrate Adaptation Action Plan

I'm a bit confused by https://csis.myclimateservice.eu/taxonomy/term/2221

Expert studies can in principle have any steps they want to add to the data package. Except the "local effects", makes no sense to have that in the expert mode.

**Comment by p-a-s-c-a-l** [comment]
> I'm a bit confused by https://csis.myclimateservice.eu/taxonomy/term/2221

Yes, some steps are missing here.

**Comment by p-a-s-c-a-l** [comment]
is bulk edit installed? where do it find it?

**Comment by DenoBeno** [comment]
> 
> 
> If I want to replace map components (Extended iFrame) in e.g. all [Characterize Hazard](https://csis.myclimateservice.eu/admin/content?title=Characterize+Hazard&type=gl_step&status=All&langcode=All) steps, how can this be done?

This way.

0. Be careful. With great power...
1. Go here: https://csis.myclimateservice.eu/maintenance/gl-steps
2. Carefully filter the nodes you need. E.g. I'm doing this with the test template only now.

![grafik](https://user-images.githubusercontent.com/2961790/64345910-747e1a00-cff1-11e9-9d17-230217c1a584.png)

3. choose the ones you really want to edit ("2" on illustration above), then click on "Modify field values"
4. chose the variable you want to set, then choose the value.
![grafik](https://user-images.githubusercontent.com/2961790/64346238-0c7c0380-cff2-11e9-8734-e587c95ad447.png)
5. Click "Apply"

**Comment by DenoBeno** [comment]
I have added a second bulk-edit form for the study types. This one is allowed for administrators and editors.

![grafik](https://user-images.githubusercontent.com/2961790/64445092-f47db000-d0d5-11e9-8ded-ecf9e5c5efc8.png)

This is good for assigning or adding steps to several studies at a time and also provides a good overview.

![grafik](https://user-images.githubusercontent.com/2961790/64445206-34449780-d0d6-11e9-8d74-3d4ecec39cee.png)

If "add multi values" is enabled, the entry will only be added to existign ones. Otherwise teh old ones will be overwritten.
---------------

I'm done with this, feel free to ask if you need anything else.

**Comment by therter** [comment]
The option "Select / deselect all results in this view" (see the red rectangle in the screenshot ) is very dangerous, because this option ignores the applied filter. If the user use this option, all workflow steps will be selected and not only the steps, which fulfil the current filter criteria.  
Especially when the user has more than one page with matches, he will mostly assume that only the matches are selected. 

![BulkEdit](https://user-images.githubusercontent.com/1788509/64951843-1bc74080-d87f-11e9-81b1-36ec37ea45ec.png)

**Comment by patrickkaleta** [comment]
Nice catch @therter. That checkbox is should be either fixed or removed. I'll look into it

**Comment by DenoBeno** [comment]
This is IMO a bug in the module. I'll report it.

**Comment by therter** [comment]
Additional info:
Until this bug is fixed, it is of course possible to use the check boxes next to the titles to mark a single step, or the checkbox in the table header to select all steps of the current page. The number of selected steps  is shown under the apply button and should be used to ensure that not accidentally too many steps are selected.

**Comment by DenoBeno** [comment]
Can we close this now?

**Comment by p-a-s-c-a-l** [comment]
no, we have to add the new table components when they are finished.

**Comment by p-a-s-c-a-l** [comment]
OK, Study types are now configured. Main difference between basic screening, advanced screening and expert is that only in advanced screening (with EMIKAT calculation) we show table components (because they depend on EMIKAT API).

![grafik](https://user-images.githubusercontent.com/1788226/65665687-6ba2c600-e03c-11e9-93ff-53a848ebfd7a.png)

**Comment by DenoBeno** [comment]
> Additional info:
> Until this bug is fixed, it is of course possible to use the check boxes next to the titles to mark a single step, or the checkbox in the table header to select all steps of the current page. The number of selected steps is shown under the apply button and should be used to ensure that not accidentally too many steps are selected.

just FYI, I have removed paging now. For now it's OK, in the future this might cause the view to load extremely long. But by then maybe the bug will be fixed upstreams.
